import os
import re
import shutil
import subprocess
import sys

XLIB_MODULE = "github.com/75912001/xlib"
COLOR_GREEN = "\033[32m"
COLOR_RED = "\033[31m"
COLOR_RESET = "\033[0m"


def print_ok(message):
    print(f"{COLOR_GREEN}{message}{COLOR_RESET}")


def print_error(message):
    print(f"{COLOR_RED}{message}{COLOR_RESET}", file=sys.stderr)


def run_cmd(cmd, cwd=None):
    print(f"Executing: {subprocess.list2cmdline(cmd)}")
    res = subprocess.run(cmd, capture_output=True, text=True, cwd=cwd)
    if res.returncode != 0:
        print_error(f"Error: {res.stderr}")
        sys.exit(res.returncode)
    return res.stdout


def check_tool(name):
    if shutil.which(name) is None:
        print_error(f"Error: '{name}' not found in PATH. Please install it first.")
        sys.exit(1)


def check_dir(path, desc):
    if not os.path.isdir(path):
        print_error(f"Error: {desc} not found: {path}")
        sys.exit(1)


def check_file(path, desc):
    if not os.path.isfile(path):
        print_error(f"Error: {desc} not found: {path}")
        sys.exit(1)


def get_go_module_dir(module, cwd):
    out = run_cmd(["go", "list", "-m", "-f", "{{.Dir}}", module], cwd=cwd).strip()
    if not out:
        print_error(f"Error: go module dir is empty: {module}")
        sys.exit(1)
    return out


def get_grpc_x_plugin_path(xlib_dir):
    if sys.platform.startswith("win"):
        name = "protoc-gen-go-grpc-x"
    elif sys.platform == "darwin":
        name = "protoc-gen-go-grpc-x-mac"
    else:
        name = "protoc-gen-go-grpc-x-linux"

    return os.path.join(xlib_dir, "grpc", "proto", "bin", name)


def discover_protos(proto_dir):
    """
    扫描 proto_dir，返回两个列表：
      - all_protos  : 所有 .proto（排除 options.proto，它只作 import 用）
      - grpc_protos : 仅 *.grpc.proto（需要 grpc / grpc-x 插件生成）
    """
    all_protos, grpc_protos = [], []
    for fname in sorted(os.listdir(proto_dir)):
        if not fname.endswith(".proto") or fname == "options.proto":
            continue
        all_protos.append(fname)
        if ".grpc." in fname:
            grpc_protos.append(fname)
    return all_protos, grpc_protos


# ─── CMD proto 生成 ───────────────────────────────────────────────────────────

_RE_CMD_COMMENT = re.compile(r'^\s*//\s*(0x[0-9A-Fa-f]+)#([^#]+)#(.+)')
_RE_MESSAGE     = re.compile(r'^\s*message\s+(\w+)')
_RE_PACKAGE     = re.compile(r'^\s*package\s+(\w+)')
_RE_GO_PACKAGE  = re.compile(r'^\s*option\s+go_package\s*=\s*"([^"]+)"')


def _parse_source_proto(path):
    """
    解析源 proto 文件，返回：
      package, go_package, entries[(hex_val, direction, desc, msg_name)]
    """
    package, go_package = "", ""
    entries = []
    pending = None

    with open(path, encoding="utf-8") as f:
        for line in f:
            m = _RE_PACKAGE.match(line)
            if m:
                package = m.group(1)
                continue
            m = _RE_GO_PACKAGE.match(line)
            if m:
                go_package = m.group(1)
                continue
            m = _RE_CMD_COMMENT.match(line)
            if m:
                pending = (m.group(1), m.group(2), m.group(3).strip())
                continue
            if pending:
                m = _RE_MESSAGE.match(line)
                if m:
                    entries.append((*pending, m.group(1)))
                pending = None

    return package, go_package, entries


def gen_cmd_protos(proto_dir):
    """
    扫描 proto_dir 中的源 proto 文件（排除 *.cmd.proto / options.proto），
    若文件中含 //0xHEX#from->to#描述 注释，则生成对应的 *.cmd.proto 枚举文件。
    """
    for fname in sorted(os.listdir(proto_dir)):
        if not fname.endswith(".proto"):
            continue
        if ".cmd." in fname or fname == "options.proto":
            continue

        src = os.path.join(proto_dir, fname)
        package, go_package, entries = _parse_source_proto(src)

        if not entries:
            continue

        # 枚举名 / zero-value 名：user.proto → MsgIDUser / UserMsgIDUnknown_CMD
        base      = fname.replace(".proto", "")          # "user"
        base_cap  = base.capitalize()                     # "User"
        enum_name = f"MsgID{base_cap}"                   # "MsgIDUser"
        zero_name = f"{base_cap}MsgIDUnknown_CMD"        # "UserMsgIDUnknown_CMD"

        out_path = os.path.join(proto_dir, f"{base}.cmd.proto")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("// Code generated by gen.py. DO NOT EDIT.\n\n")
            f.write('syntax = "proto3";\n')
            f.write(f"package {package};\n")
            f.write(f'option go_package = "{go_package}";\n')
            f.write(f"\nenum {enum_name} {{\n")
            f.write(f"  {zero_name} = 0; // proto3 首值必须为 0\n")
            for hex_val, direction, desc, msg_name in entries:
                comment = f"//{hex_val}#{direction}#{desc}"
                f.write(f"  {msg_name}_CMD = {hex_val}; {comment}\n")
            f.write("}\n")

        print_ok(f"生成 {base}.cmd.proto  ({len(entries)} 条 CMD)")


# ─── 主流程 ───────────────────────────────────────────────────────────────────

def main():
    # 当前 server 仓库根目录
    server_dir = os.path.dirname(os.path.abspath(__file__))
    # xlib 仓库与 server 同级
    xlib_dir = get_go_module_dir(XLIB_MODULE, server_dir)

    # --- 前置校验 ---
    check_tool("go")
    check_tool("protoc")
    check_dir(xlib_dir,                                              "xlib 仓库目录")
    check_dir(os.path.join(xlib_dir, "grpc", "proto"),              "xlib/grpc/proto (options.proto)")
    check_file(os.path.join(xlib_dir, "grpc", "proto", "options.proto"), "xlib/grpc/proto/options.proto")
    check_dir(os.path.join(xlib_dir, "thirdparty"),                 "xlib/thirdparty")

    proto_dir = os.path.join(server_dir, "proto")
    check_dir(proto_dir, "proto 目录")

    plugin_exe = get_grpc_x_plugin_path(xlib_dir)
    check_file(plugin_exe, "protoc-gen-go-grpc-x plugin")

    # 2. 根据源 proto 的 //0xHEX#... 注释生成 *.cmd.proto 枚举文件
    gen_cmd_protos(proto_dir)

    # 3. 扫描 proto 文件，分组（gen_cmd_protos 已将生成文件写入 proto_dir，会被发现）
    all_protos, grpc_protos = discover_protos(proto_dir)
    if not all_protos:
        print_error("Error: proto 目录中没有找到任何 .proto 文件")
        sys.exit(1)
    print(f"发现 proto 文件: {all_protos}")
    print(f"gRPC proto 文件: {grpc_protos}")

    out_dir = server_dir
    proto_path_args = [
        f"--proto_path={proto_dir}",
        f"--proto_path={os.path.join(xlib_dir, 'grpc', 'proto')}",
        f"--proto_path={os.path.join(xlib_dir, 'thirdparty')}",
    ]
    m_options = "Moptions.proto=github.com/75912001/xlib/grpc/proto"

    # 4a. 所有 proto → --go_out（普通消息、枚举）
    cmd_go = [
        "protoc",
        *proto_path_args,
        f"--go_out={out_dir}",
        f"--go_opt=module=server,{m_options}",
        *all_protos,
    ]
    run_cmd(cmd_go, cwd=server_dir)
    print_ok(f"[go_out] 生成完毕: {all_protos}")

    # 4b. *.grpc.proto → --go-grpc_out + --go-grpc-x_out（服务桩代码）
    if grpc_protos:
        cmd_grpc = [
            "protoc",
            *proto_path_args,
            f"--plugin=protoc-gen-go-grpc-x={plugin_exe}",
            f"--go-grpc_out={out_dir}",
            f"--go-grpc_opt=module=server,{m_options}",
            f"--go-grpc-x_out={out_dir}",
            "--go-grpc-x_opt=module=server",
            *grpc_protos,
        ]
        run_cmd(cmd_grpc, cwd=server_dir)
        print_ok(f"[go-grpc_out / go-grpc-x_out] 生成完毕: {grpc_protos}")

    print_ok("Done. 文件已输出至 proto/pb/")


if __name__ == "__main__":
    main()
