// Code generated by gen.register.message.sh. DO NOT EDIT.

package main

import (
	pb "server/proto/pb"

	xcontrol "github.com/75912001/xlib/control"
	xmessage "github.com/75912001/xlib/message"
	"google.golang.org/protobuf/proto"
)

var GMessage = xmessage.NewMgr()

func init() {
	registerMessages()
}

func registerMessages() {
	registerMessage(uint32(pb.MsgID_AccountVerifyReq_CMD), func() proto.Message { return &pb.AccountVerifyReq{} })
	registerMessage(uint32(pb.MsgID_AccountVerifyRes_CMD), func() proto.Message { return &pb.AccountVerifyRes{} })
	registerMessage(uint32(pb.MsgID_AccountOfflineReq_CMD), func() proto.Message { return &pb.AccountOfflineReq{} })
	registerMessage(uint32(pb.MsgID_AccountHeartbeatReq_CMD), func() proto.Message { return &pb.AccountHeartbeatReq{} })
	registerMessage(uint32(pb.MsgID_AccountHeartbeatRes_CMD), func() proto.Message { return &pb.AccountHeartbeatRes{} })
	registerMessage(uint32(pb.MsgID_AccountRecordReq_CMD), func() proto.Message { return &pb.AccountRecordReq{} })
	registerMessage(uint32(pb.MsgID_AccountRecordRes_CMD), func() proto.Message { return &pb.AccountRecordRes{} })
	registerMessage(uint32(pb.MsgID_CharacterCreateReq_CMD), func() proto.Message { return &pb.CharacterCreateReq{} })
	registerMessage(uint32(pb.MsgID_CharacterCreateRes_CMD), func() proto.Message { return &pb.CharacterCreateRes{} })
	registerMessage(uint32(pb.MsgID_RobotPingReq_CMD), func() proto.Message { return &pb.RobotPingReq{} })
	registerMessage(uint32(pb.MsgID_RobotPingRes_CMD), func() proto.Message { return &pb.RobotPingRes{} })
	registerMessage(uint32(pb.MsgID_CharacterOnlineReq_CMD), func() proto.Message { return &pb.CharacterOnlineReq{} })
	registerMessage(uint32(pb.MsgID_CharacterOnlineRes_CMD), func() proto.Message { return &pb.CharacterOnlineRes{} })
	registerMessage(uint32(pb.MsgID_CharacterOfflineReq_CMD), func() proto.Message { return &pb.CharacterOfflineReq{} })
	registerMessage(uint32(pb.MsgID_CharacterOfflineRes_CMD), func() proto.Message { return &pb.CharacterOfflineRes{} })
	registerMessage(uint32(pb.MsgID_SceneEnterReq_CMD), func() proto.Message { return &pb.SceneEnterReq{} })
	registerMessage(uint32(pb.MsgID_SceneEnterRes_CMD), func() proto.Message { return &pb.SceneEnterRes{} })
	registerMessage(uint32(pb.MsgID_CombatAutoEncounterSetReq_CMD), func() proto.Message { return &pb.CombatAutoEncounterSetReq{} })
	registerMessage(uint32(pb.MsgID_CombatAutoEncounterSetRes_CMD), func() proto.Message { return &pb.CombatAutoEncounterSetRes{} })
	registerMessage(uint32(pb.MsgID_CombatBattleStartNotify_CMD), func() proto.Message { return &pb.CombatBattleStartNotify{} })
	registerMessage(uint32(pb.MsgID_CombatRoundActionReq_CMD), func() proto.Message { return &pb.CombatRoundActionReq{} })
	registerMessage(uint32(pb.MsgID_CombatRoundActionRes_CMD), func() proto.Message { return &pb.CombatRoundActionRes{} })
	registerMessage(uint32(pb.MsgID_CombatRoundResultNotify_CMD), func() proto.Message { return &pb.CombatRoundResultNotify{} })
	registerMessage(uint32(pb.MsgID_CombatFlowCompleteReq_CMD), func() proto.Message { return &pb.CombatFlowCompleteReq{} })
	registerMessage(uint32(pb.MsgID_CombatFlowCompleteRes_CMD), func() proto.Message { return &pb.CombatFlowCompleteRes{} })
}

func registerMessage(messageID uint32, newProtoMessage func() proto.Message) {
	GMessage.Register(messageID, xmessage.NewOptions().
		WithHandler(xcontrol.NewCallBack(func(args ...any) error { return nil })).
		WithNewProtoMessage(newProtoMessage))
}
