# 角色-配置
# 任何修改此文件的行为都需要通知客户端和服务端开发人员

# character.isRole: 是否为玩家角色 (布尔值, 默认false)
# character.color: 角色颜色
# character.sprite: 按武器保存动作配置ID, 引用 character.sprite.yaml 中相同的 sprite[].id

# 角色 [1000000,1999999]
character:
############################################################
  - id: 1000000
    name: "吉米"
    isRole: true
    description: "吉米-红"
    color: "red"
    sprite: #[9289,10816] 1528 个文件
      unarmed: 0
      axe: 1
      stick: 2
      spear: 3
      bow: 4
######
  - id: 1000005
    name: "吉米"
    isRole: true
    description: "吉米-蓝"
    color: "blue"
    sprite: #[10817,12344] 1528 个文件
      unarmed: 5
      axe: 6
      stick: 7
      spear: 8
      bow: 9
######
  - id: 1000010
    name: "吉米"
    isRole: true
    description: "吉米-橙"
    color: "orange"
    sprite: #[12345,13872] 1528 个文件
      unarmed: 10
      axe: 11
      stick: 12
      spear: 13
      bow: 14
######
  - id: 1000015
    name: "吉米"
    isRole: true
    description: "吉米-棕"
    color: "brown"
    sprite: #[13873,15400] 1528 个文件
      unarmed: 15
      axe: 16
      stick: 17
      spear: 18
      bow: 19
############################################################
  # todo menglc  该角色的空手攻击,四个颜色不用. 可能需要适配修改.
  - id: 1000020
    name: "罗伦斯"
    isRole: true
    description: "罗伦斯-黄"
    color: "yellow"
    sprite: #[15401,16928] 1528 个文件
      unarmed: 20
      axe: 21
      stick: 22
      spear: 23
      bow: 24
######
  - id: 1000025
    name: "罗伦斯"
    isRole: true
    description: "罗伦斯-红"
    color: "red"
    sprite: #[16929,18456] 1528 个文件
      unarmed: 25
      axe: 26
      stick: 27
      spear: 28
      bow: 29
######
  - id: 1000030
    name: "罗伦斯"
    isRole: true
    description: "罗伦斯-蓝"
    color: "blue"
    sprite: #[18457,19984] 1528 个文件
      unarmed: 30
      axe: 31
      stick: 32
      spear: 33
      bow: 34
######
  - id: 1000035
    name: "罗伦斯"
    isRole: true
    description: "罗伦斯-黑"
    color: "black"
    sprite: #[19985,21512] 1528 个文件
      unarmed: 35
      axe: 36
      stick: 37
      spear: 38
      bow: 39
############################################################
  - id: 1000040
    name: "强普"
    isRole: true
    description: "强普-棕"
    color: "brown"
    sprite: #[21513,23040] 1528 个文件
      unarmed: 40
      axe: 41
      stick: 42
      spear: 43
      bow: 44
######
  - id: 1000045
    name: "强普"
    isRole: true
    description: "强普-黄"
    color: "yellow"
    sprite: #[23041,24568] 1528 个文件
      unarmed: 45
      axe: 46
      stick: 47
      spear: 48
      bow: 49
######
  - id: 1000050
    name: "强普"
    isRole: true
    description: "强普-黑"
    color: "black"
    sprite: #[24569,26096] 1528 个文件
      unarmed: 50
      axe: 51
      stick: 52
      spear: 53
      bow: 54
######
  - id: 1000055
    name: "强普"
    isRole: true
    description: "强普-红"
    color: "red"
    sprite: #[26097,27624] 1528 个文件
      unarmed: 55
      axe: 56
      stick: 57
      spear: 58
      bow: 59
############################################################
  - id: 1000060
    name: "库比"
    isRole: true
    description: "库比-黄"
    color: "yellow"
    sprite: #[27625,29152] 1528 个文件
      unarmed: 60
      axe: 61
      stick: 62
      spear: 63
      bow: 64
######
  - id: 1000065
    name: "库比"
    isRole: true
    description: "库比-蓝"
    color: "blue"
    sprite: #[29153,30680] 1528 个文件
      unarmed: 65
      axe: 66
      stick: 67
      spear: 68
      bow: 69
######
  - id: 1000070
    name: "库比"
    isRole: true
    description: "库比-棕"
    color: "brown"
    sprite: #[30681,32208] 1528 个文件
      unarmed: 70
      axe: 71
      stick: 72
      spear: 73
      bow: 74
######
  - id: 1000075
    name: "库比"
    isRole: true
    description: "库比-绿"
    color: "green"
    sprite: #[32209,33736] 1528 个文件
      unarmed: 75
      axe: 76
      stick: 77
      spear: 78
      bow: 79
############################################################
  - id: 1000080
    name: "卡伯菲"
    isRole: true
    description: "卡伯菲-粉"
    color: "pink"
    sprite: #[33737,35264] 1528 个文件
      unarmed: 80
      axe: 81
      stick: 82
      spear: 83
      bow: 84
######
  - id: 1000085
    name: "卡伯菲"
    isRole: true
    description: "卡伯菲-绿"
    color: "green"
    sprite: #[35265,36792] 1528 个文件
      unarmed: 85
      axe: 86
      stick: 87
      spear: 88
      bow: 89
######
  - id: 1000090
    name: "卡伯菲"
    isRole: true
    description: "卡伯菲-黄"
    color: "yellow"
    sprite: #[36793,38320] 1528 个文件
      unarmed: 90
      axe: 91
      stick: 92
      spear: 93
      bow: 94
######
  - id: 1000095
    name: "卡伯菲"
    isRole: true
    description: "卡伯菲-白"
    color: "white"
    sprite: #[38321,39848] 1528 个文件
      unarmed: 95
      axe: 96
      stick: 97
      spear: 98
      bow: 99
############################################################
  - id: 1000100
    name: "酋力安"
    isRole: true
    description: "酋力安-棕"
    color: "brown"
    sprite: #[39849,41372]  (NOTE: 126235,126236,126237,126238 单独再增加这四个文件,用在 stick.right 中. 见: defense,sad,angry ) 个文件
      unarmed: 100
      axe: 101
      stick: 102
      spear: 103
      bow: 104
######
  - id: 1000105
    name: "酋力安"
    isRole: true
    description: "酋力安-蓝"
    color: "blue"
    sprite: #[41373,42900] 1528 个文件
      unarmed: 105
      axe: 106
      stick: 107
      spear: 108
      bow: 109
######
  - id: 1000110
    name: "酋力安"
    isRole: true
    description: "酋力安-橙"
    color: "orange"
    sprite: #[42901,44428] 1528 个文件
      unarmed: 110
      axe: 111
      stick: 112
      spear: 113
      bow: 114
######
  - id: 1000115
    name: "酋力安"
    isRole: true
    description: "酋力安-黑"
    color: "black"
    sprite: #[44429,45956] 1528 个文件
      unarmed: 115
      axe: 116
      stick: 117
      spear: 118
      bow: 119
############################################################
  - id: 1000120
    name: "爱伦"
    isRole: true
    description: "爱伦-绿"
    color: "green"
    sprite: #[45957,47484]  个文件
      unarmed: 120
      axe: 121
      stick: 122
      spear: 123
      bow: 124
######
  - id: 1000125
    name: "爱伦"
    isRole: true
    description: "爱伦-黄"
    color: "yellow"
    sprite: #[47485,49012] 1528 个文件
      unarmed: 125
      axe: 126
      stick: 127
      spear: 128
      bow: 129
######
  - id: 1000130
    name: "爱伦"
    isRole: true
    description: "爱伦-蓝"
    color: "blue"
    sprite: #[49013,50540] 1528 个文件
      unarmed: 130
      axe: 131
      stick: 132
      spear: 133
      bow: 134
######
  - id: 1000135
    name: "爱伦"
    isRole: true
    description: "爱伦-粉"
    color: "pink"
    sprite: #[50541,52068] 1528 个文件
      unarmed: 135
      axe: 136
      stick: 137
      spear: 138
      bow: 139
############################################################
  - id: 1000140
    name: "玛蕾菲雅"
    isRole: true
    description: "玛蕾菲雅-绿"
    color: "green"
    sprite: #[52069,53596]  个文件
      unarmed: 140
      axe: 141
      stick: 142
      spear: 143
      bow: 144
######
  - id: 1000145
    name: "玛蕾菲雅"
    isRole: true
    description: "玛蕾菲雅-粉"
    color: "pink"
    sprite: #[53597,55124] 1528 个文件
      unarmed: 145
      axe: 146
      stick: 147
      spear: 148
      bow: 149
######
  - id: 1000150
    name: "玛蕾菲雅"
    isRole: true
    description: "玛蕾菲雅-黄"
    color: "yellow"
    sprite: #[55125,56652] 1528 个文件
      unarmed: 150
      axe: 151
      stick: 152
      spear: 153
      bow: 154
######
  - id: 1000155
    name: "玛蕾菲雅"
    isRole: true
    description: "玛蕾菲雅-蓝"
    color: "blue"
    sprite: #[56653,58180] 1528 个文件
      unarmed: 155
      axe: 156
      stick: 157
      spear: 158
      bow: 159
############################################################
  - id: 1000160
    name: "希希亚"
    isRole: true
    description: "希希亚-白"
    color: "white"
    sprite: #[58181,59708] 1528 个文件
      unarmed: 160
      axe: 161
      stick: 162
      spear: 163
      bow: 164
######
  - id: 1000165
    name: "希希亚"
    isRole: true
    description: "希希亚-蓝"
    color: "blue"
    sprite: #[59709,61236] 1528 个文件
      unarmed: 165
      axe: 166
      stick: 167
      spear: 168
      bow: 169
######
  - id: 1000170
    name: "希希亚"
    isRole: true
    description: "希希亚-绿"
    color: "green"
    sprite: #[61237,62764] 1528 个文件
      unarmed: 170
      axe: 171
      stick: 172
      spear: 173
      bow: 174
######
  - id: 1000175
    name: "希希亚"
    isRole: true
    description: "希希亚-棕"
    color: "brown"
    sprite: #[62765,64292] 1528 个文件
      unarmed: 175
      axe: 176
      stick: 177
      spear: 178
      bow: 179
############################################################
  - id: 1000180
    name: "菲莉雅"
    isRole: true
    description: "菲莉雅-棕"
    color: "brown"
    sprite: #[64293,65820] 1528 个文件
      unarmed: 180
      axe: 181
      stick: 182
      spear: 183
      bow: 184
######
  - id: 1000185
    name: "菲莉雅"
    isRole: true
    description: "菲莉雅-黄"
    color: "yellow"
    sprite: #[65821,67348] 1528 个文件
      unarmed: 185
      axe: 186
      stick: 187
      spear: 188
      bow: 189
######
  - id: 1000190
    name: "菲莉雅"
    isRole: true
    description: "菲莉雅-黑"
    color: "black"
    sprite: #[67349,68876] 1528 个文件
      unarmed: 190
      axe: 191
      stick: 192
      spear: 193
      bow: 194
######
  - id: 1000195
    name: "菲莉雅"
    isRole: true
    description: "菲莉雅-蓝"
    color: "green"
    sprite: #[68877,70404] 1528 个文件
      unarmed: 195
      axe: 196
      stick: 197
      spear: 198
      bow: 199
############################################################
  - id: 1000200
    name: "米亚"
    isRole: true
    description: "米亚-红"
    color: "red"
    sprite: #[70405,71932] 1528 个文件
      unarmed: 200
      axe: 201
      stick: 202
      spear: 203
      bow: 204
######
  - id: 1000205
    name: "米亚"
    isRole: true
    description: "米亚-橙"
    color: "yellow"
    sprite: #[71933,73460] 1528 个文件
      unarmed: 205
      axe: 206
      stick: 207
      spear: 208
      bow: 209
######
  - id: 1000210
    name: "米亚"
    isRole: true
    description: "米亚-蓝"
    color: "blue"
    sprite: #[73461,74988] 1528 个文件
      unarmed: 210
      axe: 211
      stick: 212
      spear: 213
      bow: 214
######
  - id: 1000215
    name: "米亚"
    isRole: true
    description: "米亚-白"
    color: "white"
    sprite: #[74989,76516] 1528 个文件
      unarmed: 215
      axe: 216
      stick: 217
      spear: 218
      bow: 219
############################################################
  - id: 1000220
    name: "露露"
    isRole: true
    description: "露露-黄"
    color: "yellow"
    sprite: #[76517,78069] 1552 个文件 (NOTE: 中间 77508 没用到, 实际用到文件数量为 1552)
      unarmed: 220
      axe: 221
      stick: 222
      spear: 223
      bow: 224
######
  - id: 1000225
    name: "露露"
    isRole: true
    description: "露露-绿"
    color: "green"
    sprite: #[78070,79621] 1552 个文件
      unarmed: 225
      axe: 226
      stick: 227
      spear: 228
      bow: 229
######
  - id: 1000230
    name: "露露"
    isRole: true
    description: "露露-红"
    color: "red"
    sprite: #[79622,81173] 1552 个文件
      unarmed: 230
      axe: 231
      stick: 232
      spear: 233
      bow: 234
######
  - id: 1000235
    name: "露露"
    isRole: true
    description: "露露-蓝"
    color: "blue"
    sprite: #[81174,82726] 1552 个文件 (NOTE: 中间 82211 没用到, 实际用到文件数量为 1552)
      unarmed: 235
      axe: 236
      stick: 237
      spear: 238
      bow: 239
############################################################
