# 宠物技能-配置
# 任何修改此文件的行为都需要通知客户端和服务端开发人员

# 宠物技能 [9000001,9999999]

skill:
  - id: 9000001
    name: 待机
    description: 什么也不做
    cost: 500
  - id: 9000002
    name: 攻击
    description: 通常攻击
    cost: 1000
  - id: 9000003
    name: 防御
    description: 通常防御
    cost: 1000
  - id: 9000004
    name: 破除防御
    description: 对采取防敌人攻击可能
    guardBreak: {}
    cost: 1500
  - id: 9000005
    name: 连续攻击
    description: 两次连续攻击
    continuationAttack:
      segmentCount: 2
    cost: 2000
  - id: 9000006
    name: 三段攻击
    description: 3次连续攻击
    continuationAttack:
      segmentCount: 3
    cost: 5000
  - id: 9000007
    name: 愤怒
    description: 防御率下降 攻击力和敏捷上升 给予敌人愤怒一击
    wildViolentAttack:
      attackPercentModifier: 200
      defensePercentModifier: -60
      targetDodgePercentBonus: 70
    cost: 1000
  - id: 9000008
    name: 不防守战法
    description: 本回合不主动攻击, 闪避率增加30%, 反击率增加50%; 会心率20%仅保留8.5原始配置, 当前源码不生效
    noGuard:
      dodgePercent: 30
      counterPercent: 50
      criticalPercent: 20
    cost: 3000
  - id: 9000009
    name: 不防守战法2
    description: 本回合不主动攻击, 闪避率增加40%, 反击率增加60%; 会心率30%仅保留8.5原始配置, 当前源码不生效
    noGuard:
      dodgePercent: 40
      counterPercent: 60
      criticalPercent: 30
    cost: 15000
  - id: 9000010
    name: 不防守战法3
    description: 本回合不主动攻击, 闪避率增加50%, 反击率增加70%; 会心率40%仅保留8.5原始配置, 当前源码不生效
    noGuard:
      dodgePercent: 50
      counterPercent: 70
      criticalPercent: 40
    cost: 25000
  - id: 9000011
    name: 破除防御之2
    description: 敌防御时攻+30% 敌非防御时攻-30%
    guardBreak2: {}
    cost: 1000
  - id: 9000012
    name: 狂乱暴走
    description: 乱数攻击对手3次 攻20% 防30% 下降
    attackCrazed:
      segmentCount: 3
    cost: 0
  - id: 9000013
    name: 栗子连激
    description: 乱数连续投掷栗子8~10颗
    attackShoot:
      minSegmentCount: 8
      maxSegmentCount: 10
    cost: 2000
  - id: 9000014
    name: 撕裂伤口1
    description: 撕裂旧伤口 增加20%伤害
    tearDamage:
      missingHpPercent: 20
    cost: 10000
  - id: 9000015
    name: 撕裂伤口2
    description: 撕裂旧伤口 增加50%伤害
    tearDamage:
      missingHpPercent: 50
    cost: 10000
  - id: 9000016
    name: 毒煞蔓延
    description: 让对手中毒 且有机会传染到周围的人
    sars: {}
    cost: 5000
  - id: 9000017
    name: 音波冲击
    description: 攻击宠物时 可贯穿伤害至人物身上 伤害值为1/2
    sonic:
      secondaryDamageDivisor: 2
    cost: 3000
  - id: 9000018
    name: 回旋攻击
    description: 攻击力下降20% 可攻击敌方一排
    gyrate:
      attackPercentModifier: -20
    cost: 3000
  - id: 9000019
    name: 威吓攻击
    description: 攻击力下降30% 敏捷下降30% 有60%的机率使对手麻痹一回合
    hector:
      attackPercentModifier: -30
      agilityPercentModifier: -30
    cost: 5000
  - id: 9000020
    name: 追迹攻击
    description: 对手在第一次攻击闪避的话 将会80%的机率发动第二次攻击
    retrace:
      retryThresholdExclusive: 80
      secondAttackPercentModifier: 20
    cost: 3000
  - id: 9000021
    name: 针刺外皮
    description: 可令攻击者受到1/2的伤害
    acupuncture:
      attackerDamageDivisor: 2
    cost: 5000
