# 宠物技能-配置
# 任何修改此文件的行为都需要通知客户端和服务端开发人员

# 宠物技能 [9000001,9999999]

skill:
  - id: 9000001
    name: 待机
    description: 什么也不做
    cost: 500
  - id: 9000002
    name: 攻击
    description: 通常攻击,other_without_myself
    cost: 1000
  - id: 9000003
    name: 防御
    description: 通常防御
    cost: 1000
  - id: 9000004
    name: 破除防御
    description: 对采取防敌人攻击可能,other_without_myself
    cost: 1500
  - id: 9000005
    name: 连续攻击
    description: 两次连续攻击,other_without_myself
    cost: 2000
  - id: 9000006
    name: 三段攻击
    description: 3次连续攻击,other_without_myself
    cost: 5000
