syntax = "proto3";

package user;
option go_package = "server/proto/pb;pb";

import "character.proto";

enum AccountRecordLimit {
  AccountRecordLimit_Unspecified = 0; // 未指定账号档案限制, proto3 enum 默认值
  AccountRecordLimit_MaxCharacterSlotCount = 5; // 每个账号最多可用角色槽位数量
}

message AccountRecord {
  uint64 uid = 1; // uid, 账号唯一标识
  string account = 3; // 登录账号, 去除首尾空格后保存, 大小写敏感
  int64 account_create_timestamp_ms = 4; // 账号创建时间戳, 单位毫秒
  int64 account_record_create_timestamp_ms = 5; // 账号档案初始化完成时间戳, 单位毫秒; 0 表示账号和 uid 已创建, 但角色和宠物等档案尚未初始化
  uint64 used_uuid = 6; // 当前账号内角色和宠物 UUID 递增游标
  map<uint64, uint64> asset_map = 10; // 账号资产表, key 为 asset_id, value 为数值
  repeated CharacterRecord character_record_list = 20; // 角色槽位列表, 数组下标为角色槽位; 空槽使用 uuid 为 0 的 CharacterRecord 占位, 完整角色 key 为 uid + 角色 UUID
}
