syntax = "proto3";

package account;
option go_package = "server/proto/pb;pb";

import "character.proto";
import "pet.proto";

enum AccountRecordLimit {
  AccountRecordLimit_Unspecified = 0; // 未指定账号档案限制, proto3 enum 默认值
  AccountRecordLimit_MaxCharacterSlotCount = 5; // 每个账号最多可用角色槽位数量
  AccountRecordLimit_MaxPetWarehouseCount = 100; // 每个账号宠物仓库最多可存放宠物数量
}

message AccountRecord {
  uint64 aid = 1; // aid, 账号唯一标识
  string account = 3; // 登录账号, 去除首尾空格后保存, 大小写敏感
  int64 create_timestamp_ms = 4; // 账号创建时间戳, 单位毫秒
  uint64 used_uuid = 6; // 当前账号内角色和宠物 UUID 递增游标
  map<uint64, uint64> asset_map = 10; // 账号资产表, key 为 asset_id, value 为数值
  repeated CharacterRecord character_record_list = 20; // 固定 5 个角色槽位, 建号时全部创建; 数组下标为角色槽位, 空槽使用 uuid 为 0 的 CharacterRecord 占位, 完整角色 key 为 aid + 角色 UUID
  map<uint64, PetRecord> pet_warehouse_record_map = 30; // 建号时创建的账号宠物仓库, 初始为空; key 为宠物 UUID, 同账号下所有角色可从仓库取出宠物携带, 也可将随身宠物放回仓库存放
}
