syntax = "proto3";

package account;
option go_package = "server/proto/pb;pb";

enum AssetType {
  AssetType_Record = 0;
  AssetType_Character = 1;
  AssetType_Scene = 2;
  AssetType_Item = 3;
  AssetType_Pet = 4;
  AssetType_NPC = 5;
  AssetType_Decoration = 6;
  AssetType_Building = 7;
  AssetType_Skill = 8;
}

enum AssetID {
  AssetID_Unspecified = 0;
  AssetID_Stone = 3490000;
  AssetID_Silver = 3490001;
  AssetID_Gold = 3490002;
}

enum AssetIDRange {
  option allow_alias = true;

  AssetIDRange_Unknow = 0;
  AssetIDRange_Record_Start = 1;
  AssetIDRange_Record_End = 999999;
  AssetIDRange_Character_Start = 1000000;
  AssetIDRange_Character_End = 1999999;

  AssetIDRange_Map_Start = 1; // 地图
    AssetIDRange_Map_Test_Start = 80000;
    AssetIDRange_Map_Test_End = 89999;
    AssetIDRange_Map_Training_Start = 90000;
    AssetIDRange_Map_Training_End = 99999;
  AssetIDRange_Map_End = 999999;

  AssetIDRange_Item_Start = 3000000; // 道具
  AssetIDRange_Item_Item_Start = 3000000;
  AssetIDRange_CharacterAsset_Start = 3490000;
  AssetIDRange_CharacterAsset_End = 3499999;
  AssetIDRange_Item_Item_End = 3499999;
  AssetIDRange_Item_Equipment_Start = 3500000;

    AssetIDRange_Item_Equipment_Weapon_Start = 3900000; // 武器
      // 爪
      AssetIDRange_Item_Equipment_Weapon_Claw_Start = 3900000;
      AssetIDRange_Item_Equipment_Weapon_Claw_End = 3909999;
      // 斧
      AssetIDRange_Item_Equipment_Weapon_Axe_Start = 3910000;
      AssetIDRange_Item_Equipment_Weapon_Axe_End = 3919999;
      // 棍
      AssetIDRange_Item_Equipment_Weapon_Staff_Start = 3920000;
      AssetIDRange_Item_Equipment_Weapon_Staff_End = 3929999;
      // 枪
      AssetIDRange_Item_Equipment_Weapon_Spear_Start = 3930000;
      AssetIDRange_Item_Equipment_Weapon_Spear_End = 3939999;
      // 弓
      AssetIDRange_Item_Equipment_Weapon_Bow_Start = 3940000;
      AssetIDRange_Item_Equipment_Weapon_Bow_End = 3949999;
      // 回旋镖
      AssetIDRange_Item_Equipment_Weapon_Boomerang_Start = 3950000;
      AssetIDRange_Item_Equipment_Weapon_Boomerang_End = 3959999;
      // 投掷斧
      AssetIDRange_Item_Equipment_Weapon_ThrowingAxe_Start = 3960000;
      AssetIDRange_Item_Equipment_Weapon_ThrowingAxe_End = 3969999;
      // 投掷石
      AssetIDRange_Item_Equipment_Weapon_ThrowingStone_Start = 3970000;
      AssetIDRange_Item_Equipment_Weapon_ThrowingStone_End = 3979999;

    AssetIDRange_Item_Equipment_Weapon_End = 3999999;


  AssetIDRange_Item_Equipment_End = 3999999;
  AssetIDRange_Item_End = 3999999;
  AssetIDRange_Pet_Start = 4000000;
  AssetIDRange_Pet_End = 4999999;
  AssetIDRange_NPC_Start = 5000000;
  AssetIDRange_NPC_End = 5999999;
  AssetIDRange_Decoration_Start = 6000000;
  AssetIDRange_Decoration_End = 6999999;
  AssetIDRange_Building_Start = 7000000;
  AssetIDRange_Building_End = 7999999;
  AssetIDRange_Skill_Start = 8000000;
  AssetIDRange_Skill_End = 9999999;
}

// [1, 999999] 账号档案资产 ID 范围
enum AssetIDRecord {
  AssetIDRecord_Unknow = 0;
  AssetIDRecord_Direction = 10;
  AssetIDRecord_Action = 11;
}

enum AssetElemental {
  AssetElemental_Unknow = 0;
  AssetElemental_Earth = 1;
  AssetElemental_Water = 2;
  AssetElemental_Fire = 3;
  AssetElemental_Wind = 4;
  AssetElemental_Max = 5;
}

enum AssetDirection {
  AssetDirection_Unknow = 0;
  AssetDirection_Up = 1;
  AssetDirection_UpRight = 2;
  AssetDirection_Right = 3;
  AssetDirection_DownRight = 4;
  AssetDirection_Down = 5;
  AssetDirection_DownLeft = 6;
  AssetDirection_Left = 7;
  AssetDirection_UpLeft = 8;
  AssetDirection_Max = 9;
}
