syntax = "proto3";

package account;
option go_package = "server/proto/pb;pb";

import "common.proto";

// 消息范围 [0x001019, 0x00101B]

message CharacterTeamJoinReq {
  CharacterKey target = 1; // 目标队长, 必须提供完整角色身份
}

message CharacterTeamJoinRes {}

message CharacterTeamLeaveReq {}

message CharacterTeamLeaveRes {}

message CharacterTeamDisbandReq {}

message CharacterTeamDisbandRes {}

message CharacterTeamKickReq {
  CharacterKey target = 1; // 被踢成员, 必须提供完整角色身份
}

message CharacterTeamKickRes {}

//0x001019#client->gateway#角色队伍操作-请求
message CharacterTeamOperationReq {
  uint64 character_uuid = 1; // 发起操作的当前账号角色 UUID

  oneof operation {
    CharacterTeamJoinReq join = 10;
    CharacterTeamLeaveReq leave = 11;
    CharacterTeamDisbandReq disband = 12;
    CharacterTeamKickReq kick = 13;
  }
}

//0x00101A#gateway->client#角色队伍操作-回复
message CharacterTeamOperationRes {
  uint64 character_uuid = 1; // 发起操作的角色 UUID

  oneof operation {
    CharacterTeamJoinRes join = 10;
    CharacterTeamLeaveRes leave = 11;
    CharacterTeamDisbandRes disband = 12;
    CharacterTeamKickRes kick = 13;
  }
}

//0x00101B#gateway->client#角色队伍变化-通知
message CharacterTeamChangedNotify {
  uint64 target_character_uuid = 1; // 本通知对应的本地角色 UUID
}
