syntax = "proto3";

package user;
option go_package = "server/proto/pb;pb";

import "record.proto";

enum PetAction {
  PetAction_Unknow = 0;
  PetAction_Attack = 1;
  PetAction_Faint = 2;
  PetAction_Hurt = 3;
  PetAction_Defense = 4;
  PetAction_Stand = 5;
  PetAction_Walk = 6;
  PetAction_AttackShort = 7;
  PetAction_Max = 8;
}

enum PetRarity {
  PetRarity_Unknow = 0;
  PetRarity_Common = 1;
  PetRarity_Rare = 2;
  PetRarity_Epic = 3;
  PetRarity_Legendary = 4;
  PetRarity_Mythic = 5;
  PetRarity_Max = 6;
}

enum PetGrade {
  PetGrade_Unknow = 0;
  PetGrade_Common = 1;
  PetGrade_Rare = 2;
  PetGrade_Epic = 3;
  PetGrade_Legendary = 4;
  PetGrade_Mythic = 5;
  PetGrade_Max = 6;
}

message PetRecord {
  uint64 uuid = 1;
  string nick = 2;
  map<uint32, uint64> asset_record_base_map = 10;
  map<uint64, RecordPrimary> record_map = 1000;
}
