syntax = "proto3";

package user;
option go_package = "server/proto/pb;pb";

message UserRecord {
  uint64 uid = 1; // 用户唯一 ID
  string name = 2; // 用户昵称
  string account = 3; // 登录账号，去除首尾空格后保存，大小写敏感
  int64 account_create_time_ms = 4; // 账号创建时间戳，单位毫秒
  int64 user_create_time_ms = 5; // 用户创建时间戳，单位毫秒；0 表示账号已创建但用户未创建
  map<uint64, uint64> asset_map = 10; // 资产表 key: AssetID value: 数值
  map<uint64, RecordPrimary> record_map = 1000; // 用户扩展记录表, key 为 primary_id
}

// 用户扩展记录一级分组
message RecordPrimary{
  uint64 primary_id = 1; // 一级分组 ID
  map<uint64, RecordSecondary> secondary_record_map= 2; // 二级记录表, key 为 secondary_id
}

// 用户扩展记录二级记录
message RecordSecondary{
  uint64 secondary_id = 1; // 二级记录 ID
  int64 timestamp = 2; // 记录时间戳
  repeated uint64 data = 3; // 数值数据, 具体含义由 primary_id/secondary_id 对应的业务定义
  repeated string str_data = 4; // 字符串数据, 具体含义由 primary_id/secondary_id 对应的业务定义
}
