// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: account.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 0x000001#client->gateway#账号登录验证-请求
type AccountVerifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Aid           uint64 `protobuf:"varint,1,opt,name=aid,proto3" json:"aid,omitempty"`                                         // aid, 账号唯一标识, 由 login 服务下发, 客户端登录 Gateway 时携带
	ConnectTicket string `protobuf:"bytes,2,opt,name=connect_ticket,json=connectTicket,proto3" json:"connect_ticket,omitempty"` // connectTicket, login 签发的短期连接票据, 客户端登录 Gateway 时携带
}

func (x *AccountVerifyReq) Reset() {
	*x = AccountVerifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountVerifyReq) ProtoMessage() {}

func (x *AccountVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountVerifyReq.ProtoReflect.Descriptor instead.
func (*AccountVerifyReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *AccountVerifyReq) GetAid() uint64 {
	if x != nil {
		return x.Aid
	}
	return 0
}

func (x *AccountVerifyReq) GetConnectTicket() string {
	if x != nil {
		return x.ConnectTicket
	}
	return ""
}

// 0x000002#gateway->client#账号登录验证-回复
type AccountVerifyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTimestampMs int64  `protobuf:"varint,1,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"` // 服务器当前时间戳，单位毫秒（用于客户端对时）
	HeartbeatSession  string `protobuf:"bytes,2,opt,name=heartbeat_session,json=heartbeatSession,proto3" json:"heartbeat_session,omitempty"`       // heartbeatSession, 客户端后续心跳携带的心跳认证凭证
}

func (x *AccountVerifyRes) Reset() {
	*x = AccountVerifyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountVerifyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountVerifyRes) ProtoMessage() {}

func (x *AccountVerifyRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountVerifyRes.ProtoReflect.Descriptor instead.
func (*AccountVerifyRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountVerifyRes) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

func (x *AccountVerifyRes) GetHeartbeatSession() string {
	if x != nil {
		return x.HeartbeatSession
	}
	return ""
}

// 0x000003#client->gateway#账号主动下线-请求
type AccountOfflineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason uint32 `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"` // 1=账号主动离线
}

func (x *AccountOfflineReq) Reset() {
	*x = AccountOfflineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountOfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountOfflineReq) ProtoMessage() {}

func (x *AccountOfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountOfflineReq.ProtoReflect.Descriptor instead.
func (*AccountOfflineReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountOfflineReq) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

// 0x00000A#client->gateway#心跳-请求
type AccountHeartbeatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastHeartbeatSession string `protobuf:"bytes,1,opt,name=last_heartbeat_session,json=lastHeartbeatSession,proto3" json:"last_heartbeat_session,omitempty"` // 上次 Gateway 下发的 heartbeatSession
}

func (x *AccountHeartbeatReq) Reset() {
	*x = AccountHeartbeatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountHeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountHeartbeatReq) ProtoMessage() {}

func (x *AccountHeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountHeartbeatReq.ProtoReflect.Descriptor instead.
func (*AccountHeartbeatReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *AccountHeartbeatReq) GetLastHeartbeatSession() string {
	if x != nil {
		return x.LastHeartbeatSession
	}
	return ""
}

// 0x00000B#gateway->client#心跳-回复
type AccountHeartbeatRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTimestampMs    int64  `protobuf:"varint,1,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"`         // 服务器时间毫秒
	NextHeartbeatSession string `protobuf:"bytes,2,opt,name=next_heartbeat_session,json=nextHeartbeatSession,proto3" json:"next_heartbeat_session,omitempty"` // 客户端下次心跳必须使用的 heartbeatSession
}

func (x *AccountHeartbeatRes) Reset() {
	*x = AccountHeartbeatRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountHeartbeatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountHeartbeatRes) ProtoMessage() {}

func (x *AccountHeartbeatRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountHeartbeatRes.ProtoReflect.Descriptor instead.
func (*AccountHeartbeatRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *AccountHeartbeatRes) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

func (x *AccountHeartbeatRes) GetNextHeartbeatSession() string {
	if x != nil {
		return x.NextHeartbeatSession
	}
	return ""
}

// 0x00000C#client->gateway#请求账号档案-请求
type AccountRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccountRecordReq) Reset() {
	*x = AccountRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRecordReq) ProtoMessage() {}

func (x *AccountRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRecordReq.ProtoReflect.Descriptor instead.
func (*AccountRecordReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

// 0x00000D#gateway->client#请求账号档案-回复
type AccountRecordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountRecord *AccountRecord `protobuf:"bytes,1,opt,name=account_record,json=accountRecord,proto3" json:"account_record,omitempty"` // 账号档案
}

func (x *AccountRecordRes) Reset() {
	*x = AccountRecordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRecordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRecordRes) ProtoMessage() {}

func (x *AccountRecordRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRecordRes.ProtoReflect.Descriptor instead.
func (*AccountRecordRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *AccountRecordRes) GetAccountRecord() *AccountRecord {
	if x != nil {
		return x.AccountRecord
	}
	return nil
}

// 0x00000E#client->gateway#创建角色-请求
type CharacterCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterSlotIndex uint32                    `protobuf:"varint,1,opt,name=character_slot_index,json=characterSlotIndex,proto3" json:"character_slot_index,omitempty"` // 角色创建槽位索引, 从 0 开始; 该槽位已有有效角色时创建失败
	CharacterId        uint32                    `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`                        // 角色资源 ID; 0 表示使用默认角色资源, 非 0 时必须是可创建玩家角色
	CharacterNick      string                    `protobuf:"bytes,3,opt,name=character_nick,json=characterNick,proto3" json:"character_nick,omitempty"`                   // 角色昵称; 去除首尾空白后 1-12 个字符, 空字符串表示使用默认昵称
	CharacterElemental *ElementalPoints          `protobuf:"bytes,4,opt,name=character_elemental,json=characterElemental,proto3" json:"character_elemental,omitempty"`    // 角色地水火风元素点数; 必须提交且由 online 校验合法性
	CharacterAttribute *CharacterAttributePoints `protobuf:"bytes,5,opt,name=character_attribute,json=characterAttribute,proto3" json:"character_attribute,omitempty"`    // 角色体力腕力耐力速度点数; 必须提交且由 online 校验合法性
}

func (x *CharacterCreateReq) Reset() {
	*x = CharacterCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterCreateReq) ProtoMessage() {}

func (x *CharacterCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterCreateReq.ProtoReflect.Descriptor instead.
func (*CharacterCreateReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7}
}

func (x *CharacterCreateReq) GetCharacterSlotIndex() uint32 {
	if x != nil {
		return x.CharacterSlotIndex
	}
	return 0
}

func (x *CharacterCreateReq) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterCreateReq) GetCharacterNick() string {
	if x != nil {
		return x.CharacterNick
	}
	return ""
}

func (x *CharacterCreateReq) GetCharacterElemental() *ElementalPoints {
	if x != nil {
		return x.CharacterElemental
	}
	return nil
}

func (x *CharacterCreateReq) GetCharacterAttribute() *CharacterAttributePoints {
	if x != nil {
		return x.CharacterAttribute
	}
	return nil
}

// 0x00000F#gateway->client#创建角色-回复
type CharacterCreateRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountRecord *AccountRecord `protobuf:"bytes,1,opt,name=account_record,json=accountRecord,proto3" json:"account_record,omitempty"` // 创建角色后的账号档案
}

func (x *CharacterCreateRes) Reset() {
	*x = CharacterCreateRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterCreateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterCreateRes) ProtoMessage() {}

func (x *CharacterCreateRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterCreateRes.ProtoReflect.Descriptor instead.
func (*CharacterCreateRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8}
}

func (x *CharacterCreateRes) GetAccountRecord() *AccountRecord {
	if x != nil {
		return x.AccountRecord
	}
	return nil
}

// 0x000010#client->gateway#机器人压测-请求
type RobotPingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq               uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                                                        // 客户端递增序号
	ClientTimestampMs int64  `protobuf:"varint,2,opt,name=client_timestamp_ms,json=clientTimestampMs,proto3" json:"client_timestamp_ms,omitempty"` // 客户端发送时间戳，单位毫秒
	Payload           string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                                 // 压测透传数据
}

func (x *RobotPingReq) Reset() {
	*x = RobotPingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RobotPingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotPingReq) ProtoMessage() {}

func (x *RobotPingReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotPingReq.ProtoReflect.Descriptor instead.
func (*RobotPingReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{9}
}

func (x *RobotPingReq) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RobotPingReq) GetClientTimestampMs() int64 {
	if x != nil {
		return x.ClientTimestampMs
	}
	return 0
}

func (x *RobotPingReq) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// 0x000011#gateway->client#机器人压测-回复
type RobotPingRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq               uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                                                        // 对应请求中的客户端递增序号
	ClientTimestampMs int64  `protobuf:"varint,2,opt,name=client_timestamp_ms,json=clientTimestampMs,proto3" json:"client_timestamp_ms,omitempty"` // 对应请求中的客户端发送时间戳，单位毫秒
	ServerTimestampMs int64  `protobuf:"varint,3,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"` // 服务端回复时间戳，单位毫秒
	Payload           string `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                                 // 对应请求中的压测透传数据
}

func (x *RobotPingRes) Reset() {
	*x = RobotPingRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RobotPingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotPingRes) ProtoMessage() {}

func (x *RobotPingRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotPingRes.ProtoReflect.Descriptor instead.
func (*RobotPingRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{10}
}

func (x *RobotPingRes) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RobotPingRes) GetClientTimestampMs() int64 {
	if x != nil {
		return x.ClientTimestampMs
	}
	return 0
}

func (x *RobotPingRes) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

func (x *RobotPingRes) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// 0x000012#client->gateway#设置自动遇敌-请求
type AutoEncounterSetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled       bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                  // 是否开启自动遇敌
	CharacterUuid uint64 `protobuf:"varint,2,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 目标角色 UUID, 必须属于当前账号且处于在线状态
}

func (x *AutoEncounterSetReq) Reset() {
	*x = AutoEncounterSetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoEncounterSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoEncounterSetReq) ProtoMessage() {}

func (x *AutoEncounterSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoEncounterSetReq.ProtoReflect.Descriptor instead.
func (*AutoEncounterSetReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{11}
}

func (x *AutoEncounterSetReq) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AutoEncounterSetReq) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

// 0x000013#gateway->client#设置自动遇敌-回复
type AutoEncounterSetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled           bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`                                                // 服务端确认后的自动遇敌状态
	ServerTimestampMs int64  `protobuf:"varint,2,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"` // 服务端回复时间戳, 单位毫秒
	CharacterUuid     uint64 `protobuf:"varint,3,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"`               // 已更新自动遇敌状态的角色 UUID
}

func (x *AutoEncounterSetRes) Reset() {
	*x = AutoEncounterSetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoEncounterSetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoEncounterSetRes) ProtoMessage() {}

func (x *AutoEncounterSetRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoEncounterSetRes.ProtoReflect.Descriptor instead.
func (*AutoEncounterSetRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{12}
}

func (x *AutoEncounterSetRes) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AutoEncounterSetRes) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

func (x *AutoEncounterSetRes) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

// 0x000014#gateway->client#战斗开始-通知
type CombatBattleStartNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleStart   *CombatBattleStart `protobuf:"bytes,1,opt,name=battle_start,json=battleStart,proto3" json:"battle_start,omitempty"`        // 开战快照, 只包含战斗 ID 和初始可见单位
	CharacterUuid uint64             `protobuf:"varint,2,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 本场战斗所属的玩家角色 UUID
}

func (x *CombatBattleStartNotify) Reset() {
	*x = CombatBattleStartNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatBattleStartNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatBattleStartNotify) ProtoMessage() {}

func (x *CombatBattleStartNotify) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatBattleStartNotify.ProtoReflect.Descriptor instead.
func (*CombatBattleStartNotify) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{13}
}

func (x *CombatBattleStartNotify) GetBattleStart() *CombatBattleStart {
	if x != nil {
		return x.BattleStart
	}
	return nil
}

func (x *CombatBattleStartNotify) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

// 0x000015#client->gateway#战斗回合出手-请求
type CombatRoundActionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId      string           `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`                                      // 战斗唯一 UUID 字符串
	Round         uint32           `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`                                                           // 客户端提交的回合号
	UnitKey       *CombatUnitKey   `protobuf:"bytes,3,opt,name=unit_key,json=unitKey,proto3" json:"unit_key,omitempty"`                                         // 本次提交动作的出手单位
	ActionType    CombatActionType `protobuf:"varint,4,opt,name=action_type,json=actionType,proto3,enum=account.CombatActionType" json:"action_type,omitempty"` // 出手类型
	ActionId      uint32           `protobuf:"varint,5,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`                                     // 角色动作为 CharacterAction 枚举值, 宠物技能为宠物技能 ID
	TargetKey     *CombatUnitKey   `protobuf:"bytes,6,opt,name=target_key,json=targetKey,proto3" json:"target_key,omitempty"`                                   // 动作主目标; 防御和待机可为空
	CharacterUuid uint64           `protobuf:"varint,7,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"`                      // 本次动作所属的玩家角色 UUID
}

func (x *CombatRoundActionReq) Reset() {
	*x = CombatRoundActionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatRoundActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRoundActionReq) ProtoMessage() {}

func (x *CombatRoundActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRoundActionReq.ProtoReflect.Descriptor instead.
func (*CombatRoundActionReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{14}
}

func (x *CombatRoundActionReq) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *CombatRoundActionReq) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CombatRoundActionReq) GetUnitKey() *CombatUnitKey {
	if x != nil {
		return x.UnitKey
	}
	return nil
}

func (x *CombatRoundActionReq) GetActionType() CombatActionType {
	if x != nil {
		return x.ActionType
	}
	return CombatActionType_CombatActionType_Unknown
}

func (x *CombatRoundActionReq) GetActionId() uint32 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *CombatRoundActionReq) GetTargetKey() *CombatUnitKey {
	if x != nil {
		return x.TargetKey
	}
	return nil
}

func (x *CombatRoundActionReq) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

// 0x000016#gateway->client#战斗回合出手-回复
type CombatRoundActionRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId      string         `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`                 // 战斗唯一 UUID 字符串
	Round         uint32         `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`                                      // 已接收的回合号
	UnitKey       *CombatUnitKey `protobuf:"bytes,3,opt,name=unit_key,json=unitKey,proto3" json:"unit_key,omitempty"`                    // 已接收动作的出手单位
	CharacterUuid uint64         `protobuf:"varint,4,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 本次动作所属的玩家角色 UUID
}

func (x *CombatRoundActionRes) Reset() {
	*x = CombatRoundActionRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatRoundActionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRoundActionRes) ProtoMessage() {}

func (x *CombatRoundActionRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRoundActionRes.ProtoReflect.Descriptor instead.
func (*CombatRoundActionRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{15}
}

func (x *CombatRoundActionRes) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *CombatRoundActionRes) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CombatRoundActionRes) GetUnitKey() *CombatUnitKey {
	if x != nil {
		return x.UnitKey
	}
	return nil
}

func (x *CombatRoundActionRes) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

// 0x000017#gateway->client#战斗回合结果-通知
type CombatRoundResultNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId       string                  `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`                    // 战斗唯一 UUID 字符串
	Round          uint32                  `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`                                         // 已结算的回合号
	IntentList     []*CombatActionIntent   `protobuf:"bytes,3,rep,name=intent_list,json=intentList,proto3" json:"intent_list,omitempty"`              // 本回合双方进入执行队列的出手意图列表
	CharacterUuid  uint64                  `protobuf:"varint,4,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"`    // 本场战斗所属的玩家角色 UUID
	BattleFinished bool                    `protobuf:"varint,6,opt,name=battle_finished,json=battleFinished,proto3" json:"battle_finished,omitempty"` // 本回合结算后战斗是否已经结束
	EventList      []*CombatEvent          `protobuf:"bytes,10,rep,name=event_list,json=eventList,proto3" json:"event_list,omitempty"`                // 本回合事件链, 用于表达攻击, 反击, 合击和状态变化
	Settlement     *CombatBattleSettlement `protobuf:"bytes,20,opt,name=settlement,proto3" json:"settlement,omitempty"`                               // battle_finished=true 时携带战斗结算数据
}

func (x *CombatRoundResultNotify) Reset() {
	*x = CombatRoundResultNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatRoundResultNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRoundResultNotify) ProtoMessage() {}

func (x *CombatRoundResultNotify) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRoundResultNotify.ProtoReflect.Descriptor instead.
func (*CombatRoundResultNotify) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{16}
}

func (x *CombatRoundResultNotify) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *CombatRoundResultNotify) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CombatRoundResultNotify) GetIntentList() []*CombatActionIntent {
	if x != nil {
		return x.IntentList
	}
	return nil
}

func (x *CombatRoundResultNotify) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CombatRoundResultNotify) GetBattleFinished() bool {
	if x != nil {
		return x.BattleFinished
	}
	return false
}

func (x *CombatRoundResultNotify) GetEventList() []*CombatEvent {
	if x != nil {
		return x.EventList
	}
	return nil
}

func (x *CombatRoundResultNotify) GetSettlement() *CombatBattleSettlement {
	if x != nil {
		return x.Settlement
	}
	return nil
}

// 0x000018#gateway->client#战斗回合准备-通知
type CombatRoundPrepareNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId                 string                `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`                                                      // 战斗唯一 UUID 字符串
	Round                    uint32                `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`                                                                           // 当前回合号, 从 1 开始
	ServerTimestampMs        int64                 `protobuf:"varint,3,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"`                        // 服务端当前时间戳, 单位毫秒
	RoundDeadlineTimestampMs int64                 `protobuf:"varint,4,opt,name=round_deadline_timestamp_ms,json=roundDeadlineTimestampMs,proto3" json:"round_deadline_timestamp_ms,omitempty"` // 当前回合截止时间戳, 单位毫秒
	CharacterUuid            uint64                `protobuf:"varint,5,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"`                                      // 本场战斗所属的玩家角色 UUID
	UnitStateList            []*CombatUnitState    `protobuf:"bytes,10,rep,name=unit_state_list,json=unitStateList,proto3" json:"unit_state_list,omitempty"`                                    // 当前全场运行期状态快照
	ActionOptionList         []*CombatActionOption `protobuf:"bytes,20,rep,name=action_option_list,json=actionOptionList,proto3" json:"action_option_list,omitempty"`                           // 当前客户端可提交的合法动作选项
	RequiredUnitKeyList      []*CombatUnitKey      `protobuf:"bytes,30,rep,name=required_unit_key_list,json=requiredUnitKeyList,proto3" json:"required_unit_key_list,omitempty"`                // 当前回合必须由客户端提交动作的单位
	ReadyUnitKeyList         []*CombatUnitKey      `protobuf:"bytes,31,rep,name=ready_unit_key_list,json=readyUnitKeyList,proto3" json:"ready_unit_key_list,omitempty"`                         // 当前回合已提交动作的单位
}

func (x *CombatRoundPrepareNotify) Reset() {
	*x = CombatRoundPrepareNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatRoundPrepareNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRoundPrepareNotify) ProtoMessage() {}

func (x *CombatRoundPrepareNotify) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRoundPrepareNotify.ProtoReflect.Descriptor instead.
func (*CombatRoundPrepareNotify) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{17}
}

func (x *CombatRoundPrepareNotify) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *CombatRoundPrepareNotify) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CombatRoundPrepareNotify) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

func (x *CombatRoundPrepareNotify) GetRoundDeadlineTimestampMs() int64 {
	if x != nil {
		return x.RoundDeadlineTimestampMs
	}
	return 0
}

func (x *CombatRoundPrepareNotify) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CombatRoundPrepareNotify) GetUnitStateList() []*CombatUnitState {
	if x != nil {
		return x.UnitStateList
	}
	return nil
}

func (x *CombatRoundPrepareNotify) GetActionOptionList() []*CombatActionOption {
	if x != nil {
		return x.ActionOptionList
	}
	return nil
}

func (x *CombatRoundPrepareNotify) GetRequiredUnitKeyList() []*CombatUnitKey {
	if x != nil {
		return x.RequiredUnitKeyList
	}
	return nil
}

func (x *CombatRoundPrepareNotify) GetReadyUnitKeyList() []*CombatUnitKey {
	if x != nil {
		return x.ReadyUnitKeyList
	}
	return nil
}

// 0x000019#gateway->client#战斗回合出手就绪-通知
type CombatRoundReadyNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId            string           `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`                                       // 战斗唯一 UUID 字符串
	Round               uint32           `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`                                                            // 当前回合号
	CharacterUuid       uint64           `protobuf:"varint,3,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"`                       // 本场战斗所属的玩家角色 UUID
	RequiredUnitKeyList []*CombatUnitKey `protobuf:"bytes,10,rep,name=required_unit_key_list,json=requiredUnitKeyList,proto3" json:"required_unit_key_list,omitempty"` // 当前回合必须由客户端提交动作的单位
	ReadyUnitKeyList    []*CombatUnitKey `protobuf:"bytes,11,rep,name=ready_unit_key_list,json=readyUnitKeyList,proto3" json:"ready_unit_key_list,omitempty"`          // 当前回合已提交动作的单位
}

func (x *CombatRoundReadyNotify) Reset() {
	*x = CombatRoundReadyNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatRoundReadyNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatRoundReadyNotify) ProtoMessage() {}

func (x *CombatRoundReadyNotify) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatRoundReadyNotify.ProtoReflect.Descriptor instead.
func (*CombatRoundReadyNotify) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{18}
}

func (x *CombatRoundReadyNotify) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *CombatRoundReadyNotify) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CombatRoundReadyNotify) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CombatRoundReadyNotify) GetRequiredUnitKeyList() []*CombatUnitKey {
	if x != nil {
		return x.RequiredUnitKeyList
	}
	return nil
}

func (x *CombatRoundReadyNotify) GetReadyUnitKeyList() []*CombatUnitKey {
	if x != nil {
		return x.ReadyUnitKeyList
	}
	return nil
}

// 0x00001A#client->gateway#角色上线-请求
type CharacterOnlineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 角色 UUID, 必须属于当前账号且尚未上线
}

func (x *CharacterOnlineReq) Reset() {
	*x = CharacterOnlineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterOnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterOnlineReq) ProtoMessage() {}

func (x *CharacterOnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterOnlineReq.ProtoReflect.Descriptor instead.
func (*CharacterOnlineReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{19}
}

func (x *CharacterOnlineReq) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

// 0x00001B#gateway->client#角色上线-回复
type CharacterOnlineRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CharacterOnlineRes) Reset() {
	*x = CharacterOnlineRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterOnlineRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterOnlineRes) ProtoMessage() {}

func (x *CharacterOnlineRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterOnlineRes.ProtoReflect.Descriptor instead.
func (*CharacterOnlineRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{20}
}

// 0x00001C#client->gateway#角色下线-请求
type CharacterOfflineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 角色 UUID, 必须属于当前账号且当前已上线
}

func (x *CharacterOfflineReq) Reset() {
	*x = CharacterOfflineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterOfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterOfflineReq) ProtoMessage() {}

func (x *CharacterOfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterOfflineReq.ProtoReflect.Descriptor instead.
func (*CharacterOfflineReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{21}
}

func (x *CharacterOfflineReq) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

// 0x00001D#gateway->client#角色下线-回复
type CharacterOfflineRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CharacterOfflineRes) Reset() {
	*x = CharacterOfflineRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterOfflineRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterOfflineRes) ProtoMessage() {}

func (x *CharacterOfflineRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterOfflineRes.ProtoReflect.Descriptor instead.
func (*CharacterOfflineRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{22}
}

// 0x00001E#client->gateway#进入场景-请求
type SceneEnterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 角色 UUID, 必须属于当前账号且当前已上线
	SceneId       uint32 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`                   // 目标场景 ID, 必须存在于 scene.yaml
}

func (x *SceneEnterReq) Reset() {
	*x = SceneEnterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneEnterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneEnterReq) ProtoMessage() {}

func (x *SceneEnterReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneEnterReq.ProtoReflect.Descriptor instead.
func (*SceneEnterReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{23}
}

func (x *SceneEnterReq) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *SceneEnterReq) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// 0x00001F#gateway->client#进入场景-回复
type SceneEnterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid     uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"`               // 已进入场景的角色 UUID
	SceneId           uint32 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`                                 // 已进入的场景 ID
	ServerTimestampMs int64  `protobuf:"varint,3,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"` // 服务端回复时间戳, 单位毫秒
}

func (x *SceneEnterRes) Reset() {
	*x = SceneEnterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneEnterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneEnterRes) ProtoMessage() {}

func (x *SceneEnterRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneEnterRes.ProtoReflect.Descriptor instead.
func (*SceneEnterRes) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{24}
}

func (x *SceneEnterRes) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *SceneEnterRes) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SceneEnterRes) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

var File_account_proto protoreflect.FileDescriptor

var file_account_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x14, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0c, 0x63, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a,
	0x10, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x61, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x6f, 0x0a, 0x10, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x12, 0x2e,
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x2b,
	0x0a, 0x11, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x5f, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x68, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2b, 0x0a, 0x11, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x4b, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x34, 0x0a, 0x16, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x14, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x7b, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x13,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x34, 0x0a, 0x16,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x5f, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x6e, 0x65,
	0x78, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x22, 0x51, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0xaf, 0x02, 0x0a, 0x12, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x30, 0x0a, 0x14, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x6c,
	0x6f, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x5f, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4e, 0x69, 0x63, 0x6b, 0x12, 0x49, 0x0a, 0x13,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x52, 0x12, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x12, 0x52, 0x0a, 0x13, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x12, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x22, 0x53, 0x0a, 0x12, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x3d, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x22, 0x6a, 0x0a, 0x0c, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73,
	0x65, 0x71, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x4d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x9a, 0x01, 0x0a,
	0x0c, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12,
	0x2e, 0x0a, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12,
	0x2e, 0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x56, 0x0a, 0x13, 0x41, 0x75, 0x74,
	0x6f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x22, 0x86, 0x01, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x6f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x4d, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x7f, 0x0a, 0x17, 0x43, 0x6f,
	0x6d, 0x62, 0x61, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x3d, 0x0a, 0x0c, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0xb3, 0x02, 0x0a, 0x14,
	0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x74, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x4b, 0x65,
	0x79, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x3a, 0x0a, 0x0b, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79, 0x52,
	0x09, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x22, 0xa3, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x31, 0x0a,
	0x08, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74,
	0x55, 0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0xd0, 0x02, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x62,
	0x61, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x3c, 0x0a, 0x0b, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3f, 0x0a, 0x0a, 0x73, 0x65, 0x74,
	0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a,
	0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x84, 0x04, 0x0a, 0x18, 0x43,
	0x6f, 0x6d, 0x62, 0x61, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x3d, 0x0a, 0x1b, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x5f, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x18, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x40, 0x0a, 0x0f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x0d, 0x75, 0x6e, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x49, 0x0a, 0x12, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x4b, 0x0a,
	0x16, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x6b,
	0x65, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x1e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e,
	0x69, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x13, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x55,
	0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x13, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x1f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79, 0x52,
	0x10, 0x72, 0x65, 0x61, 0x64, 0x79, 0x55, 0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x86, 0x02, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x52, 0x65, 0x61, 0x64, 0x79, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x4b, 0x0a, 0x16, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x64, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x13,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x13, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x75, 0x6e, 0x69,
	0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61,
	0x74, 0x55, 0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x10, 0x72, 0x65, 0x61, 0x64, 0x79, 0x55,
	0x6e, 0x69, 0x74, 0x4b, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x12, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x22, 0x3c, 0x0a,
	0x13, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x22, 0x51, 0x0a, 0x0d, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x63,
	0x65, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x42, 0x14, 0x5a, 0x12, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData = file_account_proto_rawDesc
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_proto_rawDescData)
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_account_proto_goTypes = []any{
	(*AccountVerifyReq)(nil),         // 0: account.AccountVerifyReq
	(*AccountVerifyRes)(nil),         // 1: account.AccountVerifyRes
	(*AccountOfflineReq)(nil),        // 2: account.AccountOfflineReq
	(*AccountHeartbeatReq)(nil),      // 3: account.AccountHeartbeatReq
	(*AccountHeartbeatRes)(nil),      // 4: account.AccountHeartbeatRes
	(*AccountRecordReq)(nil),         // 5: account.AccountRecordReq
	(*AccountRecordRes)(nil),         // 6: account.AccountRecordRes
	(*CharacterCreateReq)(nil),       // 7: account.CharacterCreateReq
	(*CharacterCreateRes)(nil),       // 8: account.CharacterCreateRes
	(*RobotPingReq)(nil),             // 9: account.RobotPingReq
	(*RobotPingRes)(nil),             // 10: account.RobotPingRes
	(*AutoEncounterSetReq)(nil),      // 11: account.AutoEncounterSetReq
	(*AutoEncounterSetRes)(nil),      // 12: account.AutoEncounterSetRes
	(*CombatBattleStartNotify)(nil),  // 13: account.CombatBattleStartNotify
	(*CombatRoundActionReq)(nil),     // 14: account.CombatRoundActionReq
	(*CombatRoundActionRes)(nil),     // 15: account.CombatRoundActionRes
	(*CombatRoundResultNotify)(nil),  // 16: account.CombatRoundResultNotify
	(*CombatRoundPrepareNotify)(nil), // 17: account.CombatRoundPrepareNotify
	(*CombatRoundReadyNotify)(nil),   // 18: account.CombatRoundReadyNotify
	(*CharacterOnlineReq)(nil),       // 19: account.CharacterOnlineReq
	(*CharacterOnlineRes)(nil),       // 20: account.CharacterOnlineRes
	(*CharacterOfflineReq)(nil),      // 21: account.CharacterOfflineReq
	(*CharacterOfflineRes)(nil),      // 22: account.CharacterOfflineRes
	(*SceneEnterReq)(nil),            // 23: account.SceneEnterReq
	(*SceneEnterRes)(nil),            // 24: account.SceneEnterRes
	(*AccountRecord)(nil),            // 25: account.AccountRecord
	(*ElementalPoints)(nil),          // 26: account.ElementalPoints
	(*CharacterAttributePoints)(nil), // 27: account.CharacterAttributePoints
	(*CombatBattleStart)(nil),        // 28: account.CombatBattleStart
	(*CombatUnitKey)(nil),            // 29: account.CombatUnitKey
	(CombatActionType)(0),            // 30: account.CombatActionType
	(*CombatActionIntent)(nil),       // 31: account.CombatActionIntent
	(*CombatEvent)(nil),              // 32: account.CombatEvent
	(*CombatBattleSettlement)(nil),   // 33: account.CombatBattleSettlement
	(*CombatUnitState)(nil),          // 34: account.CombatUnitState
	(*CombatActionOption)(nil),       // 35: account.CombatActionOption
}
var file_account_proto_depIdxs = []int32{
	25, // 0: account.AccountRecordRes.account_record:type_name -> account.AccountRecord
	26, // 1: account.CharacterCreateReq.character_elemental:type_name -> account.ElementalPoints
	27, // 2: account.CharacterCreateReq.character_attribute:type_name -> account.CharacterAttributePoints
	25, // 3: account.CharacterCreateRes.account_record:type_name -> account.AccountRecord
	28, // 4: account.CombatBattleStartNotify.battle_start:type_name -> account.CombatBattleStart
	29, // 5: account.CombatRoundActionReq.unit_key:type_name -> account.CombatUnitKey
	30, // 6: account.CombatRoundActionReq.action_type:type_name -> account.CombatActionType
	29, // 7: account.CombatRoundActionReq.target_key:type_name -> account.CombatUnitKey
	29, // 8: account.CombatRoundActionRes.unit_key:type_name -> account.CombatUnitKey
	31, // 9: account.CombatRoundResultNotify.intent_list:type_name -> account.CombatActionIntent
	32, // 10: account.CombatRoundResultNotify.event_list:type_name -> account.CombatEvent
	33, // 11: account.CombatRoundResultNotify.settlement:type_name -> account.CombatBattleSettlement
	34, // 12: account.CombatRoundPrepareNotify.unit_state_list:type_name -> account.CombatUnitState
	35, // 13: account.CombatRoundPrepareNotify.action_option_list:type_name -> account.CombatActionOption
	29, // 14: account.CombatRoundPrepareNotify.required_unit_key_list:type_name -> account.CombatUnitKey
	29, // 15: account.CombatRoundPrepareNotify.ready_unit_key_list:type_name -> account.CombatUnitKey
	29, // 16: account.CombatRoundReadyNotify.required_unit_key_list:type_name -> account.CombatUnitKey
	29, // 17: account.CombatRoundReadyNotify.ready_unit_key_list:type_name -> account.CombatUnitKey
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	file_account_record_proto_init()
	file_character_proto_init()
	file_combat_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_account_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AccountVerifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AccountVerifyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AccountOfflineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*AccountHeartbeatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AccountHeartbeatRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AccountRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*AccountRecordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterCreateRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RobotPingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RobotPingRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*AutoEncounterSetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AutoEncounterSetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CombatBattleStartNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*CombatRoundActionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*CombatRoundActionRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*CombatRoundResultNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*CombatRoundPrepareNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*CombatRoundReadyNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterOnlineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterOnlineRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterOfflineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterOfflineRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*SceneEnterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*SceneEnterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_rawDesc = nil
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
