// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: cache.grpc.proto

package pb

import (
	_ "github.com/75912001/xlib/grpc/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheUserSessionField int32

const (
	CacheUserSessionField_CacheUserSessionField_Unspecified CacheUserSessionField = 0
	CacheUserSessionField_CacheUserSessionField_GatewayKey  CacheUserSessionField = 1
	CacheUserSessionField_CacheUserSessionField_OnlineKey   CacheUserSessionField = 2
	CacheUserSessionField_CacheUserSessionField_Session     CacheUserSessionField = 3
	CacheUserSessionField_CacheUserSessionField_LoginTime   CacheUserSessionField = 4
)

// Enum value maps for CacheUserSessionField.
var (
	CacheUserSessionField_name = map[int32]string{
		0: "CacheUserSessionField_Unspecified",
		1: "CacheUserSessionField_GatewayKey",
		2: "CacheUserSessionField_OnlineKey",
		3: "CacheUserSessionField_Session",
		4: "CacheUserSessionField_LoginTime",
	}
	CacheUserSessionField_value = map[string]int32{
		"CacheUserSessionField_Unspecified": 0,
		"CacheUserSessionField_GatewayKey":  1,
		"CacheUserSessionField_OnlineKey":   2,
		"CacheUserSessionField_Session":     3,
		"CacheUserSessionField_LoginTime":   4,
	}
)

func (x CacheUserSessionField) Enum() *CacheUserSessionField {
	p := new(CacheUserSessionField)
	*p = x
	return p
}

func (x CacheUserSessionField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CacheUserSessionField) Descriptor() protoreflect.EnumDescriptor {
	return file_cache_grpc_proto_enumTypes[0].Descriptor()
}

func (CacheUserSessionField) Type() protoreflect.EnumType {
	return &file_cache_grpc_proto_enumTypes[0]
}

func (x CacheUserSessionField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CacheUserSessionField.Descriptor instead.
func (CacheUserSessionField) EnumDescriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{0}
}

type CacheUserSessionRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field CacheUserSessionField `protobuf:"varint,1,opt,name=field,proto3,enum=cache.CacheUserSessionField" json:"field,omitempty"`
	Value string                `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CacheUserSessionRecord) Reset() {
	*x = CacheUserSessionRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheUserSessionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUserSessionRecord) ProtoMessage() {}

func (x *CacheUserSessionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUserSessionRecord.ProtoReflect.Descriptor instead.
func (*CacheUserSessionRecord) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *CacheUserSessionRecord) GetField() CacheUserSessionField {
	if x != nil {
		return x.Field
	}
	return CacheUserSessionField_CacheUserSessionField_Unspecified
}

func (x *CacheUserSessionRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CacheSetUserRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint64      `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserRecord *UserRecord `protobuf:"bytes,2,opt,name=user_record,json=userRecord,proto3" json:"user_record,omitempty"` // 用户数据
}

func (x *CacheSetUserRecordReq) Reset() {
	*x = CacheSetUserRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetUserRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetUserRecordReq) ProtoMessage() {}

func (x *CacheSetUserRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetUserRecordReq.ProtoReflect.Descriptor instead.
func (*CacheSetUserRecordReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *CacheSetUserRecordReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheSetUserRecordReq) GetUserRecord() *UserRecord {
	if x != nil {
		return x.UserRecord
	}
	return nil
}

type CacheSetUserRecordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheSetUserRecordRes) Reset() {
	*x = CacheSetUserRecordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetUserRecordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetUserRecordRes) ProtoMessage() {}

func (x *CacheSetUserRecordRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetUserRecordRes.ProtoReflect.Descriptor instead.
func (*CacheSetUserRecordRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{2}
}

type CacheGetUserRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *CacheGetUserRecordReq) Reset() {
	*x = CacheGetUserRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetUserRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetUserRecordReq) ProtoMessage() {}

func (x *CacheGetUserRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetUserRecordReq.ProtoReflect.Descriptor instead.
func (*CacheGetUserRecordReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *CacheGetUserRecordReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CacheGetUserRecordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserRecord *UserRecord `protobuf:"bytes,1,opt,name=user_record,json=userRecord,proto3" json:"user_record,omitempty"` // 用户数据
}

func (x *CacheGetUserRecordRes) Reset() {
	*x = CacheGetUserRecordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetUserRecordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetUserRecordRes) ProtoMessage() {}

func (x *CacheGetUserRecordRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetUserRecordRes.ProtoReflect.Descriptor instead.
func (*CacheGetUserRecordRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *CacheGetUserRecordRes) GetUserRecord() *UserRecord {
	if x != nil {
		return x.UserRecord
	}
	return nil
}

type CacheSetVerifyUserTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token        string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpireSecond uint64 `protobuf:"varint,3,opt,name=expire_second,json=expireSecond,proto3" json:"expire_second,omitempty"`
}

func (x *CacheSetVerifyUserTokenReq) Reset() {
	*x = CacheSetVerifyUserTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetVerifyUserTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetVerifyUserTokenReq) ProtoMessage() {}

func (x *CacheSetVerifyUserTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetVerifyUserTokenReq.ProtoReflect.Descriptor instead.
func (*CacheSetVerifyUserTokenReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *CacheSetVerifyUserTokenReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheSetVerifyUserTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CacheSetVerifyUserTokenReq) GetExpireSecond() uint64 {
	if x != nil {
		return x.ExpireSecond
	}
	return 0
}

type CacheSetVerifyUserTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheSetVerifyUserTokenRes) Reset() {
	*x = CacheSetVerifyUserTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetVerifyUserTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetVerifyUserTokenRes) ProtoMessage() {}

func (x *CacheSetVerifyUserTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetVerifyUserTokenRes.ProtoReflect.Descriptor instead.
func (*CacheSetVerifyUserTokenRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{6}
}

type CacheVerifyUserTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CacheVerifyUserTokenReq) Reset() {
	*x = CacheVerifyUserTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheVerifyUserTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheVerifyUserTokenReq) ProtoMessage() {}

func (x *CacheVerifyUserTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheVerifyUserTokenReq.ProtoReflect.Descriptor instead.
func (*CacheVerifyUserTokenReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *CacheVerifyUserTokenReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheVerifyUserTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CacheVerifyUserTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheVerifyUserTokenRes) Reset() {
	*x = CacheVerifyUserTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheVerifyUserTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheVerifyUserTokenRes) ProtoMessage() {}

func (x *CacheVerifyUserTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheVerifyUserTokenRes.ProtoReflect.Descriptor instead.
func (*CacheVerifyUserTokenRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{8}
}

type CacheSetUserSessionRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     uint64                    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Records []*CacheUserSessionRecord `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *CacheSetUserSessionRecordReq) Reset() {
	*x = CacheSetUserSessionRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetUserSessionRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetUserSessionRecordReq) ProtoMessage() {}

func (x *CacheSetUserSessionRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetUserSessionRecordReq.ProtoReflect.Descriptor instead.
func (*CacheSetUserSessionRecordReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *CacheSetUserSessionRecordReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheSetUserSessionRecordReq) GetRecords() []*CacheUserSessionRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type CacheSetUserSessionRecordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheSetUserSessionRecordRes) Reset() {
	*x = CacheSetUserSessionRecordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetUserSessionRecordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetUserSessionRecordRes) ProtoMessage() {}

func (x *CacheSetUserSessionRecordRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetUserSessionRecordRes.ProtoReflect.Descriptor instead.
func (*CacheSetUserSessionRecordRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{10}
}

type CacheSetUserSessionExpireReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid          uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ExpireSecond uint64 `protobuf:"varint,2,opt,name=expire_second,json=expireSecond,proto3" json:"expire_second,omitempty"`
}

func (x *CacheSetUserSessionExpireReq) Reset() {
	*x = CacheSetUserSessionExpireReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetUserSessionExpireReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetUserSessionExpireReq) ProtoMessage() {}

func (x *CacheSetUserSessionExpireReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetUserSessionExpireReq.ProtoReflect.Descriptor instead.
func (*CacheSetUserSessionExpireReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *CacheSetUserSessionExpireReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheSetUserSessionExpireReq) GetExpireSecond() uint64 {
	if x != nil {
		return x.ExpireSecond
	}
	return 0
}

type CacheSetUserSessionExpireRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheSetUserSessionExpireRes) Reset() {
	*x = CacheSetUserSessionExpireRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetUserSessionExpireRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetUserSessionExpireRes) ProtoMessage() {}

func (x *CacheSetUserSessionExpireRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetUserSessionExpireRes.ProtoReflect.Descriptor instead.
func (*CacheSetUserSessionExpireRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{12}
}

type CacheGetUserSessionRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    uint64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Fields []CacheUserSessionField `protobuf:"varint,2,rep,packed,name=fields,proto3,enum=cache.CacheUserSessionField" json:"fields,omitempty"`
}

func (x *CacheGetUserSessionRecordReq) Reset() {
	*x = CacheGetUserSessionRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetUserSessionRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetUserSessionRecordReq) ProtoMessage() {}

func (x *CacheGetUserSessionRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetUserSessionRecordReq.ProtoReflect.Descriptor instead.
func (*CacheGetUserSessionRecordReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *CacheGetUserSessionRecordReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheGetUserSessionRecordReq) GetFields() []CacheUserSessionField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type CacheGetUserSessionRecordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*CacheUserSessionRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *CacheGetUserSessionRecordRes) Reset() {
	*x = CacheGetUserSessionRecordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetUserSessionRecordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetUserSessionRecordRes) ProtoMessage() {}

func (x *CacheGetUserSessionRecordRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetUserSessionRecordRes.ProtoReflect.Descriptor instead.
func (*CacheGetUserSessionRecordRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *CacheGetUserSessionRecordRes) GetRecords() []*CacheUserSessionRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_cache_grpc_proto protoreflect.FileDescriptor

var file_cache_grpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x1a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x16, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x32, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x63, 0x0a, 0x15, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x31, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22, 0x30, 0x0a,
	0x15, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22,
	0x4a, 0x0a, 0x15, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x70, 0x0a, 0x1a, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x1c, 0x0a,
	0x1a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x48, 0x0a, 0x17, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x61, 0x63, 0x68, 0x65, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x22, 0x70, 0x0a, 0x1c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2,
	0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x37, 0x0a, 0x07, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x22, 0x1e, 0x0a, 0x1c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x22, 0x5c, 0x0a, 0x1c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42,
	0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x22, 0x1e, 0x0a, 0x1c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x6d, 0x0a, 0x1c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2,
	0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22,
	0x57, 0x0a, 0x1c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12,
	0x37, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x2a, 0xd1, 0x01, 0x0a, 0x15, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x25, 0x0a, 0x21, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x55, 0x6e, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10, 0x00, 0x12, 0x24, 0x0a, 0x20, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x65, 0x79, 0x10, 0x01, 0x12,
	0x23, 0x0a, 0x1f, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4b,
	0x65, 0x79, 0x10, 0x02, 0x12, 0x21, 0x0a, 0x1d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x10, 0x03, 0x12, 0x23, 0x0a, 0x1f, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x10, 0x04, 0x32, 0x80, 0x06, 0x0a,
	0x0c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a,
	0x12, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x1a, 0x1c, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22,
	0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x5c, 0x0a, 0x12, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x12, 0x1c, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x1c, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2,
	0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x6b, 0x0a, 0x17, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x53, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x21, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x53, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52,
	0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x62, 0x0a, 0x14, 0x43, 0x61, 0x63, 0x68, 0x65, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e,
	0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1e,
	0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x0a,
	0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x71, 0x0a, 0x19, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x23, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x71, 0x0a,
	0x19, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x23, 0x2e, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x23, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05,
	0x12, 0x71, 0x0a, 0x19, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x23, 0x2e,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x1a, 0x23, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73,
	0xf0, 0x01, 0x05, 0x1a, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xa0, 0x01, 0x05, 0x42,
	0x14, 0x5a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cache_grpc_proto_rawDescOnce sync.Once
	file_cache_grpc_proto_rawDescData = file_cache_grpc_proto_rawDesc
)

func file_cache_grpc_proto_rawDescGZIP() []byte {
	file_cache_grpc_proto_rawDescOnce.Do(func() {
		file_cache_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_cache_grpc_proto_rawDescData)
	})
	return file_cache_grpc_proto_rawDescData
}

var file_cache_grpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cache_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cache_grpc_proto_goTypes = []any{
	(CacheUserSessionField)(0),           // 0: cache.CacheUserSessionField
	(*CacheUserSessionRecord)(nil),       // 1: cache.CacheUserSessionRecord
	(*CacheSetUserRecordReq)(nil),        // 2: cache.CacheSetUserRecordReq
	(*CacheSetUserRecordRes)(nil),        // 3: cache.CacheSetUserRecordRes
	(*CacheGetUserRecordReq)(nil),        // 4: cache.CacheGetUserRecordReq
	(*CacheGetUserRecordRes)(nil),        // 5: cache.CacheGetUserRecordRes
	(*CacheSetVerifyUserTokenReq)(nil),   // 6: cache.CacheSetVerifyUserTokenReq
	(*CacheSetVerifyUserTokenRes)(nil),   // 7: cache.CacheSetVerifyUserTokenRes
	(*CacheVerifyUserTokenReq)(nil),      // 8: cache.CacheVerifyUserTokenReq
	(*CacheVerifyUserTokenRes)(nil),      // 9: cache.CacheVerifyUserTokenRes
	(*CacheSetUserSessionRecordReq)(nil), // 10: cache.CacheSetUserSessionRecordReq
	(*CacheSetUserSessionRecordRes)(nil), // 11: cache.CacheSetUserSessionRecordRes
	(*CacheSetUserSessionExpireReq)(nil), // 12: cache.CacheSetUserSessionExpireReq
	(*CacheSetUserSessionExpireRes)(nil), // 13: cache.CacheSetUserSessionExpireRes
	(*CacheGetUserSessionRecordReq)(nil), // 14: cache.CacheGetUserSessionRecordReq
	(*CacheGetUserSessionRecordRes)(nil), // 15: cache.CacheGetUserSessionRecordRes
	(*UserRecord)(nil),                   // 16: user.UserRecord
}
var file_cache_grpc_proto_depIdxs = []int32{
	0,  // 0: cache.CacheUserSessionRecord.field:type_name -> cache.CacheUserSessionField
	16, // 1: cache.CacheSetUserRecordReq.user_record:type_name -> user.UserRecord
	16, // 2: cache.CacheGetUserRecordRes.user_record:type_name -> user.UserRecord
	1,  // 3: cache.CacheSetUserSessionRecordReq.records:type_name -> cache.CacheUserSessionRecord
	0,  // 4: cache.CacheGetUserSessionRecordReq.fields:type_name -> cache.CacheUserSessionField
	1,  // 5: cache.CacheGetUserSessionRecordRes.records:type_name -> cache.CacheUserSessionRecord
	2,  // 6: cache.CacheService.CacheSetUserRecord:input_type -> cache.CacheSetUserRecordReq
	4,  // 7: cache.CacheService.CacheGetUserRecord:input_type -> cache.CacheGetUserRecordReq
	6,  // 8: cache.CacheService.CacheSetVerifyUserToken:input_type -> cache.CacheSetVerifyUserTokenReq
	8,  // 9: cache.CacheService.CacheVerifyUserToken:input_type -> cache.CacheVerifyUserTokenReq
	10, // 10: cache.CacheService.CacheSetUserSessionRecord:input_type -> cache.CacheSetUserSessionRecordReq
	12, // 11: cache.CacheService.CacheSetUserSessionExpire:input_type -> cache.CacheSetUserSessionExpireReq
	14, // 12: cache.CacheService.CacheGetUserSessionRecord:input_type -> cache.CacheGetUserSessionRecordReq
	3,  // 13: cache.CacheService.CacheSetUserRecord:output_type -> cache.CacheSetUserRecordRes
	5,  // 14: cache.CacheService.CacheGetUserRecord:output_type -> cache.CacheGetUserRecordRes
	7,  // 15: cache.CacheService.CacheSetVerifyUserToken:output_type -> cache.CacheSetVerifyUserTokenRes
	9,  // 16: cache.CacheService.CacheVerifyUserToken:output_type -> cache.CacheVerifyUserTokenRes
	11, // 17: cache.CacheService.CacheSetUserSessionRecord:output_type -> cache.CacheSetUserSessionRecordRes
	13, // 18: cache.CacheService.CacheSetUserSessionExpire:output_type -> cache.CacheSetUserSessionExpireRes
	15, // 19: cache.CacheService.CacheGetUserSessionRecord:output_type -> cache.CacheGetUserSessionRecordRes
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_cache_grpc_proto_init() }
func file_cache_grpc_proto_init() {
	if File_cache_grpc_proto != nil {
		return
	}
	file_user_record_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cache_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CacheUserSessionRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetUserRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetUserRecordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetUserRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetUserRecordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetVerifyUserTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetVerifyUserTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CacheVerifyUserTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CacheVerifyUserTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetUserSessionRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetUserSessionRecordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetUserSessionExpireReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetUserSessionExpireRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetUserSessionRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetUserSessionRecordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cache_grpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_grpc_proto_goTypes,
		DependencyIndexes: file_cache_grpc_proto_depIdxs,
		EnumInfos:         file_cache_grpc_proto_enumTypes,
		MessageInfos:      file_cache_grpc_proto_msgTypes,
	}.Build()
	File_cache_grpc_proto = out.File
	file_cache_grpc_proto_rawDesc = nil
	file_cache_grpc_proto_goTypes = nil
	file_cache_grpc_proto_depIdxs = nil
}
