// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: cache.grpc.proto

package pb

import (
	_ "github.com/75912001/xlib/grpc/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheSetAccountRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid           uint64         `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                         // uid, 账号唯一标识, 必须与 account_record.uid 一致
	AccountRecord *AccountRecord `protobuf:"bytes,2,opt,name=account_record,json=accountRecord,proto3" json:"account_record,omitempty"` // 账号档案
}

func (x *CacheSetAccountRecordReq) Reset() {
	*x = CacheSetAccountRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetAccountRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetAccountRecordReq) ProtoMessage() {}

func (x *CacheSetAccountRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetAccountRecordReq.ProtoReflect.Descriptor instead.
func (*CacheSetAccountRecordReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *CacheSetAccountRecordReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheSetAccountRecordReq) GetAccountRecord() *AccountRecord {
	if x != nil {
		return x.AccountRecord
	}
	return nil
}

type CacheSetAccountRecordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheSetAccountRecordRes) Reset() {
	*x = CacheSetAccountRecordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetAccountRecordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetAccountRecordRes) ProtoMessage() {}

func (x *CacheSetAccountRecordRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetAccountRecordRes.ProtoReflect.Descriptor instead.
func (*CacheSetAccountRecordRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{1}
}

type CacheGetAccountRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // uid, 账号唯一标识
}

func (x *CacheGetAccountRecordReq) Reset() {
	*x = CacheGetAccountRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetAccountRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetAccountRecordReq) ProtoMessage() {}

func (x *CacheGetAccountRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetAccountRecordReq.ProtoReflect.Descriptor instead.
func (*CacheGetAccountRecordReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *CacheGetAccountRecordReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CacheGetAccountRecordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountRecord *AccountRecord `protobuf:"bytes,1,opt,name=account_record,json=accountRecord,proto3" json:"account_record,omitempty"` // 账号档案, 成功时有效, 表示 uid 对应的 AccountRecord。
}

func (x *CacheGetAccountRecordRes) Reset() {
	*x = CacheGetAccountRecordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetAccountRecordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetAccountRecordRes) ProtoMessage() {}

func (x *CacheGetAccountRecordRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetAccountRecordRes.ProtoReflect.Descriptor instead.
func (*CacheGetAccountRecordRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *CacheGetAccountRecordRes) GetAccountRecord() *AccountRecord {
	if x != nil {
		return x.AccountRecord
	}
	return nil
}

type CacheSetAccountVerifyTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account            string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                                                   // 账号
	AccountVerifyToken string `protobuf:"bytes,2,opt,name=account_verify_token,json=accountVerifyToken,proto3" json:"account_verify_token,omitempty"` // 使用一次性 SETNX 语义, 未消费前不覆盖
	ExpireSecond       uint64 `protobuf:"varint,3,opt,name=expire_second,json=expireSecond,proto3" json:"expire_second,omitempty"`                    // 单位为秒
}

func (x *CacheSetAccountVerifyTokenReq) Reset() {
	*x = CacheSetAccountVerifyTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetAccountVerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetAccountVerifyTokenReq) ProtoMessage() {}

func (x *CacheSetAccountVerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetAccountVerifyTokenReq.ProtoReflect.Descriptor instead.
func (*CacheSetAccountVerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *CacheSetAccountVerifyTokenReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CacheSetAccountVerifyTokenReq) GetAccountVerifyToken() string {
	if x != nil {
		return x.AccountVerifyToken
	}
	return ""
}

func (x *CacheSetAccountVerifyTokenReq) GetExpireSecond() uint64 {
	if x != nil {
		return x.ExpireSecond
	}
	return 0
}

type CacheSetAccountVerifyTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheSetAccountVerifyTokenRes) Reset() {
	*x = CacheSetAccountVerifyTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetAccountVerifyTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetAccountVerifyTokenRes) ProtoMessage() {}

func (x *CacheSetAccountVerifyTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetAccountVerifyTokenRes.ProtoReflect.Descriptor instead.
func (*CacheSetAccountVerifyTokenRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{5}
}

type CacheUseAccountVerifyTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account            string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                                                   // 账号
	AccountVerifyToken string `protobuf:"bytes,2,opt,name=account_verify_token,json=accountVerifyToken,proto3" json:"account_verify_token,omitempty"` // accountVerifyToken, login 签发后由 cache 原子校验并消费
}

func (x *CacheUseAccountVerifyTokenReq) Reset() {
	*x = CacheUseAccountVerifyTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheUseAccountVerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUseAccountVerifyTokenReq) ProtoMessage() {}

func (x *CacheUseAccountVerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUseAccountVerifyTokenReq.ProtoReflect.Descriptor instead.
func (*CacheUseAccountVerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *CacheUseAccountVerifyTokenReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CacheUseAccountVerifyTokenReq) GetAccountVerifyToken() string {
	if x != nil {
		return x.AccountVerifyToken
	}
	return ""
}

type CacheUseAccountVerifyTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 表示 account 绑定或新创建的可信 uid
}

func (x *CacheUseAccountVerifyTokenRes) Reset() {
	*x = CacheUseAccountVerifyTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheUseAccountVerifyTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUseAccountVerifyTokenRes) ProtoMessage() {}

func (x *CacheUseAccountVerifyTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUseAccountVerifyTokenRes.ProtoReflect.Descriptor instead.
func (*CacheUseAccountVerifyTokenRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *CacheUseAccountVerifyTokenRes) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CacheUserSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayKey       string `protobuf:"bytes,1,opt,name=gateway_key,json=gatewayKey,proto3" json:"gateway_key,omitempty"`                      // gatewayKey, 用于定位当前 Gateway
	UserSession      string `protobuf:"bytes,2,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`                   // userSession, CAS 匹配的稳定身份字段
	LoginTimestampMs int64  `protobuf:"varint,3,opt,name=login_timestamp_ms,json=loginTimestampMs,proto3" json:"login_timestamp_ms,omitempty"` // 登录时间戳, 单位毫秒
	OnlineKey        string `protobuf:"bytes,4,opt,name=online_key,json=onlineKey,proto3" json:"online_key,omitempty"`                         // onlineKey, 用于定位当前 Online
}

func (x *CacheUserSession) Reset() {
	*x = CacheUserSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheUserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUserSession) ProtoMessage() {}

func (x *CacheUserSession) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUserSession.ProtoReflect.Descriptor instead.
func (*CacheUserSession) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *CacheUserSession) GetGatewayKey() string {
	if x != nil {
		return x.GatewayKey
	}
	return ""
}

func (x *CacheUserSession) GetUserSession() string {
	if x != nil {
		return x.UserSession
	}
	return ""
}

func (x *CacheUserSession) GetLoginTimestampMs() int64 {
	if x != nil {
		return x.LoginTimestampMs
	}
	return 0
}

func (x *CacheUserSession) GetOnlineKey() string {
	if x != nil {
		return x.OnlineKey
	}
	return ""
}

type CacheGetUserSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // uid, 账号唯一标识
}

func (x *CacheGetUserSessionReq) Reset() {
	*x = CacheGetUserSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetUserSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetUserSessionReq) ProtoMessage() {}

func (x *CacheGetUserSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetUserSessionReq.ProtoReflect.Descriptor instead.
func (*CacheGetUserSessionReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *CacheGetUserSessionReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CacheGetUserSessionRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *CacheUserSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"` // 成功时有效, 包含 cache userSession 全部字段
}

func (x *CacheGetUserSessionRes) Reset() {
	*x = CacheGetUserSessionRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetUserSessionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetUserSessionRes) ProtoMessage() {}

func (x *CacheGetUserSessionRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetUserSessionRes.ProtoReflect.Descriptor instead.
func (*CacheGetUserSessionRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *CacheGetUserSessionRes) GetSession() *CacheUserSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type CacheBeginUserSessionCASReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // uid, 账号唯一标识
	// expected_user_session == ""
	// -> 期望当前 Redis 里没有 user:{uid}:session 对应的 cache userSession
	// -> 如果 key 已存在, 返回 0, 不写入
	// -> 如果 key 不存在, 写入新 userSession, 设置 TTL, 返回 1
	//
	// expected_user_session != ""
	// -> 期望当前 Redis hash 里的 userSession 字段等于 expectedUserSession
	// -> 如果不存在或不匹配, 返回 0, 不写入
	// -> 如果匹配, 删除旧 hash, 写入新 records, 设置 TTL, 返回 1
	ExpectedUserSession string `protobuf:"bytes,2,opt,name=expected_user_session,json=expectedUserSession,proto3" json:"expected_user_session,omitempty"` // 表示预期当前 user_session 必须匹配
	GatewayKey          string `protobuf:"bytes,3,opt,name=gateway_key,json=gatewayKey,proto3" json:"gateway_key,omitempty"`                              // gatewayKey, 用于定位当前 Gateway
	UserSession         string `protobuf:"bytes,4,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`                           // userSession, 新 cache userSession 的稳定身份字段
	LoginTimestampMs    int64  `protobuf:"varint,5,opt,name=login_timestamp_ms,json=loginTimestampMs,proto3" json:"login_timestamp_ms,omitempty"`         // 登录时间戳, 单位毫秒
	OnlineKey           string `protobuf:"bytes,6,opt,name=online_key,json=onlineKey,proto3" json:"online_key,omitempty"`                                 // onlineKey, 用于定位当前 Online
	ExpireSecond        uint64 `protobuf:"varint,7,opt,name=expire_second,json=expireSecond,proto3" json:"expire_second,omitempty"`                       // 单位为秒
}

func (x *CacheBeginUserSessionCASReq) Reset() {
	*x = CacheBeginUserSessionCASReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheBeginUserSessionCASReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheBeginUserSessionCASReq) ProtoMessage() {}

func (x *CacheBeginUserSessionCASReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheBeginUserSessionCASReq.ProtoReflect.Descriptor instead.
func (*CacheBeginUserSessionCASReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *CacheBeginUserSessionCASReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheBeginUserSessionCASReq) GetExpectedUserSession() string {
	if x != nil {
		return x.ExpectedUserSession
	}
	return ""
}

func (x *CacheBeginUserSessionCASReq) GetGatewayKey() string {
	if x != nil {
		return x.GatewayKey
	}
	return ""
}

func (x *CacheBeginUserSessionCASReq) GetUserSession() string {
	if x != nil {
		return x.UserSession
	}
	return ""
}

func (x *CacheBeginUserSessionCASReq) GetLoginTimestampMs() int64 {
	if x != nil {
		return x.LoginTimestampMs
	}
	return 0
}

func (x *CacheBeginUserSessionCASReq) GetOnlineKey() string {
	if x != nil {
		return x.OnlineKey
	}
	return ""
}

func (x *CacheBeginUserSessionCASReq) GetExpireSecond() uint64 {
	if x != nil {
		return x.ExpireSecond
	}
	return 0
}

type CacheBeginUserSessionCASRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheBeginUserSessionCASRes) Reset() {
	*x = CacheBeginUserSessionCASRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheBeginUserSessionCASRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheBeginUserSessionCASRes) ProtoMessage() {}

func (x *CacheBeginUserSessionCASRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheBeginUserSessionCASRes.ProtoReflect.Descriptor instead.
func (*CacheBeginUserSessionCASRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{12}
}

type CacheEndUserSessionCASReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid                 uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                             // uid, 账号唯一标识
	ExpectedUserSession string `protobuf:"bytes,2,opt,name=expected_user_session,json=expectedUserSession,proto3" json:"expected_user_session,omitempty"` // 用于 CAS 删除前匹配当前 userSession
}

func (x *CacheEndUserSessionCASReq) Reset() {
	*x = CacheEndUserSessionCASReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheEndUserSessionCASReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEndUserSessionCASReq) ProtoMessage() {}

func (x *CacheEndUserSessionCASReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEndUserSessionCASReq.ProtoReflect.Descriptor instead.
func (*CacheEndUserSessionCASReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *CacheEndUserSessionCASReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheEndUserSessionCASReq) GetExpectedUserSession() string {
	if x != nil {
		return x.ExpectedUserSession
	}
	return ""
}

type CacheEndUserSessionCASRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheEndUserSessionCASRes) Reset() {
	*x = CacheEndUserSessionCASRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheEndUserSessionCASRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEndUserSessionCASRes) ProtoMessage() {}

func (x *CacheEndUserSessionCASRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEndUserSessionCASRes.ProtoReflect.Descriptor instead.
func (*CacheEndUserSessionCASRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{14}
}

type CacheRefreshUserSessionCASReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid                 uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                                             // uid, 账号唯一标识
	ExpectedUserSession string `protobuf:"bytes,2,opt,name=expected_user_session,json=expectedUserSession,proto3" json:"expected_user_session,omitempty"` // 用于 CAS 续期前匹配当前 userSession
	ExpireSecond        uint64 `protobuf:"varint,3,opt,name=expire_second,json=expireSecond,proto3" json:"expire_second,omitempty"`                       // 单位为秒
}

func (x *CacheRefreshUserSessionCASReq) Reset() {
	*x = CacheRefreshUserSessionCASReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheRefreshUserSessionCASReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRefreshUserSessionCASReq) ProtoMessage() {}

func (x *CacheRefreshUserSessionCASReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRefreshUserSessionCASReq.ProtoReflect.Descriptor instead.
func (*CacheRefreshUserSessionCASReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{15}
}

func (x *CacheRefreshUserSessionCASReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheRefreshUserSessionCASReq) GetExpectedUserSession() string {
	if x != nil {
		return x.ExpectedUserSession
	}
	return ""
}

func (x *CacheRefreshUserSessionCASReq) GetExpireSecond() uint64 {
	if x != nil {
		return x.ExpireSecond
	}
	return 0
}

type CacheRefreshUserSessionCASRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheRefreshUserSessionCASRes) Reset() {
	*x = CacheRefreshUserSessionCASRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheRefreshUserSessionCASRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRefreshUserSessionCASRes) ProtoMessage() {}

func (x *CacheRefreshUserSessionCASRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRefreshUserSessionCASRes.ProtoReflect.Descriptor instead.
func (*CacheRefreshUserSessionCASRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{16}
}

var File_cache_grpc_proto protoreflect.FileDescriptor

var file_cache_grpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x1a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f,
	0x0a, 0x18, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x3a, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22,
	0x1a, 0x0a, 0x18, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22, 0x33, 0x0a, 0x18, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x22, 0x56, 0x0a, 0x18, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x97, 0x01, 0x0a, 0x1d, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xc2, 0x3e, 0x02,
	0x50, 0x01, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a,
	0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x22, 0x72, 0x0a, 0x1d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x14, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x31, 0x0a, 0x1d, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x55, 0x73, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x10, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1f, 0x0a, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x65, 0x79,
	0x12, 0x21, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x10, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4b, 0x65, 0x79,
	0x22, 0x31, 0x0a, 0x16, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x16, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a,
	0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0xa0, 0x02, 0x0a, 0x1b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2,
	0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x65, 0x78, 0x70,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x21,
	0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x23,
	0x0a, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x42, 0x65, 0x67, 0x69,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52,
	0x65, 0x73, 0x22, 0x68, 0x0a, 0x19, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e,
	0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x65, 0x78, 0x70, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x1b, 0x0a, 0x19,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x1d, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x13, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x1f, 0x0a,
	0x1d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x73, 0x32, 0x85,
	0x07, 0x0a, 0x0c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x65, 0x0a, 0x15, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52,
	0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x65, 0x0a, 0x15, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x1f, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x1a, 0x1f, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x74, 0x0a,
	0x1a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x2e, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x24, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73,
	0xf0, 0x01, 0x01, 0x12, 0x74, 0x0a, 0x1a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x24, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55,
	0x73, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2,
	0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x01, 0x12, 0x5f, 0x0a, 0x13, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x1d, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x0a,
	0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x6e, 0x0a, 0x18, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x73, 0x22, 0x0a,
	0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x68, 0x0a, 0x16, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x45, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x43, 0x41, 0x53, 0x12, 0x20, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x45, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x43, 0x41, 0x53, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33,
	0x73, 0xf0, 0x01, 0x05, 0x12, 0x74, 0x0a, 0x1a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x41, 0x53, 0x12, 0x24, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x73, 0x22, 0x0a,
	0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x1a, 0x0a, 0xc2, 0x3e, 0x07, 0x52,
	0x02, 0x33, 0x73, 0xa0, 0x01, 0x05, 0x42, 0x14, 0x5a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cache_grpc_proto_rawDescOnce sync.Once
	file_cache_grpc_proto_rawDescData = file_cache_grpc_proto_rawDesc
)

func file_cache_grpc_proto_rawDescGZIP() []byte {
	file_cache_grpc_proto_rawDescOnce.Do(func() {
		file_cache_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_cache_grpc_proto_rawDescData)
	})
	return file_cache_grpc_proto_rawDescData
}

var file_cache_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cache_grpc_proto_goTypes = []any{
	(*CacheSetAccountRecordReq)(nil),      // 0: cache.CacheSetAccountRecordReq
	(*CacheSetAccountRecordRes)(nil),      // 1: cache.CacheSetAccountRecordRes
	(*CacheGetAccountRecordReq)(nil),      // 2: cache.CacheGetAccountRecordReq
	(*CacheGetAccountRecordRes)(nil),      // 3: cache.CacheGetAccountRecordRes
	(*CacheSetAccountVerifyTokenReq)(nil), // 4: cache.CacheSetAccountVerifyTokenReq
	(*CacheSetAccountVerifyTokenRes)(nil), // 5: cache.CacheSetAccountVerifyTokenRes
	(*CacheUseAccountVerifyTokenReq)(nil), // 6: cache.CacheUseAccountVerifyTokenReq
	(*CacheUseAccountVerifyTokenRes)(nil), // 7: cache.CacheUseAccountVerifyTokenRes
	(*CacheUserSession)(nil),              // 8: cache.CacheUserSession
	(*CacheGetUserSessionReq)(nil),        // 9: cache.CacheGetUserSessionReq
	(*CacheGetUserSessionRes)(nil),        // 10: cache.CacheGetUserSessionRes
	(*CacheBeginUserSessionCASReq)(nil),   // 11: cache.CacheBeginUserSessionCASReq
	(*CacheBeginUserSessionCASRes)(nil),   // 12: cache.CacheBeginUserSessionCASRes
	(*CacheEndUserSessionCASReq)(nil),     // 13: cache.CacheEndUserSessionCASReq
	(*CacheEndUserSessionCASRes)(nil),     // 14: cache.CacheEndUserSessionCASRes
	(*CacheRefreshUserSessionCASReq)(nil), // 15: cache.CacheRefreshUserSessionCASReq
	(*CacheRefreshUserSessionCASRes)(nil), // 16: cache.CacheRefreshUserSessionCASRes
	(*AccountRecord)(nil),                 // 17: user.AccountRecord
}
var file_cache_grpc_proto_depIdxs = []int32{
	17, // 0: cache.CacheSetAccountRecordReq.account_record:type_name -> user.AccountRecord
	17, // 1: cache.CacheGetAccountRecordRes.account_record:type_name -> user.AccountRecord
	8,  // 2: cache.CacheGetUserSessionRes.session:type_name -> cache.CacheUserSession
	0,  // 3: cache.CacheService.CacheSetAccountRecord:input_type -> cache.CacheSetAccountRecordReq
	2,  // 4: cache.CacheService.CacheGetAccountRecord:input_type -> cache.CacheGetAccountRecordReq
	4,  // 5: cache.CacheService.CacheSetAccountVerifyToken:input_type -> cache.CacheSetAccountVerifyTokenReq
	6,  // 6: cache.CacheService.CacheUseAccountVerifyToken:input_type -> cache.CacheUseAccountVerifyTokenReq
	9,  // 7: cache.CacheService.CacheGetUserSession:input_type -> cache.CacheGetUserSessionReq
	11, // 8: cache.CacheService.CacheBeginUserSessionCAS:input_type -> cache.CacheBeginUserSessionCASReq
	13, // 9: cache.CacheService.CacheEndUserSessionCAS:input_type -> cache.CacheEndUserSessionCASReq
	15, // 10: cache.CacheService.CacheRefreshUserSessionCAS:input_type -> cache.CacheRefreshUserSessionCASReq
	1,  // 11: cache.CacheService.CacheSetAccountRecord:output_type -> cache.CacheSetAccountRecordRes
	3,  // 12: cache.CacheService.CacheGetAccountRecord:output_type -> cache.CacheGetAccountRecordRes
	5,  // 13: cache.CacheService.CacheSetAccountVerifyToken:output_type -> cache.CacheSetAccountVerifyTokenRes
	7,  // 14: cache.CacheService.CacheUseAccountVerifyToken:output_type -> cache.CacheUseAccountVerifyTokenRes
	10, // 15: cache.CacheService.CacheGetUserSession:output_type -> cache.CacheGetUserSessionRes
	12, // 16: cache.CacheService.CacheBeginUserSessionCAS:output_type -> cache.CacheBeginUserSessionCASRes
	14, // 17: cache.CacheService.CacheEndUserSessionCAS:output_type -> cache.CacheEndUserSessionCASRes
	16, // 18: cache.CacheService.CacheRefreshUserSessionCAS:output_type -> cache.CacheRefreshUserSessionCASRes
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_cache_grpc_proto_init() }
func file_cache_grpc_proto_init() {
	if File_cache_grpc_proto != nil {
		return
	}
	file_account_record_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cache_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetAccountRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetAccountRecordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetAccountRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetAccountRecordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetAccountVerifyTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetAccountVerifyTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CacheUseAccountVerifyTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CacheUseAccountVerifyTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CacheUserSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetUserSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetUserSessionRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*CacheBeginUserSessionCASReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*CacheBeginUserSessionCASRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CacheEndUserSessionCASReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*CacheEndUserSessionCASRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*CacheRefreshUserSessionCASReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*CacheRefreshUserSessionCASRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cache_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_grpc_proto_goTypes,
		DependencyIndexes: file_cache_grpc_proto_depIdxs,
		MessageInfos:      file_cache_grpc_proto_msgTypes,
	}.Build()
	File_cache_grpc_proto = out.File
	file_cache_grpc_proto_rawDesc = nil
	file_cache_grpc_proto_goTypes = nil
	file_cache_grpc_proto_depIdxs = nil
}
