// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: cache.grpc.proto

package pb

import (
	_ "github.com/75912001/xlib/grpc/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheSetUserRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint64      `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserRecord *UserRecord `protobuf:"bytes,2,opt,name=user_record,json=userRecord,proto3" json:"user_record,omitempty"` // 用户数据
}

func (x *CacheSetUserRecordReq) Reset() {
	*x = CacheSetUserRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetUserRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetUserRecordReq) ProtoMessage() {}

func (x *CacheSetUserRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetUserRecordReq.ProtoReflect.Descriptor instead.
func (*CacheSetUserRecordReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *CacheSetUserRecordReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheSetUserRecordReq) GetUserRecord() *UserRecord {
	if x != nil {
		return x.UserRecord
	}
	return nil
}

type CacheSetUserRecordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheSetUserRecordRes) Reset() {
	*x = CacheSetUserRecordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetUserRecordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetUserRecordRes) ProtoMessage() {}

func (x *CacheSetUserRecordRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetUserRecordRes.ProtoReflect.Descriptor instead.
func (*CacheSetUserRecordRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{1}
}

type CacheGetUserRecordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *CacheGetUserRecordReq) Reset() {
	*x = CacheGetUserRecordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetUserRecordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetUserRecordReq) ProtoMessage() {}

func (x *CacheGetUserRecordReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetUserRecordReq.ProtoReflect.Descriptor instead.
func (*CacheGetUserRecordReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *CacheGetUserRecordReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CacheGetUserRecordRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserRecord *UserRecord `protobuf:"bytes,1,opt,name=user_record,json=userRecord,proto3" json:"user_record,omitempty"` // 用户数据，成功时有效，表示 uid 对应的用户档案。
}

func (x *CacheGetUserRecordRes) Reset() {
	*x = CacheGetUserRecordRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetUserRecordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetUserRecordRes) ProtoMessage() {}

func (x *CacheGetUserRecordRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetUserRecordRes.ProtoReflect.Descriptor instead.
func (*CacheGetUserRecordRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *CacheGetUserRecordRes) GetUserRecord() *UserRecord {
	if x != nil {
		return x.UserRecord
	}
	return nil
}

type CacheSetAccountVerifyTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account      string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                                // 账号
	Token        string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                    // 使用一次性 SETNX 语义, 未消费前不覆盖
	ExpireSecond uint64 `protobuf:"varint,3,opt,name=expire_second,json=expireSecond,proto3" json:"expire_second,omitempty"` // 单位为秒
}

func (x *CacheSetAccountVerifyTokenReq) Reset() {
	*x = CacheSetAccountVerifyTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetAccountVerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetAccountVerifyTokenReq) ProtoMessage() {}

func (x *CacheSetAccountVerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetAccountVerifyTokenReq.ProtoReflect.Descriptor instead.
func (*CacheSetAccountVerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *CacheSetAccountVerifyTokenReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CacheSetAccountVerifyTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CacheSetAccountVerifyTokenReq) GetExpireSecond() uint64 {
	if x != nil {
		return x.ExpireSecond
	}
	return 0
}

type CacheSetAccountVerifyTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheSetAccountVerifyTokenRes) Reset() {
	*x = CacheSetAccountVerifyTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheSetAccountVerifyTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetAccountVerifyTokenRes) ProtoMessage() {}

func (x *CacheSetAccountVerifyTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetAccountVerifyTokenRes.ProtoReflect.Descriptor instead.
func (*CacheSetAccountVerifyTokenRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{5}
}

type CacheUseAccountVerifyTokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // 账号
	Token   string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CacheUseAccountVerifyTokenReq) Reset() {
	*x = CacheUseAccountVerifyTokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheUseAccountVerifyTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUseAccountVerifyTokenReq) ProtoMessage() {}

func (x *CacheUseAccountVerifyTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUseAccountVerifyTokenReq.ProtoReflect.Descriptor instead.
func (*CacheUseAccountVerifyTokenReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *CacheUseAccountVerifyTokenReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CacheUseAccountVerifyTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CacheUseAccountVerifyTokenRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` // 表示 account 绑定或新创建的可信 uid
}

func (x *CacheUseAccountVerifyTokenRes) Reset() {
	*x = CacheUseAccountVerifyTokenRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheUseAccountVerifyTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUseAccountVerifyTokenRes) ProtoMessage() {}

func (x *CacheUseAccountVerifyTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUseAccountVerifyTokenRes.ProtoReflect.Descriptor instead.
func (*CacheUseAccountVerifyTokenRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *CacheUseAccountVerifyTokenRes) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CacheUserSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GatewayKey  string `protobuf:"bytes,1,opt,name=gateway_key,json=gatewayKey,proto3" json:"gateway_key,omitempty"`       // 用于定位当前 gateway
	UserSession string `protobuf:"bytes,2,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`    // 是 CAS 匹配的稳定身份字段
	LoginTimeMs int64  `protobuf:"varint,3,opt,name=login_time_ms,json=loginTimeMs,proto3" json:"login_time_ms,omitempty"` // 毫秒
	OnlineKey   string `protobuf:"bytes,4,opt,name=online_key,json=onlineKey,proto3" json:"online_key,omitempty"`          // 用于定位当前 online。
}

func (x *CacheUserSession) Reset() {
	*x = CacheUserSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheUserSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheUserSession) ProtoMessage() {}

func (x *CacheUserSession) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheUserSession.ProtoReflect.Descriptor instead.
func (*CacheUserSession) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *CacheUserSession) GetGatewayKey() string {
	if x != nil {
		return x.GatewayKey
	}
	return ""
}

func (x *CacheUserSession) GetUserSession() string {
	if x != nil {
		return x.UserSession
	}
	return ""
}

func (x *CacheUserSession) GetLoginTimeMs() int64 {
	if x != nil {
		return x.LoginTimeMs
	}
	return 0
}

func (x *CacheUserSession) GetOnlineKey() string {
	if x != nil {
		return x.OnlineKey
	}
	return ""
}

type CacheGetUserSessionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *CacheGetUserSessionReq) Reset() {
	*x = CacheGetUserSessionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetUserSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetUserSessionReq) ProtoMessage() {}

func (x *CacheGetUserSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetUserSessionReq.ProtoReflect.Descriptor instead.
func (*CacheGetUserSessionReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *CacheGetUserSessionReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type CacheGetUserSessionRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Session *CacheUserSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"` // 成功时有效，包含 CacheUserSession 全部字段
}

func (x *CacheGetUserSessionRes) Reset() {
	*x = CacheGetUserSessionRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheGetUserSessionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetUserSessionRes) ProtoMessage() {}

func (x *CacheGetUserSessionRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetUserSessionRes.ProtoReflect.Descriptor instead.
func (*CacheGetUserSessionRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *CacheGetUserSessionRes) GetSession() *CacheUserSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type CacheBeginUserSessionCASReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid                 uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ExpectedUserSession string `protobuf:"bytes,2,opt,name=expected_user_session,json=expectedUserSession,proto3" json:"expected_user_session,omitempty"` // 表示预期当前 user_session 必须匹配
	GatewayKey          string `protobuf:"bytes,3,opt,name=gateway_key,json=gatewayKey,proto3" json:"gateway_key,omitempty"`                              // 用于定位当前 gateway
	UserSession         string `protobuf:"bytes,4,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"`                           // 是新在线会话的稳定身份字段
	LoginTimeMs         int64  `protobuf:"varint,5,opt,name=login_time_ms,json=loginTimeMs,proto3" json:"login_time_ms,omitempty"`                        // 毫秒
	OnlineKey           string `protobuf:"bytes,6,opt,name=online_key,json=onlineKey,proto3" json:"online_key,omitempty"`                                 // 用于定位当前 online
	ExpireSecond        uint64 `protobuf:"varint,7,opt,name=expire_second,json=expireSecond,proto3" json:"expire_second,omitempty"`                       // 单位为秒
}

func (x *CacheBeginUserSessionCASReq) Reset() {
	*x = CacheBeginUserSessionCASReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheBeginUserSessionCASReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheBeginUserSessionCASReq) ProtoMessage() {}

func (x *CacheBeginUserSessionCASReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheBeginUserSessionCASReq.ProtoReflect.Descriptor instead.
func (*CacheBeginUserSessionCASReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *CacheBeginUserSessionCASReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheBeginUserSessionCASReq) GetExpectedUserSession() string {
	if x != nil {
		return x.ExpectedUserSession
	}
	return ""
}

func (x *CacheBeginUserSessionCASReq) GetGatewayKey() string {
	if x != nil {
		return x.GatewayKey
	}
	return ""
}

func (x *CacheBeginUserSessionCASReq) GetUserSession() string {
	if x != nil {
		return x.UserSession
	}
	return ""
}

func (x *CacheBeginUserSessionCASReq) GetLoginTimeMs() int64 {
	if x != nil {
		return x.LoginTimeMs
	}
	return 0
}

func (x *CacheBeginUserSessionCASReq) GetOnlineKey() string {
	if x != nil {
		return x.OnlineKey
	}
	return ""
}

func (x *CacheBeginUserSessionCASReq) GetExpireSecond() uint64 {
	if x != nil {
		return x.ExpireSecond
	}
	return 0
}

type CacheBeginUserSessionCASRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheBeginUserSessionCASRes) Reset() {
	*x = CacheBeginUserSessionCASRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheBeginUserSessionCASRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheBeginUserSessionCASRes) ProtoMessage() {}

func (x *CacheBeginUserSessionCASRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheBeginUserSessionCASRes.ProtoReflect.Descriptor instead.
func (*CacheBeginUserSessionCASRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{12}
}

type CacheEndUserSessionCASReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid                 uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ExpectedUserSession string `protobuf:"bytes,2,opt,name=expected_user_session,json=expectedUserSession,proto3" json:"expected_user_session,omitempty"` // 用于 CAS 删除前匹配当前 session
}

func (x *CacheEndUserSessionCASReq) Reset() {
	*x = CacheEndUserSessionCASReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheEndUserSessionCASReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEndUserSessionCASReq) ProtoMessage() {}

func (x *CacheEndUserSessionCASReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEndUserSessionCASReq.ProtoReflect.Descriptor instead.
func (*CacheEndUserSessionCASReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *CacheEndUserSessionCASReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheEndUserSessionCASReq) GetExpectedUserSession() string {
	if x != nil {
		return x.ExpectedUserSession
	}
	return ""
}

type CacheEndUserSessionCASRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheEndUserSessionCASRes) Reset() {
	*x = CacheEndUserSessionCASRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheEndUserSessionCASRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheEndUserSessionCASRes) ProtoMessage() {}

func (x *CacheEndUserSessionCASRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheEndUserSessionCASRes.ProtoReflect.Descriptor instead.
func (*CacheEndUserSessionCASRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{14}
}

type CacheRefreshUserSessionCASReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid                 uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ExpectedUserSession string `protobuf:"bytes,2,opt,name=expected_user_session,json=expectedUserSession,proto3" json:"expected_user_session,omitempty"` // 用于 CAS 续期前匹配当前 session
	ExpireSecond        uint64 `protobuf:"varint,3,opt,name=expire_second,json=expireSecond,proto3" json:"expire_second,omitempty"`                       // 单位为秒
}

func (x *CacheRefreshUserSessionCASReq) Reset() {
	*x = CacheRefreshUserSessionCASReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheRefreshUserSessionCASReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRefreshUserSessionCASReq) ProtoMessage() {}

func (x *CacheRefreshUserSessionCASReq) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRefreshUserSessionCASReq.ProtoReflect.Descriptor instead.
func (*CacheRefreshUserSessionCASReq) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{15}
}

func (x *CacheRefreshUserSessionCASReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CacheRefreshUserSessionCASReq) GetExpectedUserSession() string {
	if x != nil {
		return x.ExpectedUserSession
	}
	return ""
}

func (x *CacheRefreshUserSessionCASReq) GetExpireSecond() uint64 {
	if x != nil {
		return x.ExpireSecond
	}
	return 0
}

type CacheRefreshUserSessionCASRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CacheRefreshUserSessionCASRes) Reset() {
	*x = CacheRefreshUserSessionCASRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cache_grpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CacheRefreshUserSessionCASRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheRefreshUserSessionCASRes) ProtoMessage() {}

func (x *CacheRefreshUserSessionCASRes) ProtoReflect() protoreflect.Message {
	mi := &file_cache_grpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheRefreshUserSessionCASRes.ProtoReflect.Descriptor instead.
func (*CacheRefreshUserSessionCASRes) Descriptor() ([]byte, []int) {
	return file_cache_grpc_proto_rawDescGZIP(), []int{16}
}

var File_cache_grpc_proto protoreflect.FileDescriptor

var file_cache_grpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x1a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x15, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x31, 0x0a,
	0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x22, 0x17, 0x0a, 0x15, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x15, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42,
	0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x4a, 0x0a, 0x15, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x75, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22, 0x7b, 0x0a, 0x1d, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x23, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x56, 0x0a, 0x1d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73,
	0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x31, 0x0a,
	0x1d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x22, 0x99, 0x01, 0x0a, 0x10, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x31, 0x0a, 0x16,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22,
	0x4b, 0x0a, 0x16, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x96, 0x02, 0x0a,
	0x1b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50, 0x01,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a,
	0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x4d,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41,
	0x53, 0x52, 0x65, 0x73, 0x22, 0x68, 0x0a, 0x19, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05,
	0xc2, 0x3e, 0x02, 0x50, 0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x65, 0x78,
	0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65, 0x78, 0x70, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x1b,
	0x0a, 0x19, 0x43, 0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x1d,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xc2, 0x3e, 0x02, 0x50,
	0x01, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22,
	0x1f, 0x0a, 0x1d, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x73,
	0x32, 0xf3, 0x06, 0x0a, 0x0c, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x5c, 0x0a, 0x12, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12,
	0x5c, 0x0a, 0x12, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x74, 0x0a,
	0x1a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x2e, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x24, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x53,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73,
	0xf0, 0x01, 0x01, 0x12, 0x74, 0x0a, 0x1a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x24, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55,
	0x73, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x73, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2,
	0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x01, 0x12, 0x5f, 0x0a, 0x13, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1d, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a,
	0x1d, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x0a,
	0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x6e, 0x0a, 0x18, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x73, 0x22, 0x0a,
	0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x12, 0x68, 0x0a, 0x16, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x45, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x43, 0x41, 0x53, 0x12, 0x20, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x45, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x43, 0x41, 0x53, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x45, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x73, 0x22, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33,
	0x73, 0xf0, 0x01, 0x05, 0x12, 0x74, 0x0a, 0x1a, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x41, 0x53, 0x12, 0x24, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x41, 0x53, 0x52, 0x65, 0x73, 0x22, 0x0a,
	0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xf0, 0x01, 0x05, 0x1a, 0x0a, 0xc2, 0x3e, 0x07, 0x52,
	0x02, 0x33, 0x73, 0xa0, 0x01, 0x05, 0x42, 0x14, 0x5a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cache_grpc_proto_rawDescOnce sync.Once
	file_cache_grpc_proto_rawDescData = file_cache_grpc_proto_rawDesc
)

func file_cache_grpc_proto_rawDescGZIP() []byte {
	file_cache_grpc_proto_rawDescOnce.Do(func() {
		file_cache_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_cache_grpc_proto_rawDescData)
	})
	return file_cache_grpc_proto_rawDescData
}

var file_cache_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_cache_grpc_proto_goTypes = []any{
	(*CacheSetUserRecordReq)(nil),         // 0: cache.CacheSetUserRecordReq
	(*CacheSetUserRecordRes)(nil),         // 1: cache.CacheSetUserRecordRes
	(*CacheGetUserRecordReq)(nil),         // 2: cache.CacheGetUserRecordReq
	(*CacheGetUserRecordRes)(nil),         // 3: cache.CacheGetUserRecordRes
	(*CacheSetAccountVerifyTokenReq)(nil), // 4: cache.CacheSetAccountVerifyTokenReq
	(*CacheSetAccountVerifyTokenRes)(nil), // 5: cache.CacheSetAccountVerifyTokenRes
	(*CacheUseAccountVerifyTokenReq)(nil), // 6: cache.CacheUseAccountVerifyTokenReq
	(*CacheUseAccountVerifyTokenRes)(nil), // 7: cache.CacheUseAccountVerifyTokenRes
	(*CacheUserSession)(nil),              // 8: cache.CacheUserSession
	(*CacheGetUserSessionReq)(nil),        // 9: cache.CacheGetUserSessionReq
	(*CacheGetUserSessionRes)(nil),        // 10: cache.CacheGetUserSessionRes
	(*CacheBeginUserSessionCASReq)(nil),   // 11: cache.CacheBeginUserSessionCASReq
	(*CacheBeginUserSessionCASRes)(nil),   // 12: cache.CacheBeginUserSessionCASRes
	(*CacheEndUserSessionCASReq)(nil),     // 13: cache.CacheEndUserSessionCASReq
	(*CacheEndUserSessionCASRes)(nil),     // 14: cache.CacheEndUserSessionCASRes
	(*CacheRefreshUserSessionCASReq)(nil), // 15: cache.CacheRefreshUserSessionCASReq
	(*CacheRefreshUserSessionCASRes)(nil), // 16: cache.CacheRefreshUserSessionCASRes
	(*UserRecord)(nil),                    // 17: user.UserRecord
}
var file_cache_grpc_proto_depIdxs = []int32{
	17, // 0: cache.CacheSetUserRecordReq.user_record:type_name -> user.UserRecord
	17, // 1: cache.CacheGetUserRecordRes.user_record:type_name -> user.UserRecord
	8,  // 2: cache.CacheGetUserSessionRes.session:type_name -> cache.CacheUserSession
	0,  // 3: cache.CacheService.CacheSetUserRecord:input_type -> cache.CacheSetUserRecordReq
	2,  // 4: cache.CacheService.CacheGetUserRecord:input_type -> cache.CacheGetUserRecordReq
	4,  // 5: cache.CacheService.CacheSetAccountVerifyToken:input_type -> cache.CacheSetAccountVerifyTokenReq
	6,  // 6: cache.CacheService.CacheUseAccountVerifyToken:input_type -> cache.CacheUseAccountVerifyTokenReq
	9,  // 7: cache.CacheService.CacheGetUserSession:input_type -> cache.CacheGetUserSessionReq
	11, // 8: cache.CacheService.CacheBeginUserSessionCAS:input_type -> cache.CacheBeginUserSessionCASReq
	13, // 9: cache.CacheService.CacheEndUserSessionCAS:input_type -> cache.CacheEndUserSessionCASReq
	15, // 10: cache.CacheService.CacheRefreshUserSessionCAS:input_type -> cache.CacheRefreshUserSessionCASReq
	1,  // 11: cache.CacheService.CacheSetUserRecord:output_type -> cache.CacheSetUserRecordRes
	3,  // 12: cache.CacheService.CacheGetUserRecord:output_type -> cache.CacheGetUserRecordRes
	5,  // 13: cache.CacheService.CacheSetAccountVerifyToken:output_type -> cache.CacheSetAccountVerifyTokenRes
	7,  // 14: cache.CacheService.CacheUseAccountVerifyToken:output_type -> cache.CacheUseAccountVerifyTokenRes
	10, // 15: cache.CacheService.CacheGetUserSession:output_type -> cache.CacheGetUserSessionRes
	12, // 16: cache.CacheService.CacheBeginUserSessionCAS:output_type -> cache.CacheBeginUserSessionCASRes
	14, // 17: cache.CacheService.CacheEndUserSessionCAS:output_type -> cache.CacheEndUserSessionCASRes
	16, // 18: cache.CacheService.CacheRefreshUserSessionCAS:output_type -> cache.CacheRefreshUserSessionCASRes
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_cache_grpc_proto_init() }
func file_cache_grpc_proto_init() {
	if File_cache_grpc_proto != nil {
		return
	}
	file_user_record_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cache_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetUserRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetUserRecordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetUserRecordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetUserRecordRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetAccountVerifyTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CacheSetAccountVerifyTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CacheUseAccountVerifyTokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CacheUseAccountVerifyTokenRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CacheUserSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetUserSessionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CacheGetUserSessionRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*CacheBeginUserSessionCASReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*CacheBeginUserSessionCASRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CacheEndUserSessionCASReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*CacheEndUserSessionCASRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*CacheRefreshUserSessionCASReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cache_grpc_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*CacheRefreshUserSessionCASRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cache_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_grpc_proto_goTypes,
		DependencyIndexes: file_cache_grpc_proto_depIdxs,
		MessageInfos:      file_cache_grpc_proto_msgTypes,
	}.Build()
	File_cache_grpc_proto = out.File
	file_cache_grpc_proto_rawDesc = nil
	file_cache_grpc_proto_goTypes = nil
	file_cache_grpc_proto_depIdxs = nil
}
