// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: combat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CombatEnemyGroupEnemyCountRange int32

const (
	CombatEnemyGroupEnemyCountRange_CombatEnemyGroupEnemyCountRange_Unknow CombatEnemyGroupEnemyCountRange = 0
	CombatEnemyGroupEnemyCountRange_CombatEnemyGroupEnemyCountRange_Min    CombatEnemyGroupEnemyCountRange = 1
	CombatEnemyGroupEnemyCountRange_CombatEnemyGroupEnemyCountRange_Max    CombatEnemyGroupEnemyCountRange = 10
)

// Enum value maps for CombatEnemyGroupEnemyCountRange.
var (
	CombatEnemyGroupEnemyCountRange_name = map[int32]string{
		0:  "CombatEnemyGroupEnemyCountRange_Unknow",
		1:  "CombatEnemyGroupEnemyCountRange_Min",
		10: "CombatEnemyGroupEnemyCountRange_Max",
	}
	CombatEnemyGroupEnemyCountRange_value = map[string]int32{
		"CombatEnemyGroupEnemyCountRange_Unknow": 0,
		"CombatEnemyGroupEnemyCountRange_Min":    1,
		"CombatEnemyGroupEnemyCountRange_Max":    10,
	}
)

func (x CombatEnemyGroupEnemyCountRange) Enum() *CombatEnemyGroupEnemyCountRange {
	p := new(CombatEnemyGroupEnemyCountRange)
	*p = x
	return p
}

func (x CombatEnemyGroupEnemyCountRange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombatEnemyGroupEnemyCountRange) Descriptor() protoreflect.EnumDescriptor {
	return file_combat_proto_enumTypes[0].Descriptor()
}

func (CombatEnemyGroupEnemyCountRange) Type() protoreflect.EnumType {
	return &file_combat_proto_enumTypes[0]
}

func (x CombatEnemyGroupEnemyCountRange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombatEnemyGroupEnemyCountRange.Descriptor instead.
func (CombatEnemyGroupEnemyCountRange) EnumDescriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{0}
}

type CombatEnemyGroupBabyRate int32

const (
	CombatEnemyGroupBabyRate_CombatEnemyGroupBabyRate_Min CombatEnemyGroupBabyRate = 0
	CombatEnemyGroupBabyRate_CombatEnemyGroupBabyRate_Max CombatEnemyGroupBabyRate = 100000
)

// Enum value maps for CombatEnemyGroupBabyRate.
var (
	CombatEnemyGroupBabyRate_name = map[int32]string{
		0:      "CombatEnemyGroupBabyRate_Min",
		100000: "CombatEnemyGroupBabyRate_Max",
	}
	CombatEnemyGroupBabyRate_value = map[string]int32{
		"CombatEnemyGroupBabyRate_Min": 0,
		"CombatEnemyGroupBabyRate_Max": 100000,
	}
)

func (x CombatEnemyGroupBabyRate) Enum() *CombatEnemyGroupBabyRate {
	p := new(CombatEnemyGroupBabyRate)
	*p = x
	return p
}

func (x CombatEnemyGroupBabyRate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombatEnemyGroupBabyRate) Descriptor() protoreflect.EnumDescriptor {
	return file_combat_proto_enumTypes[1].Descriptor()
}

func (CombatEnemyGroupBabyRate) Type() protoreflect.EnumType {
	return &file_combat_proto_enumTypes[1]
}

func (x CombatEnemyGroupBabyRate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombatEnemyGroupBabyRate.Descriptor instead.
func (CombatEnemyGroupBabyRate) EnumDescriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{1}
}

type CombatCamp int32

const (
	CombatCamp_CombatCamp_Initiator CombatCamp = 0
	CombatCamp_CombatCamp_Defender  CombatCamp = 1
)

// Enum value maps for CombatCamp.
var (
	CombatCamp_name = map[int32]string{
		0: "CombatCamp_Initiator",
		1: "CombatCamp_Defender",
	}
	CombatCamp_value = map[string]int32{
		"CombatCamp_Initiator": 0,
		"CombatCamp_Defender":  1,
	}
)

func (x CombatCamp) Enum() *CombatCamp {
	p := new(CombatCamp)
	*p = x
	return p
}

func (x CombatCamp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombatCamp) Descriptor() protoreflect.EnumDescriptor {
	return file_combat_proto_enumTypes[2].Descriptor()
}

func (CombatCamp) Type() protoreflect.EnumType {
	return &file_combat_proto_enumTypes[2]
}

func (x CombatCamp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombatCamp.Descriptor instead.
func (CombatCamp) EnumDescriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{2}
}

type CombatCampPosition int32

const (
	CombatCampPosition_CombatCampPosition_Unknow CombatCampPosition = 0
	CombatCampPosition_CombatCampPosition_Count  CombatCampPosition = 10
)

// Enum value maps for CombatCampPosition.
var (
	CombatCampPosition_name = map[int32]string{
		0:  "CombatCampPosition_Unknow",
		10: "CombatCampPosition_Count",
	}
	CombatCampPosition_value = map[string]int32{
		"CombatCampPosition_Unknow": 0,
		"CombatCampPosition_Count":  10,
	}
)

func (x CombatCampPosition) Enum() *CombatCampPosition {
	p := new(CombatCampPosition)
	*p = x
	return p
}

func (x CombatCampPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombatCampPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_combat_proto_enumTypes[3].Descriptor()
}

func (CombatCampPosition) Type() protoreflect.EnumType {
	return &file_combat_proto_enumTypes[3]
}

func (x CombatCampPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombatCampPosition.Descriptor instead.
func (CombatCampPosition) EnumDescriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{3}
}

type CombatUnitKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountUid    uint64 `protobuf:"varint,1,opt,name=account_uid,json=accountUid,proto3" json:"account_uid,omitempty"`          // 账号 uid; 玩家单位为 AccountRecord.uid, 怪物/NPC 为 0
	CharacterUuid uint64 `protobuf:"varint,2,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 角色 UUID; 玩家单位为所属角色 UUID, 怪物/NPC 为 0
	PetUuid       uint64 `protobuf:"varint,3,opt,name=pet_uuid,json=petUuid,proto3" json:"pet_uuid,omitempty"`                   // 宠物 UUID; 玩家宠物单位为宠物 UUID, 角色单位为 0, 怪物/NPC 为本场战斗临时唯一 ID
}

func (x *CombatUnitKey) Reset() {
	*x = CombatUnitKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatUnitKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatUnitKey) ProtoMessage() {}

func (x *CombatUnitKey) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatUnitKey.ProtoReflect.Descriptor instead.
func (*CombatUnitKey) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{0}
}

func (x *CombatUnitKey) GetAccountUid() uint64 {
	if x != nil {
		return x.AccountUid
	}
	return 0
}

func (x *CombatUnitKey) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CombatUnitKey) GetPetUuid() uint64 {
	if x != nil {
		return x.PetUuid
	}
	return 0
}

type CombatUnitAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exp     uint64 `protobuf:"varint,1,opt,name=exp,proto3" json:"exp,omitempty"`         // 当前经验值, 客户端按配置规则推导等级
	Hp      uint64 `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`           // 当前生命值
	Attack  uint64 `protobuf:"varint,3,opt,name=attack,proto3" json:"attack,omitempty"`   // 攻击力
	Defense uint64 `protobuf:"varint,4,opt,name=defense,proto3" json:"defense,omitempty"` // 防御力
	Agility uint64 `protobuf:"varint,5,opt,name=agility,proto3" json:"agility,omitempty"` // 敏捷
	Loyalty uint64 `protobuf:"varint,6,opt,name=loyalty,proto3" json:"loyalty,omitempty"` // 忠诚度, 非宠物单位为 0
}

func (x *CombatUnitAttribute) Reset() {
	*x = CombatUnitAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatUnitAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatUnitAttribute) ProtoMessage() {}

func (x *CombatUnitAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatUnitAttribute.ProtoReflect.Descriptor instead.
func (*CombatUnitAttribute) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{1}
}

func (x *CombatUnitAttribute) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *CombatUnitAttribute) GetHp() uint64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CombatUnitAttribute) GetAttack() uint64 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *CombatUnitAttribute) GetDefense() uint64 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *CombatUnitAttribute) GetAgility() uint64 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *CombatUnitAttribute) GetLoyalty() uint64 {
	if x != nil {
		return x.Loyalty
	}
	return 0
}

type CombatEquipmentBind struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipmentId uint32 `protobuf:"varint,1,opt,name=equipment_id,json=equipmentId,proto3" json:"equipment_id,omitempty"` // 装备资源 ID
}

func (x *CombatEquipmentBind) Reset() {
	*x = CombatEquipmentBind{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatEquipmentBind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatEquipmentBind) ProtoMessage() {}

func (x *CombatEquipmentBind) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatEquipmentBind.ProtoReflect.Descriptor instead.
func (*CombatEquipmentBind) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{2}
}

func (x *CombatEquipmentBind) GetEquipmentId() uint32 {
	if x != nil {
		return x.EquipmentId
	}
	return 0
}

type CombatUnit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Camp          CombatCamp             `protobuf:"varint,1,opt,name=camp,proto3,enum=user.CombatCamp" json:"camp,omitempty"`                   // 所属阵营
	Position      uint32                 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`                                // 阵营内站位槽位, 只表示阵型/显示位置, 不参与单位身份
	Key           *CombatUnitKey         `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`                                           // 战斗单位身份 key; 玩家单位由 account_uid + character_uuid + pet_uuid 唯一确定
	CharacterId   uint32                 `protobuf:"varint,10,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`      // 角色资源 ID; 怪物/NPC 为 0
	PetId         uint32                 `protobuf:"varint,11,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`                        // 宠物或怪物资源 ID; 纯角色单位为 0
	MountPetId    uint32                 `protobuf:"varint,13,opt,name=mount_pet_id,json=mountPetId,proto3" json:"mount_pet_id,omitempty"`       // 骑宠资源 ID; 没有骑宠时为 0
	Attribute     *CombatUnitAttribute   `protobuf:"bytes,20,opt,name=attribute,proto3" json:"attribute,omitempty"`                              // 开战时可见战斗属性快照
	EquipmentList []*CombatEquipmentBind `protobuf:"bytes,30,rep,name=equipment_list,json=equipmentList,proto3" json:"equipment_list,omitempty"` // 开战时可见装备绑定列表
}

func (x *CombatUnit) Reset() {
	*x = CombatUnit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatUnit) ProtoMessage() {}

func (x *CombatUnit) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatUnit.ProtoReflect.Descriptor instead.
func (*CombatUnit) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{3}
}

func (x *CombatUnit) GetCamp() CombatCamp {
	if x != nil {
		return x.Camp
	}
	return CombatCamp_CombatCamp_Initiator
}

func (x *CombatUnit) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CombatUnit) GetKey() *CombatUnitKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CombatUnit) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CombatUnit) GetPetId() uint32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *CombatUnit) GetMountPetId() uint32 {
	if x != nil {
		return x.MountPetId
	}
	return 0
}

func (x *CombatUnit) GetAttribute() *CombatUnitAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *CombatUnit) GetEquipmentList() []*CombatEquipmentBind {
	if x != nil {
		return x.EquipmentList
	}
	return nil
}

type CombatBattleStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId uint64        `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"` // 战斗唯一 ID
	UnitList []*CombatUnit `protobuf:"bytes,10,rep,name=unit_list,json=unitList,proto3" json:"unit_list,omitempty"` // 开战时场上可见单位列表
}

func (x *CombatBattleStart) Reset() {
	*x = CombatBattleStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_combat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombatBattleStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatBattleStart) ProtoMessage() {}

func (x *CombatBattleStart) ProtoReflect() protoreflect.Message {
	mi := &file_combat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatBattleStart.ProtoReflect.Descriptor instead.
func (*CombatBattleStart) Descriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{4}
}

func (x *CombatBattleStart) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *CombatBattleStart) GetUnitList() []*CombatUnit {
	if x != nil {
		return x.UnitList
	}
	return nil
}

var File_combat_proto protoreflect.FileDescriptor

var file_combat_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x22, 0x72, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e,
	0x69, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x55, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x65, 0x74, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x70, 0x65, 0x74, 0x55, 0x75, 0x69, 0x64, 0x22, 0x9d, 0x01, 0x0a, 0x13, 0x43, 0x6f, 0x6d,
	0x62, 0x61, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x65,
	0x78, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x68, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65,
	0x66, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x64, 0x65, 0x66,
	0x65, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x67, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x6c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79, 0x22, 0x38, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x62,
	0x61, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x69, 0x6e, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x22, 0xcc, 0x02, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e, 0x69,
	0x74, 0x12, 0x24, 0x0a, 0x04, 0x63, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x43, 0x61, 0x6d,
	0x70, 0x52, 0x04, 0x63, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e,
	0x69, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x70, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70,
	0x65, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x65,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x50, 0x65, 0x74, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12,
	0x40, 0x0a, 0x0e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x1e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43,
	0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x69,
	0x6e, 0x64, 0x52, 0x0d, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x5f, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x6f,
	0x6d, 0x62, 0x61, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x2a, 0x9f, 0x01, 0x0a, 0x1f, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e, 0x65,
	0x6d, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x26, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74,
	0x45, 0x6e, 0x65, 0x6d, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x10, 0x00, 0x12, 0x27, 0x0a, 0x23, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e, 0x65, 0x6d,
	0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x4d, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x27, 0x0a, 0x23, 0x43,
	0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45,
	0x6e, 0x65, 0x6d, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x4d,
	0x61, 0x78, 0x10, 0x0a, 0x2a, 0x60, 0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e,
	0x65, 0x6d, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x61, 0x62, 0x79, 0x52, 0x61, 0x74, 0x65,
	0x12, 0x20, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x42, 0x61, 0x62, 0x79, 0x52, 0x61, 0x74, 0x65, 0x5f, 0x4d, 0x69, 0x6e,
	0x10, 0x00, 0x12, 0x22, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e, 0x65, 0x6d,
	0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x61, 0x62, 0x79, 0x52, 0x61, 0x74, 0x65, 0x5f, 0x4d,
	0x61, 0x78, 0x10, 0xa0, 0x8d, 0x06, 0x2a, 0x3f, 0x0a, 0x0a, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74,
	0x43, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x43, 0x61,
	0x6d, 0x70, 0x5f, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x10, 0x00, 0x12, 0x17,
	0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x5f, 0x44, 0x65, 0x66,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x10, 0x01, 0x2a, 0x51, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x62, 0x61,
	0x74, 0x43, 0x61, 0x6d, 0x70, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a,
	0x19, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18,
	0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x0a, 0x42, 0x14, 0x5a, 0x12, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_combat_proto_rawDescOnce sync.Once
	file_combat_proto_rawDescData = file_combat_proto_rawDesc
)

func file_combat_proto_rawDescGZIP() []byte {
	file_combat_proto_rawDescOnce.Do(func() {
		file_combat_proto_rawDescData = protoimpl.X.CompressGZIP(file_combat_proto_rawDescData)
	})
	return file_combat_proto_rawDescData
}

var file_combat_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_combat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_combat_proto_goTypes = []any{
	(CombatEnemyGroupEnemyCountRange)(0), // 0: user.CombatEnemyGroupEnemyCountRange
	(CombatEnemyGroupBabyRate)(0),        // 1: user.CombatEnemyGroupBabyRate
	(CombatCamp)(0),                      // 2: user.CombatCamp
	(CombatCampPosition)(0),              // 3: user.CombatCampPosition
	(*CombatUnitKey)(nil),                // 4: user.CombatUnitKey
	(*CombatUnitAttribute)(nil),          // 5: user.CombatUnitAttribute
	(*CombatEquipmentBind)(nil),          // 6: user.CombatEquipmentBind
	(*CombatUnit)(nil),                   // 7: user.CombatUnit
	(*CombatBattleStart)(nil),            // 8: user.CombatBattleStart
}
var file_combat_proto_depIdxs = []int32{
	2, // 0: user.CombatUnit.camp:type_name -> user.CombatCamp
	4, // 1: user.CombatUnit.key:type_name -> user.CombatUnitKey
	5, // 2: user.CombatUnit.attribute:type_name -> user.CombatUnitAttribute
	6, // 3: user.CombatUnit.equipment_list:type_name -> user.CombatEquipmentBind
	7, // 4: user.CombatBattleStart.unit_list:type_name -> user.CombatUnit
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_combat_proto_init() }
func file_combat_proto_init() {
	if File_combat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_combat_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CombatUnitKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combat_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CombatUnitAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combat_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CombatEquipmentBind); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combat_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CombatUnit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_combat_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CombatBattleStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_combat_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_combat_proto_goTypes,
		DependencyIndexes: file_combat_proto_depIdxs,
		EnumInfos:         file_combat_proto_enumTypes,
		MessageInfos:      file_combat_proto_msgTypes,
	}.Build()
	File_combat_proto = out.File
	file_combat_proto_rawDesc = nil
	file_combat_proto_goTypes = nil
	file_combat_proto_depIdxs = nil
}
