// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: gateway.grpc.proto

package pb

import (
	_ "github.com/75912001/xlib/grpc/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayKickUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid         uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`                                   // 已登录用户 uid；gateway 先从 byUID 查找，再校验 userSession
	Reason      uint32 `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`                             // 离线原因码
	Msg         string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`                                    // 离线说明
	UserSession string `protobuf:"bytes,4,opt,name=user_session,json=userSession,proto3" json:"user_session,omitempty"` // 固定连接身份，只断开匹配的连接
}

func (x *GatewayKickUserReq) Reset() {
	*x = GatewayKickUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayKickUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKickUserReq) ProtoMessage() {}

func (x *GatewayKickUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKickUserReq.ProtoReflect.Descriptor instead.
func (*GatewayKickUserReq) Descriptor() ([]byte, []int) {
	return file_gateway_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayKickUserReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GatewayKickUserReq) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *GatewayKickUserReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GatewayKickUserReq) GetUserSession() string {
	if x != nil {
		return x.UserSession
	}
	return ""
}

type GatewayKickUserRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GatewayKickUserRes) Reset() {
	*x = GatewayKickUserRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayKickUserRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayKickUserRes) ProtoMessage() {}

func (x *GatewayKickUserRes) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayKickUserRes.ProtoReflect.Descriptor instead.
func (*GatewayKickUserRes) Descriptor() ([]byte, []int) {
	return file_gateway_grpc_proto_rawDescGZIP(), []int{1}
}

var File_gateway_grpc_proto protoreflect.FileDescriptor

var file_gateway_grpc_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x1a, 0x0d, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x73, 0x0a, 0x12,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x21,
	0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x32, 0x73, 0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x0f, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x69,
	0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4b, 0x69, 0x63, 0x6b, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x22, 0x08, 0xc2, 0x3e, 0x05, 0x52, 0x03, 0x36, 0x30, 0x73,
	0x1a, 0x0a, 0xc2, 0x3e, 0x07, 0x52, 0x02, 0x33, 0x73, 0xa0, 0x01, 0x06, 0x42, 0x14, 0x5a, 0x12,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_grpc_proto_rawDescOnce sync.Once
	file_gateway_grpc_proto_rawDescData = file_gateway_grpc_proto_rawDesc
)

func file_gateway_grpc_proto_rawDescGZIP() []byte {
	file_gateway_grpc_proto_rawDescOnce.Do(func() {
		file_gateway_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_grpc_proto_rawDescData)
	})
	return file_gateway_grpc_proto_rawDescData
}

var file_gateway_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_grpc_proto_goTypes = []any{
	(*GatewayKickUserReq)(nil), // 0: gateway.GatewayKickUserReq
	(*GatewayKickUserRes)(nil), // 1: gateway.GatewayKickUserRes
}
var file_gateway_grpc_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayService.GatewayKickUser:input_type -> gateway.GatewayKickUserReq
	1, // 1: gateway.GatewayService.GatewayKickUser:output_type -> gateway.GatewayKickUserRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_grpc_proto_init() }
func file_gateway_grpc_proto_init() {
	if File_gateway_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GatewayKickUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GatewayKickUserRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_grpc_proto_goTypes,
		DependencyIndexes: file_gateway_grpc_proto_depIdxs,
		MessageInfos:      file_gateway_grpc_proto_msgTypes,
	}.Build()
	File_gateway_grpc_proto = out.File
	file_gateway_grpc_proto_rawDesc = nil
	file_gateway_grpc_proto_goTypes = nil
	file_gateway_grpc_proto_depIdxs = nil
}
