// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: msg.mail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MailRecord 表示角色邮箱中的一封系统邮件.
type MailRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid              uint64 `protobuf:"varint,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                                      // 邮箱内单调递增且不复用的邮件 UUID
	Title             string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                                                     // 去除首尾空白后的纯文本主题
	Content           string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                                                 // 统一换行为 LF 的纯文本正文
	CreateTimestampMs int64  `protobuf:"varint,4,opt,name=create_timestamp_ms,json=createTimestampMs,proto3" json:"create_timestamp_ms,omitempty"` // Cache 写入邮件时生成的 Unix 毫秒时间戳
	ExpireTimestampMs int64  `protobuf:"varint,5,opt,name=expire_timestamp_ms,json=expireTimestampMs,proto3" json:"expire_timestamp_ms,omitempty"` // 邮件过期的 Unix 毫秒时间戳, now >= 此值即过期
	IsRead            bool   `protobuf:"varint,6,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`                                    // 是否已经成功标记为已读
}

func (x *MailRecord) Reset() {
	*x = MailRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailRecord) ProtoMessage() {}

func (x *MailRecord) ProtoReflect() protoreflect.Message {
	mi := &file_msg_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailRecord.ProtoReflect.Descriptor instead.
func (*MailRecord) Descriptor() ([]byte, []int) {
	return file_msg_mail_proto_rawDescGZIP(), []int{0}
}

func (x *MailRecord) GetUuid() uint64 {
	if x != nil {
		return x.Uuid
	}
	return 0
}

func (x *MailRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MailRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MailRecord) GetCreateTimestampMs() int64 {
	if x != nil {
		return x.CreateTimestampMs
	}
	return 0
}

func (x *MailRecord) GetExpireTimestampMs() int64 {
	if x != nil {
		return x.ExpireTimestampMs
	}
	return 0
}

func (x *MailRecord) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

// MailboxRecord 表示单个角色完整邮箱快照.
type MailboxRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsedUuid      uint64                 `protobuf:"varint,1,opt,name=used_uuid,json=usedUuid,proto3" json:"used_uuid,omitempty"`                                                                                                          // 已分配过的最大邮件 UUID, 只增不减且不复用
	MailRecordMap map[uint64]*MailRecord `protobuf:"bytes,2,rep,name=mail_record_map,json=mailRecordMap,proto3" json:"mail_record_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // key 必须与 MailRecord.uuid 一致
}

func (x *MailboxRecord) Reset() {
	*x = MailboxRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailboxRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxRecord) ProtoMessage() {}

func (x *MailboxRecord) ProtoReflect() protoreflect.Message {
	mi := &file_msg_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxRecord.ProtoReflect.Descriptor instead.
func (*MailboxRecord) Descriptor() ([]byte, []int) {
	return file_msg_mail_proto_rawDescGZIP(), []int{1}
}

func (x *MailboxRecord) GetUsedUuid() uint64 {
	if x != nil {
		return x.UsedUuid
	}
	return 0
}

func (x *MailboxRecord) GetMailRecordMap() map[uint64]*MailRecord {
	if x != nil {
		return x.MailRecordMap
	}
	return nil
}

// 0x005000#client->gateway#获取角色邮箱-请求
type CharacterMailboxGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 当前账号内已上线的角色 UUID
}

func (x *CharacterMailboxGetReq) Reset() {
	*x = CharacterMailboxGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterMailboxGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMailboxGetReq) ProtoMessage() {}

func (x *CharacterMailboxGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMailboxGetReq.ProtoReflect.Descriptor instead.
func (*CharacterMailboxGetReq) Descriptor() ([]byte, []int) {
	return file_msg_mail_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterMailboxGetReq) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

// 0x005001#gateway->client#获取角色邮箱-回复
type CharacterMailboxGetRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64         `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 已加载邮箱的角色 UUID
	MailboxRecord *MailboxRecord `protobuf:"bytes,2,opt,name=mailbox_record,json=mailboxRecord,proto3" json:"mailbox_record,omitempty"`  // 清理过期邮件后的完整邮箱快照
}

func (x *CharacterMailboxGetRes) Reset() {
	*x = CharacterMailboxGetRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_mail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterMailboxGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMailboxGetRes) ProtoMessage() {}

func (x *CharacterMailboxGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_msg_mail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMailboxGetRes.ProtoReflect.Descriptor instead.
func (*CharacterMailboxGetRes) Descriptor() ([]byte, []int) {
	return file_msg_mail_proto_rawDescGZIP(), []int{3}
}

func (x *CharacterMailboxGetRes) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CharacterMailboxGetRes) GetMailboxRecord() *MailboxRecord {
	if x != nil {
		return x.MailboxRecord
	}
	return nil
}

// 0x005002#client->gateway#标记角色邮件已读-请求
type CharacterMailReadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 当前账号内已上线的角色 UUID
	MailUuid      uint64 `protobuf:"varint,2,opt,name=mail_uuid,json=mailUuid,proto3" json:"mail_uuid,omitempty"`                // 要标记为已读的邮件 UUID
}

func (x *CharacterMailReadReq) Reset() {
	*x = CharacterMailReadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_mail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterMailReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMailReadReq) ProtoMessage() {}

func (x *CharacterMailReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_mail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMailReadReq.ProtoReflect.Descriptor instead.
func (*CharacterMailReadReq) Descriptor() ([]byte, []int) {
	return file_msg_mail_proto_rawDescGZIP(), []int{4}
}

func (x *CharacterMailReadReq) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CharacterMailReadReq) GetMailUuid() uint64 {
	if x != nil {
		return x.MailUuid
	}
	return 0
}

// 0x005003#gateway->client#标记角色邮件已读-回复
type CharacterMailReadRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 已操作邮件所属的角色 UUID
	MailUuid      uint64 `protobuf:"varint,2,opt,name=mail_uuid,json=mailUuid,proto3" json:"mail_uuid,omitempty"`                // 已标记为已读的邮件 UUID
}

func (x *CharacterMailReadRes) Reset() {
	*x = CharacterMailReadRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_mail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterMailReadRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMailReadRes) ProtoMessage() {}

func (x *CharacterMailReadRes) ProtoReflect() protoreflect.Message {
	mi := &file_msg_mail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMailReadRes.ProtoReflect.Descriptor instead.
func (*CharacterMailReadRes) Descriptor() ([]byte, []int) {
	return file_msg_mail_proto_rawDescGZIP(), []int{5}
}

func (x *CharacterMailReadRes) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CharacterMailReadRes) GetMailUuid() uint64 {
	if x != nil {
		return x.MailUuid
	}
	return 0
}

// 0x005004#client->gateway#删除角色邮件-请求
type CharacterMailDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 当前账号内已上线的角色 UUID
	MailUuid      uint64 `protobuf:"varint,2,opt,name=mail_uuid,json=mailUuid,proto3" json:"mail_uuid,omitempty"`                // 要删除的邮件 UUID
}

func (x *CharacterMailDeleteReq) Reset() {
	*x = CharacterMailDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_mail_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterMailDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMailDeleteReq) ProtoMessage() {}

func (x *CharacterMailDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_mail_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMailDeleteReq.ProtoReflect.Descriptor instead.
func (*CharacterMailDeleteReq) Descriptor() ([]byte, []int) {
	return file_msg_mail_proto_rawDescGZIP(), []int{6}
}

func (x *CharacterMailDeleteReq) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CharacterMailDeleteReq) GetMailUuid() uint64 {
	if x != nil {
		return x.MailUuid
	}
	return 0
}

// 0x005005#gateway->client#删除角色邮件-回复
type CharacterMailDeleteRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 已操作邮件所属的角色 UUID
	MailUuid      uint64 `protobuf:"varint,2,opt,name=mail_uuid,json=mailUuid,proto3" json:"mail_uuid,omitempty"`                // 已删除的邮件 UUID
}

func (x *CharacterMailDeleteRes) Reset() {
	*x = CharacterMailDeleteRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_mail_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterMailDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMailDeleteRes) ProtoMessage() {}

func (x *CharacterMailDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_msg_mail_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMailDeleteRes.ProtoReflect.Descriptor instead.
func (*CharacterMailDeleteRes) Descriptor() ([]byte, []int) {
	return file_msg_mail_proto_rawDescGZIP(), []int{7}
}

func (x *CharacterMailDeleteRes) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CharacterMailDeleteRes) GetMailUuid() uint64 {
	if x != nil {
		return x.MailUuid
	}
	return 0
}

// 0x005006#gateway->client#新增角色系统邮件-通知
type CharacterSystemMailNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64      `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 收到新邮件的在线角色 UUID
	MailRecord    *MailRecord `protobuf:"bytes,2,opt,name=mail_record,json=mailRecord,proto3" json:"mail_record,omitempty"`           // Cache 持久化成功的新邮件完整记录
}

func (x *CharacterSystemMailNotify) Reset() {
	*x = CharacterSystemMailNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_mail_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterSystemMailNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSystemMailNotify) ProtoMessage() {}

func (x *CharacterSystemMailNotify) ProtoReflect() protoreflect.Message {
	mi := &file_msg_mail_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSystemMailNotify.ProtoReflect.Descriptor instead.
func (*CharacterSystemMailNotify) Descriptor() ([]byte, []int) {
	return file_msg_mail_proto_rawDescGZIP(), []int{8}
}

func (x *CharacterSystemMailNotify) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CharacterSystemMailNotify) GetMailRecord() *MailRecord {
	if x != nil {
		return x.MailRecord
	}
	return nil
}

var File_msg_mail_proto protoreflect.FileDescriptor

var file_msg_mail_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x2e, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xc9, 0x01, 0x0a, 0x0a, 0x4d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x13,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x2e, 0x0a, 0x13,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4d, 0x73, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x52, 0x65, 0x61, 0x64, 0x22, 0xd6, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f,
	0x78, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x64, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x75, 0x73, 0x65, 0x64,
	0x55, 0x75, 0x69, 0x64, 0x12, 0x51, 0x0a, 0x0f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x4d, 0x61, 0x70, 0x1a, 0x55, 0x0a, 0x12, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3f,
	0x0a, 0x16, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x62,
	0x6f, 0x78, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22,
	0x7e, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c,
	0x62, 0x6f, 0x78, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x3d, 0x0a, 0x0e, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x5f, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x0d, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x22,
	0x5a, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x75, 0x69, 0x64, 0x22, 0x5a, 0x0a, 0x14, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61,
	0x69, 0x6c, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6d,
	0x61, 0x69, 0x6c, 0x55, 0x75, 0x69, 0x64, 0x22, 0x5c, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x69, 0x6c,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6d, 0x61, 0x69,
	0x6c, 0x55, 0x75, 0x69, 0x64, 0x22, 0x5c, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x55,
	0x75, 0x69, 0x64, 0x22, 0x78, 0x0a, 0x19, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x0b, 0x6d, 0x61, 0x69, 0x6c, 0x5f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x52, 0x0a, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x14, 0x5a,
	0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_mail_proto_rawDescOnce sync.Once
	file_msg_mail_proto_rawDescData = file_msg_mail_proto_rawDesc
)

func file_msg_mail_proto_rawDescGZIP() []byte {
	file_msg_mail_proto_rawDescOnce.Do(func() {
		file_msg_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_mail_proto_rawDescData)
	})
	return file_msg_mail_proto_rawDescData
}

var file_msg_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_msg_mail_proto_goTypes = []any{
	(*MailRecord)(nil),                // 0: account.MailRecord
	(*MailboxRecord)(nil),             // 1: account.MailboxRecord
	(*CharacterMailboxGetReq)(nil),    // 2: account.CharacterMailboxGetReq
	(*CharacterMailboxGetRes)(nil),    // 3: account.CharacterMailboxGetRes
	(*CharacterMailReadReq)(nil),      // 4: account.CharacterMailReadReq
	(*CharacterMailReadRes)(nil),      // 5: account.CharacterMailReadRes
	(*CharacterMailDeleteReq)(nil),    // 6: account.CharacterMailDeleteReq
	(*CharacterMailDeleteRes)(nil),    // 7: account.CharacterMailDeleteRes
	(*CharacterSystemMailNotify)(nil), // 8: account.CharacterSystemMailNotify
	nil,                               // 9: account.MailboxRecord.MailRecordMapEntry
}
var file_msg_mail_proto_depIdxs = []int32{
	9, // 0: account.MailboxRecord.mail_record_map:type_name -> account.MailboxRecord.MailRecordMapEntry
	1, // 1: account.CharacterMailboxGetRes.mailbox_record:type_name -> account.MailboxRecord
	0, // 2: account.CharacterSystemMailNotify.mail_record:type_name -> account.MailRecord
	0, // 3: account.MailboxRecord.MailRecordMapEntry.value:type_name -> account.MailRecord
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_msg_mail_proto_init() }
func file_msg_mail_proto_init() {
	if File_msg_mail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_mail_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MailRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_mail_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MailboxRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_mail_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterMailboxGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_mail_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterMailboxGetRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_mail_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterMailReadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_mail_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterMailReadRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_mail_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterMailDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_mail_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterMailDeleteRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_mail_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterSystemMailNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_mail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_mail_proto_goTypes,
		DependencyIndexes: file_msg_mail_proto_depIdxs,
		MessageInfos:      file_msg_mail_proto_msgTypes,
	}.Build()
	File_msg_mail_proto = out.File
	file_msg_mail_proto_rawDesc = nil
	file_msg_mail_proto_goTypes = nil
	file_msg_mail_proto_depIdxs = nil
}
