// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: msg.map.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MapCharacterInfo 是练级地图角色列表使用的完整显示快照.
type MapCharacterInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Character    *CharacterKey `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`                            // 角色唯一标识
	CharacterId  uint64        `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`    // 角色视觉资源 ID
	Nick         string        `protobuf:"bytes,3,opt,name=nick,proto3" json:"nick,omitempty"`                                      // 角色昵称
	RebirthCount uint64        `protobuf:"varint,4,opt,name=rebirth_count,json=rebirthCount,proto3" json:"rebirth_count,omitempty"` // 角色转生次数
	Exp          uint64        `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`                                       // 角色当前原始经验值, 客户端据此计算等级
	MountPetId   uint64        `protobuf:"varint,6,opt,name=mount_pet_id,json=mountPetId,proto3" json:"mount_pet_id,omitempty"`     // 当前骑宠资源 ID; 没有骑宠时为 0
	TeamEnabled  bool          `protobuf:"varint,7,opt,name=team_enabled,json=teamEnabled,proto3" json:"team_enabled,omitempty"`    // 当前登录会话中是否允许组队
	InCombat     bool          `protobuf:"varint,8,opt,name=in_combat,json=inCombat,proto3" json:"in_combat,omitempty"`             // 是否正在战斗; 地图列表据此显示 [vs] 并禁用加入
}

func (x *MapCharacterInfo) Reset() {
	*x = MapCharacterInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapCharacterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapCharacterInfo) ProtoMessage() {}

func (x *MapCharacterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapCharacterInfo.ProtoReflect.Descriptor instead.
func (*MapCharacterInfo) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{0}
}

func (x *MapCharacterInfo) GetCharacter() *CharacterKey {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *MapCharacterInfo) GetCharacterId() uint64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *MapCharacterInfo) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *MapCharacterInfo) GetRebirthCount() uint64 {
	if x != nil {
		return x.RebirthCount
	}
	return 0
}

func (x *MapCharacterInfo) GetExp() uint64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *MapCharacterInfo) GetMountPetId() uint64 {
	if x != nil {
		return x.MountPetId
	}
	return 0
}

func (x *MapCharacterInfo) GetTeamEnabled() bool {
	if x != nil {
		return x.TeamEnabled
	}
	return false
}

func (x *MapCharacterInfo) GetInCombat() bool {
	if x != nil {
		return x.InCombat
	}
	return false
}

// CharacterMapGroup 是可进入地图的第一层展示节点.
// 单人节点只有一项; 队伍节点第一项固定为队长, 后续项保持服务端队伍顺序.
type CharacterMapGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterList []*MapCharacterInfo `protobuf:"bytes,1,rep,name=character_list,json=characterList,proto3" json:"character_list,omitempty"`
}

func (x *CharacterMapGroup) Reset() {
	*x = CharacterMapGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterMapGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMapGroup) ProtoMessage() {}

func (x *CharacterMapGroup) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMapGroup.ProtoReflect.Descriptor instead.
func (*CharacterMapGroup) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterMapGroup) GetCharacterList() []*MapCharacterInfo {
	if x != nil {
		return x.CharacterList
	}
	return nil
}

// 0x00101C#client->gateway#进入地图-请求
type CharacterMapEnterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 发起进入操作的当前账号角色 UUID
	MapId         uint32 `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`                         // 0 表示离开当前地图; 非 0 表示当前版本允许进入的测试、练级或任务地图 ID
}

func (x *CharacterMapEnterReq) Reset() {
	*x = CharacterMapEnterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterMapEnterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMapEnterReq) ProtoMessage() {}

func (x *CharacterMapEnterReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMapEnterReq.ProtoReflect.Descriptor instead.
func (*CharacterMapEnterReq) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterMapEnterReq) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CharacterMapEnterReq) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

// 0x00101D#gateway->client#进入地图-回复
type CharacterMapEnterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64               `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 本次进入地图的接收角色 UUID
	MapId         uint32               `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`                         // 服务端确认的目标地图 ID; 0 表示当前不在任何地图中
	GroupList     []*CharacterMapGroup `protobuf:"bytes,3,rep,name=group_list,json=groupList,proto3" json:"group_list,omitempty"`              // 目标地图全部其他分组, 不包含接收角色所在队伍
}

func (x *CharacterMapEnterRes) Reset() {
	*x = CharacterMapEnterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterMapEnterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMapEnterRes) ProtoMessage() {}

func (x *CharacterMapEnterRes) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMapEnterRes.ProtoReflect.Descriptor instead.
func (*CharacterMapEnterRes) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{3}
}

func (x *CharacterMapEnterRes) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (x *CharacterMapEnterRes) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CharacterMapEnterRes) GetGroupList() []*CharacterMapGroup {
	if x != nil {
		return x.GroupList
	}
	return nil
}

// 0x00101E#gateway->client#地图角色事件-通知
type CharacterMapEventNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetCharacterUuid uint64 `protobuf:"varint,1,opt,name=target_character_uuid,json=targetCharacterUuid,proto3" json:"target_character_uuid,omitempty"` // 本通知对应的接收角色 UUID
	// Types that are assignable to Event:
	//
	//	*CharacterMapEventNotify_MapJoin
	//	*CharacterMapEventNotify_MapLeave
	//	*CharacterMapEventNotify_TeamLeave
	//	*CharacterMapEventNotify_TeamDisband
	//	*CharacterMapEventNotify_TeamJoin
	//	*CharacterMapEventNotify_CharacterUpdate
	Event isCharacterMapEventNotify_Event `protobuf_oneof:"event"`
}

func (x *CharacterMapEventNotify) Reset() {
	*x = CharacterMapEventNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterMapEventNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMapEventNotify) ProtoMessage() {}

func (x *CharacterMapEventNotify) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMapEventNotify.ProtoReflect.Descriptor instead.
func (*CharacterMapEventNotify) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{4}
}

func (x *CharacterMapEventNotify) GetTargetCharacterUuid() uint64 {
	if x != nil {
		return x.TargetCharacterUuid
	}
	return 0
}

func (m *CharacterMapEventNotify) GetEvent() isCharacterMapEventNotify_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *CharacterMapEventNotify) GetMapJoin() *CharacterMapGroup {
	if x, ok := x.GetEvent().(*CharacterMapEventNotify_MapJoin); ok {
		return x.MapJoin
	}
	return nil
}

func (x *CharacterMapEventNotify) GetMapLeave() *CharacterKey {
	if x, ok := x.GetEvent().(*CharacterMapEventNotify_MapLeave); ok {
		return x.MapLeave
	}
	return nil
}

func (x *CharacterMapEventNotify) GetTeamLeave() *CharacterKey {
	if x, ok := x.GetEvent().(*CharacterMapEventNotify_TeamLeave); ok {
		return x.TeamLeave
	}
	return nil
}

func (x *CharacterMapEventNotify) GetTeamDisband() *CharacterKey {
	if x, ok := x.GetEvent().(*CharacterMapEventNotify_TeamDisband); ok {
		return x.TeamDisband
	}
	return nil
}

func (x *CharacterMapEventNotify) GetTeamJoin() *CharacterMapGroup {
	if x, ok := x.GetEvent().(*CharacterMapEventNotify_TeamJoin); ok {
		return x.TeamJoin
	}
	return nil
}

func (x *CharacterMapEventNotify) GetCharacterUpdate() *MapCharacterInfo {
	if x, ok := x.GetEvent().(*CharacterMapEventNotify_CharacterUpdate); ok {
		return x.CharacterUpdate
	}
	return nil
}

type isCharacterMapEventNotify_Event interface {
	isCharacterMapEventNotify_Event()
}

type CharacterMapEventNotify_MapJoin struct {
	MapJoin *CharacterMapGroup `protobuf:"bytes,10,opt,name=map_join,json=mapJoin,proto3,oneof"` // 新加入地图的单人或完整队伍分组
}

type CharacterMapEventNotify_MapLeave struct {
	MapLeave *CharacterKey `protobuf:"bytes,11,opt,name=map_leave,json=mapLeave,proto3,oneof"` // 离开地图的第一层角色身份; 队长表示整队离开
}

type CharacterMapEventNotify_TeamLeave struct {
	TeamLeave *CharacterKey `protobuf:"bytes,12,opt,name=team_leave,json=teamLeave,proto3,oneof"` // 离开队伍并继续留在当前地图的成员身份
}

type CharacterMapEventNotify_TeamDisband struct {
	TeamDisband *CharacterKey `protobuf:"bytes,13,opt,name=team_disband,json=teamDisband,proto3,oneof"` // 解散队伍的队长身份
}

type CharacterMapEventNotify_TeamJoin struct {
	TeamJoin *CharacterMapGroup `protobuf:"bytes,15,opt,name=team_join,json=teamJoin,proto3,oneof"` // 加入队伍后的完整新队伍; 队长固定第一项, 新成员位于末尾
}

type CharacterMapEventNotify_CharacterUpdate struct {
	CharacterUpdate *MapCharacterInfo `protobuf:"bytes,14,opt,name=character_update,json=characterUpdate,proto3,oneof"` // 已有角色最新的完整显示快照
}

func (*CharacterMapEventNotify_MapJoin) isCharacterMapEventNotify_Event() {}

func (*CharacterMapEventNotify_MapLeave) isCharacterMapEventNotify_Event() {}

func (*CharacterMapEventNotify_TeamLeave) isCharacterMapEventNotify_Event() {}

func (*CharacterMapEventNotify_TeamDisband) isCharacterMapEventNotify_Event() {}

func (*CharacterMapEventNotify_TeamJoin) isCharacterMapEventNotify_Event() {}

func (*CharacterMapEventNotify_CharacterUpdate) isCharacterMapEventNotify_Event() {}

var File_msg_map_proto protoreflect.FileDescriptor

var file_msg_map_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x73, 0x67, 0x2e, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x02, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a, 0x09, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x72, 0x65, 0x62, 0x69, 0x72, 0x74, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x20,
	0x0a, 0x0c, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x65, 0x74, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x74, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6d, 0x62, 0x61, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74,
	0x22, 0x55, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x70,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x40, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x4d, 0x61, 0x70, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x14, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x8f, 0x01,
	0x0a, 0x14, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d,
	0x61, 0x70, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0xbc, 0x03, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x70,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x32, 0x0a, 0x15, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x13, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x37, 0x0a, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x48, 0x00, 0x52,
	0x07, 0x6d, 0x61, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x34, 0x0a, 0x09, 0x6d, 0x61, 0x70, 0x5f,
	0x6c, 0x65, 0x61, 0x76, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4b,
	0x65, 0x79, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x61, 0x70, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x36,
	0x0a, 0x0a, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x09, 0x74, 0x65, 0x61,
	0x6d, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x64,
	0x69, 0x73, 0x62, 0x61, 0x6e, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x0b, 0x74, 0x65, 0x61, 0x6d, 0x44, 0x69, 0x73, 0x62, 0x61,
	0x6e, 0x64, 0x12, 0x39, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x48, 0x00, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x46, 0x0a,
	0x10, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x4d, 0x61, 0x70, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x14,
	0x5a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_map_proto_rawDescOnce sync.Once
	file_msg_map_proto_rawDescData = file_msg_map_proto_rawDesc
)

func file_msg_map_proto_rawDescGZIP() []byte {
	file_msg_map_proto_rawDescOnce.Do(func() {
		file_msg_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_map_proto_rawDescData)
	})
	return file_msg_map_proto_rawDescData
}

var file_msg_map_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_msg_map_proto_goTypes = []any{
	(*MapCharacterInfo)(nil),        // 0: account.MapCharacterInfo
	(*CharacterMapGroup)(nil),       // 1: account.CharacterMapGroup
	(*CharacterMapEnterReq)(nil),    // 2: account.CharacterMapEnterReq
	(*CharacterMapEnterRes)(nil),    // 3: account.CharacterMapEnterRes
	(*CharacterMapEventNotify)(nil), // 4: account.CharacterMapEventNotify
	(*CharacterKey)(nil),            // 5: account.CharacterKey
}
var file_msg_map_proto_depIdxs = []int32{
	5, // 0: account.MapCharacterInfo.character:type_name -> account.CharacterKey
	0, // 1: account.CharacterMapGroup.character_list:type_name -> account.MapCharacterInfo
	1, // 2: account.CharacterMapEnterRes.group_list:type_name -> account.CharacterMapGroup
	1, // 3: account.CharacterMapEventNotify.map_join:type_name -> account.CharacterMapGroup
	5, // 4: account.CharacterMapEventNotify.map_leave:type_name -> account.CharacterKey
	5, // 5: account.CharacterMapEventNotify.team_leave:type_name -> account.CharacterKey
	5, // 6: account.CharacterMapEventNotify.team_disband:type_name -> account.CharacterKey
	1, // 7: account.CharacterMapEventNotify.team_join:type_name -> account.CharacterMapGroup
	0, // 8: account.CharacterMapEventNotify.character_update:type_name -> account.MapCharacterInfo
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_msg_map_proto_init() }
func file_msg_map_proto_init() {
	if File_msg_map_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_map_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MapCharacterInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterMapGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterMapEnterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterMapEnterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CharacterMapEventNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_msg_map_proto_msgTypes[4].OneofWrappers = []any{
		(*CharacterMapEventNotify_MapJoin)(nil),
		(*CharacterMapEventNotify_MapLeave)(nil),
		(*CharacterMapEventNotify_TeamLeave)(nil),
		(*CharacterMapEventNotify_TeamDisband)(nil),
		(*CharacterMapEventNotify_TeamJoin)(nil),
		(*CharacterMapEventNotify_CharacterUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_map_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_map_proto_goTypes,
		DependencyIndexes: file_msg_map_proto_depIdxs,
		MessageInfos:      file_msg_map_proto_msgTypes,
	}.Build()
	File_msg_map_proto = out.File
	file_msg_map_proto_rawDesc = nil
	file_msg_map_proto_goTypes = nil
	file_msg_map_proto_depIdxs = nil
}
