// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: msg.gm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GMItemAddCommand 表示给发起命令的角色自身增加道具.
type GMItemAddCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 道具资源 ID, 必须存在于 item.yaml
	Count  uint64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                 // 增加数量, 必须大于 0 且增加后不得发生 uint64 溢出
}

func (x *GMItemAddCommand) Reset() {
	*x = GMItemAddCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_gm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMItemAddCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMItemAddCommand) ProtoMessage() {}

func (x *GMItemAddCommand) ProtoReflect() protoreflect.Message {
	mi := &file_msg_gm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMItemAddCommand.ProtoReflect.Descriptor instead.
func (*GMItemAddCommand) Descriptor() ([]byte, []int) {
	return file_msg_gm_proto_rawDescGZIP(), []int{0}
}

func (x *GMItemAddCommand) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GMItemAddCommand) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GMItemAddResult 表示服务端已持久化的道具增加结果.
type GMItemAddResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId     uint32 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`             // 已增加的道具资源 ID
	AddedCount uint64 `protobuf:"varint,2,opt,name=added_count,json=addedCount,proto3" json:"added_count,omitempty"` // 本次实际增加数量
}

func (x *GMItemAddResult) Reset() {
	*x = GMItemAddResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_gm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMItemAddResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMItemAddResult) ProtoMessage() {}

func (x *GMItemAddResult) ProtoReflect() protoreflect.Message {
	mi := &file_msg_gm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMItemAddResult.ProtoReflect.Descriptor instead.
func (*GMItemAddResult) Descriptor() ([]byte, []int) {
	return file_msg_gm_proto_rawDescGZIP(), []int{1}
}

func (x *GMItemAddResult) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GMItemAddResult) GetAddedCount() uint64 {
	if x != nil {
		return x.AddedCount
	}
	return 0
}

// GMPetAddCommand 表示给发起命令的角色自身增加一只 1 级随身宠物.
type GMPetAddCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PetId    uint32   `protobuf:"varint,1,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`                                // 宠物资源 ID, 必须存在于 pet.yaml
	PetGrade PetGrade `protobuf:"varint,2,opt,name=pet_grade,json=petGrade,proto3,enum=account.PetGrade" json:"pet_grade,omitempty"` // 宠物品阶, 只允许 Common 到 Mythic
}

func (x *GMPetAddCommand) Reset() {
	*x = GMPetAddCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_gm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMPetAddCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMPetAddCommand) ProtoMessage() {}

func (x *GMPetAddCommand) ProtoReflect() protoreflect.Message {
	mi := &file_msg_gm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMPetAddCommand.ProtoReflect.Descriptor instead.
func (*GMPetAddCommand) Descriptor() ([]byte, []int) {
	return file_msg_gm_proto_rawDescGZIP(), []int{2}
}

func (x *GMPetAddCommand) GetPetId() uint32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *GMPetAddCommand) GetPetGrade() PetGrade {
	if x != nil {
		return x.PetGrade
	}
	return PetGrade_PetGrade_Unknow
}

// GMPetAddResult 表示服务端已持久化的随身宠物增加结果.
type GMPetAddResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PetUuid  uint64   `protobuf:"varint,1,opt,name=pet_uuid,json=petUuid,proto3" json:"pet_uuid,omitempty"`                          // 新宠物的账号级唯一 UUID
	PetId    uint32   `protobuf:"varint,2,opt,name=pet_id,json=petId,proto3" json:"pet_id,omitempty"`                                // 已增加的宠物资源 ID
	PetGrade PetGrade `protobuf:"varint,3,opt,name=pet_grade,json=petGrade,proto3,enum=account.PetGrade" json:"pet_grade,omitempty"` // 已增加宠物的品阶
}

func (x *GMPetAddResult) Reset() {
	*x = GMPetAddResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_gm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMPetAddResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMPetAddResult) ProtoMessage() {}

func (x *GMPetAddResult) ProtoReflect() protoreflect.Message {
	mi := &file_msg_gm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMPetAddResult.ProtoReflect.Descriptor instead.
func (*GMPetAddResult) Descriptor() ([]byte, []int) {
	return file_msg_gm_proto_rawDescGZIP(), []int{3}
}

func (x *GMPetAddResult) GetPetUuid() uint64 {
	if x != nil {
		return x.PetUuid
	}
	return 0
}

func (x *GMPetAddResult) GetPetId() uint32 {
	if x != nil {
		return x.PetId
	}
	return 0
}

func (x *GMPetAddResult) GetPetGrade() PetGrade {
	if x != nil {
		return x.PetGrade
	}
	return PetGrade_PetGrade_Unknow
}

// GMSystemMailAddCommand 表示给发起命令的在线角色自身增加一封系统邮件.
type GMSystemMailAddCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title   string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`     // 纯文本主题, 去除首尾空白后不能为空
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 纯文本正文, 使用 LF 保存换行
}

func (x *GMSystemMailAddCommand) Reset() {
	*x = GMSystemMailAddCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_gm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMSystemMailAddCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMSystemMailAddCommand) ProtoMessage() {}

func (x *GMSystemMailAddCommand) ProtoReflect() protoreflect.Message {
	mi := &file_msg_gm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMSystemMailAddCommand.ProtoReflect.Descriptor instead.
func (*GMSystemMailAddCommand) Descriptor() ([]byte, []int) {
	return file_msg_gm_proto_rawDescGZIP(), []int{4}
}

func (x *GMSystemMailAddCommand) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GMSystemMailAddCommand) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// GMSystemMailAddResult 表示 Cache 已持久化的系统邮件增加结果.
type GMSystemMailAddResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailUuid uint64 `protobuf:"varint,1,opt,name=mail_uuid,json=mailUuid,proto3" json:"mail_uuid,omitempty"` // 新邮件在当前角色邮箱中的 UUID
}

func (x *GMSystemMailAddResult) Reset() {
	*x = GMSystemMailAddResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_gm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMSystemMailAddResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMSystemMailAddResult) ProtoMessage() {}

func (x *GMSystemMailAddResult) ProtoReflect() protoreflect.Message {
	mi := &file_msg_gm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMSystemMailAddResult.ProtoReflect.Descriptor instead.
func (*GMSystemMailAddResult) Descriptor() ([]byte, []int) {
	return file_msg_gm_proto_rawDescGZIP(), []int{5}
}

func (x *GMSystemMailAddResult) GetMailUuid() uint64 {
	if x != nil {
		return x.MailUuid
	}
	return 0
}

// 0x00f000#client->gateway#执行GM命令-请求
type GMCommandReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 发起命令并接收结果的当前账号在线角色 UUID
	// Types that are assignable to Command:
	//
	//	*GMCommandReq_ItemAdd
	//	*GMCommandReq_PetAdd
	//	*GMCommandReq_MailAdd
	Command isGMCommandReq_Command `protobuf_oneof:"command"`
}

func (x *GMCommandReq) Reset() {
	*x = GMCommandReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_gm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMCommandReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMCommandReq) ProtoMessage() {}

func (x *GMCommandReq) ProtoReflect() protoreflect.Message {
	mi := &file_msg_gm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMCommandReq.ProtoReflect.Descriptor instead.
func (*GMCommandReq) Descriptor() ([]byte, []int) {
	return file_msg_gm_proto_rawDescGZIP(), []int{6}
}

func (x *GMCommandReq) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (m *GMCommandReq) GetCommand() isGMCommandReq_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *GMCommandReq) GetItemAdd() *GMItemAddCommand {
	if x, ok := x.GetCommand().(*GMCommandReq_ItemAdd); ok {
		return x.ItemAdd
	}
	return nil
}

func (x *GMCommandReq) GetPetAdd() *GMPetAddCommand {
	if x, ok := x.GetCommand().(*GMCommandReq_PetAdd); ok {
		return x.PetAdd
	}
	return nil
}

func (x *GMCommandReq) GetMailAdd() *GMSystemMailAddCommand {
	if x, ok := x.GetCommand().(*GMCommandReq_MailAdd); ok {
		return x.MailAdd
	}
	return nil
}

type isGMCommandReq_Command interface {
	isGMCommandReq_Command()
}

type GMCommandReq_ItemAdd struct {
	ItemAdd *GMItemAddCommand `protobuf:"bytes,10,opt,name=item_add,json=itemAdd,proto3,oneof"` // 对应客户端文本命令 gm item add <id> <cnt>
}

type GMCommandReq_PetAdd struct {
	PetAdd *GMPetAddCommand `protobuf:"bytes,11,opt,name=pet_add,json=petAdd,proto3,oneof"` // 对应客户端文本命令 gm pet add <petid> <petGrade>
}

type GMCommandReq_MailAdd struct {
	MailAdd *GMSystemMailAddCommand `protobuf:"bytes,12,opt,name=mail_add,json=mailAdd,proto3,oneof"` // 对应客户端文本命令 gm mail add <主题>|<正文>
}

func (*GMCommandReq_ItemAdd) isGMCommandReq_Command() {}

func (*GMCommandReq_PetAdd) isGMCommandReq_Command() {}

func (*GMCommandReq_MailAdd) isGMCommandReq_Command() {}

// 0x00f001#gateway->client#执行GM命令-回复
type GMCommandRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CharacterUuid uint64 `protobuf:"varint,1,opt,name=character_uuid,json=characterUuid,proto3" json:"character_uuid,omitempty"` // 已执行命令的角色 UUID
	// Types that are assignable to Result:
	//
	//	*GMCommandRes_ItemAdd
	//	*GMCommandRes_PetAdd
	//	*GMCommandRes_MailAdd
	Result isGMCommandRes_Result `protobuf_oneof:"result"`
}

func (x *GMCommandRes) Reset() {
	*x = GMCommandRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_gm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMCommandRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMCommandRes) ProtoMessage() {}

func (x *GMCommandRes) ProtoReflect() protoreflect.Message {
	mi := &file_msg_gm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMCommandRes.ProtoReflect.Descriptor instead.
func (*GMCommandRes) Descriptor() ([]byte, []int) {
	return file_msg_gm_proto_rawDescGZIP(), []int{7}
}

func (x *GMCommandRes) GetCharacterUuid() uint64 {
	if x != nil {
		return x.CharacterUuid
	}
	return 0
}

func (m *GMCommandRes) GetResult() isGMCommandRes_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GMCommandRes) GetItemAdd() *GMItemAddResult {
	if x, ok := x.GetResult().(*GMCommandRes_ItemAdd); ok {
		return x.ItemAdd
	}
	return nil
}

func (x *GMCommandRes) GetPetAdd() *GMPetAddResult {
	if x, ok := x.GetResult().(*GMCommandRes_PetAdd); ok {
		return x.PetAdd
	}
	return nil
}

func (x *GMCommandRes) GetMailAdd() *GMSystemMailAddResult {
	if x, ok := x.GetResult().(*GMCommandRes_MailAdd); ok {
		return x.MailAdd
	}
	return nil
}

type isGMCommandRes_Result interface {
	isGMCommandRes_Result()
}

type GMCommandRes_ItemAdd struct {
	ItemAdd *GMItemAddResult `protobuf:"bytes,10,opt,name=item_add,json=itemAdd,proto3,oneof"` // 已持久化的道具增加结果
}

type GMCommandRes_PetAdd struct {
	PetAdd *GMPetAddResult `protobuf:"bytes,11,opt,name=pet_add,json=petAdd,proto3,oneof"` // 已持久化的随身宠物增加结果
}

type GMCommandRes_MailAdd struct {
	MailAdd *GMSystemMailAddResult `protobuf:"bytes,12,opt,name=mail_add,json=mailAdd,proto3,oneof"` // 已持久化的系统邮件增加结果
}

func (*GMCommandRes_ItemAdd) isGMCommandRes_Result() {}

func (*GMCommandRes_PetAdd) isGMCommandRes_Result() {}

func (*GMCommandRes_MailAdd) isGMCommandRes_Result() {}

var File_msg_gm_proto protoreflect.FileDescriptor

var file_msg_gm_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x73, 0x67, 0x2e, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x0d, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x10, 0x47, 0x4d, 0x49, 0x74, 0x65, 0x6d,
	0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74,
	0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x0f, 0x47, 0x4d, 0x49,
	0x74, 0x65, 0x6d, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x65, 0x64, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x65,
	0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x4a, 0x04, 0x08, 0x03, 0x10, 0x04, 0x22, 0x58, 0x0a, 0x0f,
	0x47, 0x4d, 0x50, 0x65, 0x74, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x70, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x70, 0x65, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x09, 0x70, 0x65, 0x74, 0x5f, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x50, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x52, 0x08, 0x70, 0x65,
	0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x22, 0x72, 0x0a, 0x0e, 0x47, 0x4d, 0x50, 0x65, 0x74, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x74, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x65, 0x74, 0x55,
	0x75, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x65, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x09, 0x70, 0x65,
	0x74, 0x5f, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x50, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65,
	0x52, 0x08, 0x70, 0x65, 0x74, 0x47, 0x72, 0x61, 0x64, 0x65, 0x22, 0x48, 0x0a, 0x16, 0x47, 0x4d,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0x34, 0x0a, 0x15, 0x47, 0x4d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x4d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x75, 0x69, 0x64, 0x22, 0xeb, 0x01, 0x0a, 0x0c, 0x47,
	0x4d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x36, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47,
	0x4d, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48,
	0x00, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x41, 0x64, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x70, 0x65,
	0x74, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x4d, 0x50, 0x65, 0x74, 0x41, 0x64, 0x64, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x06, 0x70, 0x65, 0x74, 0x41, 0x64, 0x64, 0x12,
	0x3c, 0x0a, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x4d, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x42, 0x09, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0xe7, 0x01, 0x0a, 0x0c, 0x47, 0x4d, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0d, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64,
	0x12, 0x35, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x4d, 0x49,
	0x74, 0x65, 0x6d, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x07,
	0x69, 0x74, 0x65, 0x6d, 0x41, 0x64, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x70, 0x65, 0x74, 0x5f, 0x61,
	0x64, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x47, 0x4d, 0x50, 0x65, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x48, 0x00, 0x52, 0x06, 0x70, 0x65, 0x74, 0x41, 0x64, 0x64, 0x12, 0x3b, 0x0a, 0x08, 0x6d,
	0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x4d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x4d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52,
	0x07, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x14, 0x5a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_gm_proto_rawDescOnce sync.Once
	file_msg_gm_proto_rawDescData = file_msg_gm_proto_rawDesc
)

func file_msg_gm_proto_rawDescGZIP() []byte {
	file_msg_gm_proto_rawDescOnce.Do(func() {
		file_msg_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_gm_proto_rawDescData)
	})
	return file_msg_gm_proto_rawDescData
}

var file_msg_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_msg_gm_proto_goTypes = []any{
	(*GMItemAddCommand)(nil),       // 0: account.GMItemAddCommand
	(*GMItemAddResult)(nil),        // 1: account.GMItemAddResult
	(*GMPetAddCommand)(nil),        // 2: account.GMPetAddCommand
	(*GMPetAddResult)(nil),         // 3: account.GMPetAddResult
	(*GMSystemMailAddCommand)(nil), // 4: account.GMSystemMailAddCommand
	(*GMSystemMailAddResult)(nil),  // 5: account.GMSystemMailAddResult
	(*GMCommandReq)(nil),           // 6: account.GMCommandReq
	(*GMCommandRes)(nil),           // 7: account.GMCommandRes
	(PetGrade)(0),                  // 8: account.PetGrade
}
var file_msg_gm_proto_depIdxs = []int32{
	8, // 0: account.GMPetAddCommand.pet_grade:type_name -> account.PetGrade
	8, // 1: account.GMPetAddResult.pet_grade:type_name -> account.PetGrade
	0, // 2: account.GMCommandReq.item_add:type_name -> account.GMItemAddCommand
	2, // 3: account.GMCommandReq.pet_add:type_name -> account.GMPetAddCommand
	4, // 4: account.GMCommandReq.mail_add:type_name -> account.GMSystemMailAddCommand
	1, // 5: account.GMCommandRes.item_add:type_name -> account.GMItemAddResult
	3, // 6: account.GMCommandRes.pet_add:type_name -> account.GMPetAddResult
	5, // 7: account.GMCommandRes.mail_add:type_name -> account.GMSystemMailAddResult
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_msg_gm_proto_init() }
func file_msg_gm_proto_init() {
	if File_msg_gm_proto != nil {
		return
	}
	file_msg_pet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_gm_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GMItemAddCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_gm_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GMItemAddResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_gm_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GMPetAddCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_gm_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GMPetAddResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_gm_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GMSystemMailAddCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_gm_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GMSystemMailAddResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_gm_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GMCommandReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_gm_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GMCommandRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_msg_gm_proto_msgTypes[6].OneofWrappers = []any{
		(*GMCommandReq_ItemAdd)(nil),
		(*GMCommandReq_PetAdd)(nil),
		(*GMCommandReq_MailAdd)(nil),
	}
	file_msg_gm_proto_msgTypes[7].OneofWrappers = []any{
		(*GMCommandRes_ItemAdd)(nil),
		(*GMCommandRes_PetAdd)(nil),
		(*GMCommandRes_MailAdd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_gm_proto_goTypes,
		DependencyIndexes: file_msg_gm_proto_depIdxs,
		MessageInfos:      file_msg_gm_proto_msgTypes,
	}.Build()
	File_msg_gm_proto = out.File
	file_msg_gm_proto_rawDesc = nil
	file_msg_gm_proto_goTypes = nil
	file_msg_gm_proto_depIdxs = nil
}
