// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.0
// source: online.grpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnlineService_OnlineBindAccount_FullMethodName   = "/online.OnlineService/OnlineBindAccount"
	OnlineService_OnlineUnbindAccount_FullMethodName = "/online.OnlineService/OnlineUnbindAccount"
	OnlineService_OnlineStreamTunnel_FullMethodName  = "/online.OnlineService/OnlineStreamTunnel"
)

// OnlineServiceClient is the client API for OnlineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnlineServiceClient interface {
	// 控制面：绑定 Account actor (Unary RPC)
	// 作用: Gateway 完成 connectTicket 校验和 accountSession 抢占后, 通过此接口通知 Online 建立 Account actor。
	// 特性: Online 只负责绑定 Account actor, 不读写 cache accountSession。
	OnlineBindAccount(ctx context.Context, in *OnlineBindAccountReq, opts ...grpc.CallOption) (*OnlineBindAccountRes, error)
	// 控制面：解绑 Account actor (Unary RPC)
	// 作用: Gateway 在 TCP 断开、顶号、主动离线和回滚等场景下, 同步通知 Online 解绑 Account actor。
	OnlineUnbindAccount(ctx context.Context, in *OnlineUnbindAccountReq, opts ...grpc.CallOption) (*OnlineUnbindAccountRes, error)
	// 数据面：全互联双向流隧道 (Bidirectional Stream)
	// 作用: 承载 Gateway 与该 Online 节点之间所有账号的上下行数据。
	// 特性：支持批量打包 (Batching)，极其高效。
	OnlineStreamTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OnlineStreamTunnelReq, OnlineStreamTunnelRes], error)
}

type onlineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnlineServiceClient(cc grpc.ClientConnInterface) OnlineServiceClient {
	return &onlineServiceClient{cc}
}

func (c *onlineServiceClient) OnlineBindAccount(ctx context.Context, in *OnlineBindAccountReq, opts ...grpc.CallOption) (*OnlineBindAccountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineBindAccountRes)
	err := c.cc.Invoke(ctx, OnlineService_OnlineBindAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onlineServiceClient) OnlineUnbindAccount(ctx context.Context, in *OnlineUnbindAccountReq, opts ...grpc.CallOption) (*OnlineUnbindAccountRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineUnbindAccountRes)
	err := c.cc.Invoke(ctx, OnlineService_OnlineUnbindAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *onlineServiceClient) OnlineStreamTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OnlineStreamTunnelReq, OnlineStreamTunnelRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OnlineService_ServiceDesc.Streams[0], OnlineService_OnlineStreamTunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OnlineStreamTunnelReq, OnlineStreamTunnelRes]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OnlineService_OnlineStreamTunnelClient = grpc.BidiStreamingClient[OnlineStreamTunnelReq, OnlineStreamTunnelRes]

// OnlineServiceServer is the server API for OnlineService service.
// All implementations must embed UnimplementedOnlineServiceServer
// for forward compatibility.
type OnlineServiceServer interface {
	// 控制面：绑定 Account actor (Unary RPC)
	// 作用: Gateway 完成 connectTicket 校验和 accountSession 抢占后, 通过此接口通知 Online 建立 Account actor。
	// 特性: Online 只负责绑定 Account actor, 不读写 cache accountSession。
	OnlineBindAccount(context.Context, *OnlineBindAccountReq) (*OnlineBindAccountRes, error)
	// 控制面：解绑 Account actor (Unary RPC)
	// 作用: Gateway 在 TCP 断开、顶号、主动离线和回滚等场景下, 同步通知 Online 解绑 Account actor。
	OnlineUnbindAccount(context.Context, *OnlineUnbindAccountReq) (*OnlineUnbindAccountRes, error)
	// 数据面：全互联双向流隧道 (Bidirectional Stream)
	// 作用: 承载 Gateway 与该 Online 节点之间所有账号的上下行数据。
	// 特性：支持批量打包 (Batching)，极其高效。
	OnlineStreamTunnel(grpc.BidiStreamingServer[OnlineStreamTunnelReq, OnlineStreamTunnelRes]) error
	mustEmbedUnimplementedOnlineServiceServer()
}

// UnimplementedOnlineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnlineServiceServer struct{}

func (UnimplementedOnlineServiceServer) OnlineBindAccount(context.Context, *OnlineBindAccountReq) (*OnlineBindAccountRes, error) {
	return nil, status.Error(codes.Unimplemented, "method OnlineBindAccount not implemented")
}
func (UnimplementedOnlineServiceServer) OnlineUnbindAccount(context.Context, *OnlineUnbindAccountReq) (*OnlineUnbindAccountRes, error) {
	return nil, status.Error(codes.Unimplemented, "method OnlineUnbindAccount not implemented")
}
func (UnimplementedOnlineServiceServer) OnlineStreamTunnel(grpc.BidiStreamingServer[OnlineStreamTunnelReq, OnlineStreamTunnelRes]) error {
	return status.Error(codes.Unimplemented, "method OnlineStreamTunnel not implemented")
}
func (UnimplementedOnlineServiceServer) mustEmbedUnimplementedOnlineServiceServer() {}
func (UnimplementedOnlineServiceServer) testEmbeddedByValue()                       {}

// UnsafeOnlineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnlineServiceServer will
// result in compilation errors.
type UnsafeOnlineServiceServer interface {
	mustEmbedUnimplementedOnlineServiceServer()
}

func RegisterOnlineServiceServer(s grpc.ServiceRegistrar, srv OnlineServiceServer) {
	// If the following call panics, it indicates UnimplementedOnlineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnlineService_ServiceDesc, srv)
}

func _OnlineService_OnlineBindAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineBindAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineServiceServer).OnlineBindAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnlineService_OnlineBindAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineServiceServer).OnlineBindAccount(ctx, req.(*OnlineBindAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnlineService_OnlineUnbindAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineUnbindAccountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnlineServiceServer).OnlineUnbindAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnlineService_OnlineUnbindAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnlineServiceServer).OnlineUnbindAccount(ctx, req.(*OnlineUnbindAccountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OnlineService_OnlineStreamTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OnlineServiceServer).OnlineStreamTunnel(&grpc.GenericServerStream[OnlineStreamTunnelReq, OnlineStreamTunnelRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OnlineService_OnlineStreamTunnelServer = grpc.BidiStreamingServer[OnlineStreamTunnelReq, OnlineStreamTunnelRes]

// OnlineService_ServiceDesc is the grpc.ServiceDesc for OnlineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnlineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "online.OnlineService",
	HandlerType: (*OnlineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnlineBindAccount",
			Handler:    _OnlineService_OnlineBindAccount_Handler,
		},
		{
			MethodName: "OnlineUnbindAccount",
			Handler:    _OnlineService_OnlineUnbindAccount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnlineStreamTunnel",
			Handler:       _OnlineService_OnlineStreamTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "online.grpc.proto",
}
