// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: weapon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterWeaponType int32

const (
	CharacterWeaponType_CharacterWeaponType_Unknow  CharacterWeaponType = 0
	CharacterWeaponType_CharacterWeaponType_Unarmed CharacterWeaponType = 1 // 空手/爪/投掷斧/回旋镖/石头
	CharacterWeaponType_CharacterWeaponType_Axe     CharacterWeaponType = 2 // 斧头
	CharacterWeaponType_CharacterWeaponType_Bow     CharacterWeaponType = 3 // 弓
	CharacterWeaponType_CharacterWeaponType_Spear   CharacterWeaponType = 4 // 长枪
	CharacterWeaponType_CharacterWeaponType_Stick   CharacterWeaponType = 5 // 棍棒
	CharacterWeaponType_CharacterWeaponType_Max     CharacterWeaponType = 6
)

// Enum value maps for CharacterWeaponType.
var (
	CharacterWeaponType_name = map[int32]string{
		0: "CharacterWeaponType_Unknow",
		1: "CharacterWeaponType_Unarmed",
		2: "CharacterWeaponType_Axe",
		3: "CharacterWeaponType_Bow",
		4: "CharacterWeaponType_Spear",
		5: "CharacterWeaponType_Stick",
		6: "CharacterWeaponType_Max",
	}
	CharacterWeaponType_value = map[string]int32{
		"CharacterWeaponType_Unknow":  0,
		"CharacterWeaponType_Unarmed": 1,
		"CharacterWeaponType_Axe":     2,
		"CharacterWeaponType_Bow":     3,
		"CharacterWeaponType_Spear":   4,
		"CharacterWeaponType_Stick":   5,
		"CharacterWeaponType_Max":     6,
	}
)

func (x CharacterWeaponType) Enum() *CharacterWeaponType {
	p := new(CharacterWeaponType)
	*p = x
	return p
}

func (x CharacterWeaponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharacterWeaponType) Descriptor() protoreflect.EnumDescriptor {
	return file_weapon_proto_enumTypes[0].Descriptor()
}

func (CharacterWeaponType) Type() protoreflect.EnumType {
	return &file_weapon_proto_enumTypes[0]
}

func (x CharacterWeaponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CharacterWeaponType.Descriptor instead.
func (CharacterWeaponType) EnumDescriptor() ([]byte, []int) {
	return file_weapon_proto_rawDescGZIP(), []int{0}
}

var File_weapon_proto protoreflect.FileDescriptor

var file_weapon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0xeb, 0x01, 0x0a, 0x13, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1e, 0x0a, 0x1a, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12,
	0x1f, 0x0a, 0x1b, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x57, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x6e, 0x61, 0x72, 0x6d, 0x65, 0x64, 0x10, 0x01,
	0x12, 0x1b, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x57, 0x65, 0x61,
	0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x41, 0x78, 0x65, 0x10, 0x02, 0x12, 0x1b, 0x0a,
	0x17, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x5f, 0x42, 0x6f, 0x77, 0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x53, 0x70, 0x65, 0x61, 0x72, 0x10, 0x04, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x53, 0x74, 0x69, 0x63, 0x6b, 0x10, 0x05, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f,
	0x4d, 0x61, 0x78, 0x10, 0x06, 0x42, 0x14, 0x5a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_weapon_proto_rawDescOnce sync.Once
	file_weapon_proto_rawDescData = file_weapon_proto_rawDesc
)

func file_weapon_proto_rawDescGZIP() []byte {
	file_weapon_proto_rawDescOnce.Do(func() {
		file_weapon_proto_rawDescData = protoimpl.X.CompressGZIP(file_weapon_proto_rawDescData)
	})
	return file_weapon_proto_rawDescData
}

var file_weapon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_weapon_proto_goTypes = []any{
	(CharacterWeaponType)(0), // 0: account.CharacterWeaponType
}
var file_weapon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weapon_proto_init() }
func file_weapon_proto_init() {
	if File_weapon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_weapon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weapon_proto_goTypes,
		DependencyIndexes: file_weapon_proto_depIdxs,
		EnumInfos:         file_weapon_proto_enumTypes,
	}.Build()
	File_weapon_proto = out.File
	file_weapon_proto_rawDesc = nil
	file_weapon_proto_goTypes = nil
	file_weapon_proto_depIdxs = nil
}
